### ISSUE TITLE
Solar panel snag list

### ISSUE THREAD

**Issue by iteles** [dwyl/home#102]
The application of the solar panels is now complete (see #20 for more details), but the installation caused two major issues:
+ Someone stepped on the gutter, which caused all the water to build up on one side of the roof and be dumped out infront of our garage, flooding the basement https://github.com/dwyl/home/issues/20#issuecomment-549135213
+ When installing the solar panel frame, they appear to have opened fissures in the roof (see black lines in photos below) which they then attempted to cover with isolating 'tela liquidia' (the lighter clay coloured plastic looking paint in the photos below), which clearly did not work correctly:
![IMG_20191125_085058](https://user-images.githubusercontent.com/4185328/69717657-5f062100-1104-11ea-84fb-9e21602a00ee.jpg)
![IMG_20191125_085109](https://user-images.githubusercontent.com/4185328/69717664-60374e00-1104-11ea-856b-4cceef844b32.jpg)

This is the damage that has now been caused, which Carlos is busy fixing
![IMG_20191125_085620](https://user-images.githubusercontent.com/4185328/69717651-5c0b3080-1104-11ea-991a-e38f4699fa20.jpg)
![IMG_20191125_085730](https://user-images.githubusercontent.com/4185328/69717652-5ca3c700-1104-11ea-8dee-1a9f158d2d91.jpg)
![IMG_20191125_085633](https://user-images.githubusercontent.com/4185328/69717655-5dd4f400-1104-11ea-9931-d5ddbee4a340.jpg)

## Tasks
+ [ ] Fix guttering
  + [ ] Speak to Pedro for budget
  + [ ] Email DAPE to confirm this will be going ahead on their dime
  + [ ] Book in the work
  + [ ] Work completed
  + [ ] Email DAPE with invoice (to be deducted from what we pay them)
+ [ ] Fix leaks from fissures 
  + [ ] Email DAPE to confirm what is happening with photos
  + [ ] Carlos to perform fixes
  + [ ] Email DAPE with invoice (to be deducted from what we pay them)

Making this a `priority-1` because of its destructive nature.

**Comment by iteles** [comment]
The roof leaks were repaired by Carlos just before Christmas (and a massive rainstorm). 

The guys who installed our gutters went by and noted that they would require scaffolding to get it done (this is why we put the gutters on BEFORE the roof) so it would make more sense to do it when scaffolding was in place nearby or in the area (he mentioned Pedro had said it possibly would be for #14?). 

There is a patch in place so pulling the priority of this down.

**Comment by iteles** [comment]
The fissures were _not_ repaired it turns out. But it's been far too long to be able to charge DAPE for this (thanks pandemic).

Will open new issues for these.
