### ISSUE TITLE
Parts missing from urinol flushes

### ISSUE THREAD

**Issue by iteles** [dwyl/home#109]
This affects both the plumbing snag list #96 and the electricians snag list #108 so I've opened it as a separate issue given there are various actors.

Whilst going into the urinol flushes today to make the final electrical connections (these were only done temporarily by the plumbers), the electrician noted that there are a couple of things missing:
+ Neither flush has a transformer (which it requires as per the manufacturer's installation requirements)
+ One flush is missing the 'electrovalvula' (you can see it's missing from the top photo below)

![63e49cac-9e8e-4f80-8664-bbc1d028c2ae](https://user-images.githubusercontent.com/4185328/72364046-bf214880-36ed-11ea-9af2-177fd8d3eb44.jpg)
![34015e1a-6001-419d-91d3-aa3164222113](https://user-images.githubusercontent.com/4185328/72364047-bf214880-36ed-11ea-9eb5-13743e923485.jpg)

## Tasks
+ [x] Email plumbers to alert them to the issue and figure out what's happened to the missing parts
+ [ ] Chase by phone and get confirmation of next steps
+ [ ] Receive missing parts from plumbers
+ [ ] Electricians to install

**Comment by iteles** [comment]
Emailed plumbers today.
