### ISSUE TITLE
New water meter

### ISSUE THREAD

**Issue by iteles** [dwyl/home#117]
As per #96, we've had to move the water meter to the outside of the house.

The plumbing is all done and we just need to get the new meter so it can be installed.
How, you ask? Great question.

## Tasks
+ [x] Go to [AGERE](http://agere.pt/) to find out what paperwork/actions are needed to get a new water meter
  + [x] Check in with the pool guys to check if they have any specific requirements
  + [x] Confirm that the plumbers can have someone here to accompany the work **[Email request sent 13-Feb-2020]**
  + [x] Get Carlos to come in and check his part is also complete
+ ~[ ] Get licença de ocupação de via for the plumbers to connect to the ramal (1day)~
+ ~[ ] AGERE to provide us with a new meter~
+ ~[ ] Plumbers to do the work for the ramal~
+ ~[ ] AGERE to come out and connect the new ramal~
+ [x] Plumbers to make sure everything is ready for the permanent connection
+ [x] AGERE to switch off the water
+ [x] Plumbers to make the permanent connection based on the conversation had with AGERE and the plumbers yesterday
+ [x] AGERE to move the water meter from inside to outside and switch the water back on

~I predict this exercise will cost us no less than €800-1000.~

Adding a priority-1 label because it is a _lengthy_ process and needs to get done this week.

**Comment by iteles** [comment]
The water meter will be moved from inside to outside on 4-Mar-2020 at 09h00.

Before this happens we need to:
+ Check in with the pool guys to check if they have any specific requirements
+ Confirm that the plumbers can have someone here to accompany the work 
+ Get Carlos to come in and check his part is also complete

**Comment by iteles** [comment]
AGERE came yesterday to discuss what needed to be done.

The plumbers found and exposed the current piping and prepared the water meter box with permanent tubing. 

AGERE were supposed to come and switch off the water today and the plumbers were to finalise the connection before AGERE came back to switch on the water again and move the water meter. However, given that it was raining, this has been **pushed back to Monday, 9-Mar-2020 at 09h00**.

@nelsonic In light of this, we should put the cover back on the water meter box for now.

<hr/> 

We also discussed yesterday that in actual fact, no increase in the ramal is necessary because the tubing that comes into the house is 1" which matches the tubing in the house itself.

We will be sending the water off for testing and seeing if there is any need to change this for other reasons.

**Comment by iteles** [comment]
After someone parking directly over the water access point yesterday, AGERE couldn't switch off the water, so the work could not be completed.

This has now been rescheduled for Thursday 12th March at 10h00.

**Comment by iteles** [comment]
This was completed 👍 

Thanks for fixing the lid for the water meter @nelsonic
