### ISSUE TITLE
[SPIKE] Setup Dust Commander Extraction in Workshop

### ISSUE THREAD

**Issue by nelsonic** [dwyl/home#121]
At present we do not have _any_ (_dedicated_) dust extraction in the workshop so I have _manually_ swept/collected the sawdust after making the handful of items I've made. Manual cleanup is "OK" for small pieces but tedious and a waste of time. We can do better.
We _already_ have a Bosch ([GAS Pro 20L](https://www.leroymerlin.pt/Produtos/Ferramentas/Aspiradores/Aspiradores/WPR_REF_81865767)) Shop Vac (that I used to use in the London workshop) 
and I bought a [dust commander](https://www.dust-commander.com/gb/p/9-cyclone-filter-dust-commander-dlx-3760013430023.html) cyclone filter ... I just need to put it all together with the relevant hoses. 

# Todo

+ [ ] Attach Dust Commander to top of Dust Collection Tank.
  + [ ] Visit Leroy and buy the necessary parts (tubes and connectors) to connect everything
+ [ ] Measure everything up and make notes on how to make the movable cart
+ [ ] Create a wheeled "cart" to store both the Shop Vac and  Dust Tank
  + [ ] See: Steve Ramsey (Woodworking for Mere Mortals) "Affordable Dust Collection for the Home Workshop"  https://youtu.be/3ni1Pf-wwo0
