### ISSUE TITLE
Washing Machine Setup

### ISSUE THREAD

**Issue by nelsonic** [dwyl/home#124]
Installing the washing machine requires a tube to connect the machine to the house plumbing.

I took accurate measurements of the pipe fitting dimensions using my digital caliper:

![IMG_20200623_110117](https://user-images.githubusercontent.com/194400/85390974-7b0a5d80-b541-11ea-8e6f-53948b6d2b32.jpg)

![IMG_20200623_110245](https://user-images.githubusercontent.com/194400/85390994-82316b80-b541-11ea-9161-86ac7f9d6341.jpg)

Both ends appear to be around the 26mm (rounded up) _external_ diameter. The thread is on the outside at both ends so that's the measurement we care about.

# Todo

+ [x] Go to hardware store and buy required pipe to connect the machine to the water mains.
+ [x] Do the work of connecting
+ [x] Run a test wash using the dirty (construction) towels and sheets (after shaking them out outside for any larger debris).

I will roll this trip to Leroy into my next store visit 
to buy building materials, so it's not a special trip. Expect the setup to take around 20mins and the first wash around 1h.

**Comment by nelsonic** [comment]
Annoyingly, the Samsung washing machine has a different diameter of inlet: 26.85mm 🙄

![IMG_20200623_111250](https://user-images.githubusercontent.com/194400/85391989-d1c46700-b542-11ea-9c9f-3d8eb23eaefa.jpg)

I will check if Leroy has an adapter or the bigger thread size connector. If not might have to visit a specialty plumbing store. ⏳

**Comment by nelsonic** [comment]
@iteles I've installed the 12kg (towels & linen) machine:
![IMG_20200623_161559](https://user-images.githubusercontent.com/194400/85433943-2553a680-b57d-11ea-941f-45d1d9df79dc.jpg)

It works. ✅

Now I'm figuring out if I should install the 8kg "everyday" use machine *above* the 12kg or on the step to the right:

![IMG_20200623_183356](https://user-images.githubusercontent.com/194400/85435937-220dea00-b580-11ea-8d05-3431e3b86ad7.jpg)


The reason I'm having second thoughts about stacking the two washing machines is because if we install the 8kg machine above the 12kg, the drawer for adding laundry detergent will be at 180cm above the ground:

![IMG_20200623_181536](https://user-images.githubusercontent.com/194400/85434818-8760db80-b57e-11ea-95a7-a547d7c69ad4.jpg)

This is because the 12kg is on a step and thus the top is at 100.5 cm from the ground:
![IMG_20200623_181710](https://user-images.githubusercontent.com/194400/85434371-dbb78b80-b57d-11ea-954e-b9ca78b01112.jpg)

If we put the 8kg machine on top, the laundry detergent drawer will not be accessible to _average_ height people. Instead they will need to use a step ladder in order to add their detergent.
This is not a problem a few times, but could get tedious after a while ... 🤔

Baring in mind that the clothes dryer has an outlet tube for excess liquid/moisture so there will be a tube going from the shelf to the drainage point regardless of which machine we place on the shelf.
The difference is there will be *one* tube if the dryer is on the shelf and *two* pipes if the washing machine is on the shelf.

What are your thoughts? 💭

**Comment by nelsonic** [comment]
I have placed the dryer on the shelf as we had previously discussed (verbally):

![IMG_20200624_094200](https://user-images.githubusercontent.com/194400/85523615-22999580-b5ff-11ea-8507-3f8915cd1cee.jpg)

If we decide to move it later we can.
I just need to move _forward_ with this _now_.

**Comment by iteles** [comment]
I agree with you that we can't realistically have the detergent drawer that far up though. We'll try it with a stepstool at first but I think ultimately we'll end up changing them.

**Comment by nelsonic** [comment]
@iteles once I get good with designing folding furniture I could make a fold-away stepstool. Or we can just encourage people to use the soap ball (that you put liquid detergent in the drum). But either way it’s very high up. Also the machine is *very* heavy so I will need help to lift it.

**Comment by nelsonic** [comment]
Both machines now installed. See #151 for more photos. 👍🏻
