### ISSUE TITLE
Psychodidae 🤦‍♂️

### ISSUE THREAD

**Issue by nelsonic** [dwyl/home#125]
For whatever reason one of the drains in the basement has these flies.
We need to address the problem systematically so that they do not reappear.

https://en.wikipedia.org/wiki/Psychodidae
![image](https://user-images.githubusercontent.com/194400/85557203-7916cc00-b61f-11ea-9d68-90561035a304.png)

![image](https://user-images.githubusercontent.com/194400/85558435-a31cbe00-b620-11ea-934a-590120e69b53.png)

# Todo

+ [ ] investigate the options for eliminating the pest 
+ [ ] investigate long-term solution to avoid them returning

**Comment by nelsonic** [comment]
The first thing we need to do is eliminate the adult flies using a non-toxic (_but still not friendly to the flies_) chemical. 

https://www.doyourownpestcontrol.com/drainflies.htm
[![image](https://user-images.githubusercontent.com/194400/85563331-30621180-b625-11ea-8fe1-e590d104587f.png)](https://youtu.be/U4VXeH9pOIs)
Sadly, this video just references a bunch of products that are only available in USA. 🙄 


[![image](https://user-images.githubusercontent.com/194400/85560164-4b7f5200-b622-11ea-95ae-d81010e6006f.png)](https://youtu.be/a8KNC-plXCQ)
https://youtu.be/a8KNC-plXCQ

Apparently baking soda is a potential remedy:  (_is there anything baking soda does **not** resolve?_)
![image](https://user-images.githubusercontent.com/194400/85560395-83869500-b622-11ea-930a-b15a3b6f8466.png)

In case you are wondering, baking soda is just **sodium bicarbonate** https://en.wikipedia.org/wiki/Sodium_bicarbonate 
Chemical formula NaHCO<sub>3</sub>. A salt composed of a sodium cation (Na+) and a bicarbonate anion (HCO<sub>3</sub>−).
[![image](https://user-images.githubusercontent.com/194400/85563732-9058b800-b625-11ea-82f4-147be6888975.png)](https://youtu.be/GXRouroc_ZY?t=88)
https://youtu.be/GXRouroc_ZY?t=88

I'm going to try the following recipe:
+ 100g sodium bicarbonate
+ 100ml white vinegar
+ 20 cloves https://en.wikipedia.org/wiki/Clove heated in the microwave for 10 minutes in 100ml of water
+ 100ml of detergent
Going to put this all in a spray bottle and apply to the adult flies.

Once I have addressed the Adult flies, I will do a full inspection of the drains in the basement to determine their source.
I intend to apply silicone sealant to any cracks around the access box to avoid them resurfacing.
But we need to flush out the decaying organic matter so the larvae don't have any food. 
Going to pour bicarb down _all_ the drains in the house. I count 15 drains. 🙄

**Comment by nelsonic** [comment]
Leroy does not appear to have any relevant products: https://www.leroymerlin.pt/pesquisa/mosca 🔍 
Just going with the "natural" remedy for now and will report back as to its' efficacy. ⏳

**Comment by nelsonic** [comment]
The recipe above appears to work. (fewer adult flies in the area than yesterday)
But the bicarb does not fully dissolve so it does not work in a spray bottle.
Going to re-mix a new batch without the bicarb in the _bottle_ and see if the spray works.
Will still use bicarb powder + vinegar in all the drains as that appears to help dissolve any organic matter.

https://www.thespruce.com/freshen-and-unclog-drain-with-baking-soda-1900466
![image](https://user-images.githubusercontent.com/194400/85682386-280ce380-b6c4-11ea-9a64-fe853126828d.png)

**Comment by nelsonic** [comment]
We’ve been away from @home (visiting family) for a week.
Sadly, the *natural* remedy has not deterred the flies. 🤦‍♂️
(Or I haven’t applied it sufficiently to all the areas where they are breeding... 🤷🏼‍♂️)

![A3B8A11B-A1CE-43D3-B459-4D358D32B6CA](https://user-images.githubusercontent.com/194400/87286483-d43a3100-c4f0-11ea-905c-a64efb45a257.jpeg)

I’ve just spent 45mins *vacuuming* all the flies and I think I got 99% of the ones I could *see*. It’s a _huge_ waste of my time and I really just want to *solve* it.

# Todo:

+ [ ] Do further research into what (preferably non-toxic) chemicals will kill both the adults but *crucially* the larvae.

**Comment by iteles** [comment]
I’m going to do some research now and see if we can find a way to resolve this problem once and for all! Will go out and buy whatever we need this afternoon as I’ll already be out. 
Thank you so much for taking care of the immediate problem (you’re right, it’s a huge waste of your time and shouldn’t happen again) ❤️

**Comment by nelsonic** [comment]
@iteles thanks for taking this tedious task on. 👍 
It shouldn't take priority over "work work", but it's something that we _need_ to do 
because it's costing time 🔥  each day and is generally _annoying_. 🤦

**Comment by iteles** [comment]
I've done some research and turned up much the same things you have above. 

A lot of the resources mention cleaning and drying around drains thoroughly and "removing slime" but our drains and pipes are brand new and pretty clean! 

However, there may be multiple breeding sources as they don't stop once they've found one breeding ground. 
I believe there's a possibility that the drain flies _may_ be coming from under the slab in the basement bathroom floor, as I mentioned to you before, I'm concerned that there might be a cracked pipe under there, as mentioned here:
https://www.doyourownpestcontrol.com/drainflies.htm
![image](https://user-images.githubusercontent.com/4185328/87312931-2727de80-c519-11ea-9017-83c228ed690a.png)

So here are the next steps I propose:

+ [ ] 1. I will go to one of the big supermarkets today and buy some strong drain cleaner
+ [ ] 2. I will pour warm water down the drains, followed by the drain cleaner - both sinks and showers
+ [ ] 3. I'm going to put masking tape around the tile on the floor (pipe cover) that _may_ be problematic to temporarily 'seal' it 
+ [ ] 4. Tomorrow, I'll check the masking tape and if there are any drain flies stuck to it, we'll know it's also a source there
  + [ ] If this is the case, we'll need to lift the slab and check for cracked pipes
  + [ ] If there _is_ a crack in the pipe causing the issue, this is a totally different kettle of fish and we'll get the plumbers in
  + [ ] If there isn't (and it's just a case of lack of usage of the pipes):
      + [ ]  The whole area will need to be cleaned and dried - depending on the situation we find if we have to lift up the tile, it may be worth getting pest control to deal with it. The key is to clean it and get rid of the larvae and then dry everything thoroughly. 
      + [ ] We'll speak to the plumbers to better understand the usage of the pipes so that we can prevent it from happening again :+1:


It's also possible that

**Comment by nelsonic** [comment]
@iteles please LMK if you want/need my help with any of the next steps. (_keen to make progress on this today_) 👍

**Comment by nelsonic** [comment]
https://www.rotorooter.com/plumbing-videos/sinks/how-to-get-rid-of-drain-flies/
![image](https://user-images.githubusercontent.com/194400/87531198-45145100-c689-11ea-90d8-cab41cc426cd.png)

**Comment by iteles** [comment]
Yep. Bought more bleach today so I propose we do the bottom two floors today and the top one first thing when we get up in the morning!

**Comment by nelsonic** [comment]
The bleach worked well. But sadly, it needs to be continued. 😞 
Might go buy more tomorrow after work. 💭

**Comment by nelsonic** [comment]
Mercifully the treatment we applied and fixing the drain got rid of these super-annoying bugs and haven't seen them again.
Closing. ✅
