### ISSUE TITLE
Communal area lights should only switch on when needed (dawn, dusk, nights and dark days)

### ISSUE THREAD

**Issue by iteles** [dwyl/home#137]
Over the course of the last few months I've realised that I find it extremely annoying when on a bright summer's day, the corridor and communal area lights (e.g kitchen and dining room) lights switch on automatically when they make absolutely no difference to the lighting conditions because it's already so bright.

It's not so much that it's a waste (because they're all LEDs) but it _feels_ wasteful and the switching on and off of lights constantly is completely unnecessary.

Yes, we could increase the timers on the lights (we will have to regulate them all anyway) but this isn't a solution to the problem. On bright summer days or intense daylight hours, the lights should only switch on when they are actually needed, not when they are irrelevant.

## Tasks
+ [ ] Investigate timers that can be fitted to electrical boards
+ [ ] Investigate timers that can be fitted to motion sensors (without looking insanely ugly)
+ [ ] Investigate how these could be governed by light sensors
+ [ ] Investigate other possible solutions to this problem
