### ISSUE TITLE
BUG: Cleaning Solar Panels

### ISSUE THREAD

**Issue by nelsonic** [dwyl/home#138]
Today after finishing the stairs #136 I went upstairs to the roof to do a quick inspection.
I noted that all our solar panels are covered in dust:

![solar-panels-filthy](https://user-images.githubusercontent.com/194400/90315611-a80d3800-df14-11ea-8428-2883c7338bec.jpg)

Dust/dirt and pollution on the solar cells can cause a **`25%`** decrease in solar panel efficiency.
https://www.popularmechanics.com/science/energy/news/a27112/pollution-can-block-25-percent-of-solar-power
Some articles I read say the drop in output can be as high as 60%, but let's keep this conservative for now.

We have **`10kW`** of panels and let's go with **4 hours** of sunshine per day. 
If we are losing **`25%`** per day it's **`10kWh`** which at our current cost of **`€0.1544/kWh`** is **`€1.54/day`**. 
Multiplied by 30 days it's **`€46.20`**. 

Note: we are not _really_ "losing" this much money each day, and our recent electricity bill https://github.com/dwyl/home/issues/70#issuecomment-670210331 is not this much. But if we are going to be _using_ our Air Conditioning or Heating, we need to ensure that we are getting the _most_ out of our _considerable_ investment into solar. 

## Proposed Solution

I propose that as part of the garden water points (water well installation) we install a water pipe up to the roof 
Then we can ***either*** have a **timed irrigation system**  that sprays water on each panel once per day
***or*** invest in a Pressure Washer that can be used once a month to deep-clean all the panels.

e.g: https://www.leroymerlin.pt/Produtos/Jardim/Maquinas-de-jardim/Lavadoras-de-alta-pressao/WPR_REF_19299700
![image](https://user-images.githubusercontent.com/194400/90317537-3a680880-df22-11ea-838e-e97052d325d8.png)

## Water Source

When the Water Well people add the pipes and taps to the garden, we need them to add one to the roof.

> The water line only needs to be a basic hose pipe, it doesn't need to be anything fancy.

## Priority?

The _reason_ I've applied the **`bug`** and **`priority-2`** labels to this issue is because the inefficiency of the panels is costing us money each day. So the sooner we resolve it the sooner we **stop _wasting_ money**.
On an annualised basis the lost power due to dust is _considerably_ more than installing a pipe and either of the proposed solutions.

## Dependencies?

Given that we have blocked the finishing of the water well until the green room is done #14,
we should prioritise that ASAP and get Carlos/Pedro to come and at least build the foundation.
Once the foundation for the green room is done, we can finish the water well and the garden. 

# Todo

+ [ ] _Contact_ the Solar Panel Suppliers to ask what they recommend for keeping the panels clean.
+ [ ] Speak to Carlos about the Green Room
+ [ ] Speak to Water Well people about installing a pipe to the roof as part of the garden water points.
+ [ ] Decide which method of cleaning we are going to adopt

**Comment by nelsonic** [comment]
Last night it rained lightly here so I just went up to the roof to check what effect a bit of rain has on the panels. 🔍 
![several-solar-panels-after-rain-still-dirty](https://user-images.githubusercontent.com/194400/90383637-4f56b000-e078-11ea-9003-19e2a5b3cb2e.jpeg)

The cells are less dusty as the rain has cleaned them off a bit:
![solar-cell-after-rain-still-dirty](https://user-images.githubusercontent.com/194400/90383647-5251a080-e078-11ea-8f64-6f88e9a9a15c.jpeg)

But they aren't what anyone would describe as "clean" so we are still losing power. 


@iteles given that you want to turn on the heat pump today to start using hot water, 🥶 
do you think it could be worth trying to see if the hose pipe can reach the roof from the kitchen? 💭

**Comment by iteles** [comment]
We can try! 

I'm not convinced that just a hose pipe without the pressure washer will make much difference but I don't want to _buy_ the pressure washer until DAPE have confirmed care instructions.

I have emailed them to confirm.
