### ISSUE TITLE
Smart Energy Monitor Research

### ISSUE THREAD

**Issue by nelsonic** [dwyl/home#144]
We have a few devices in the building that use considerable amounts of Electricity.
At present we only have rough monitoring in the form of our Solax inverter. 
We need to track energy consumption for both individual appliances and the whole building in real time.

# Requirements

+ [ ] Each monitoring unit should transmit energy usage data to a central hub as close to real-time as possible.
+ [ ] Data should be captured/aggregated centrally (_on our local network_) 
+ [ ] We should not need to send data to Amazon, Google, etc. [wikipedia.org/Surveillance_capitalism](https://en.wikipedia.org/wiki/Surveillance_capitalism) or [state-controlled tech companies](https://www.bloomberg.com/news/articles/2020-06-24/pentagon-names-20-chinese-firms-it-says-are-military-controlled).  So any product with Alexa or Google integration should be deprioritised unless the device can be flashed with new open source firmware.
+ [ ] Ideally the **hardware _and_ software** should be **Open Source**. 
  > As much as we like polished closed source products, we are very happy to have comparatively "rough" Open Source products/software provided they are accurate.

# Todo

+ [ ] Research available Smart Measuring Transmitting Units (MTU)
  + [ ] Plugs: https://www.amazon.co.uk/s?k=energy+monitor+plug 
  > Amazon is our _starting_ point for research because it has reasonably reliable reviews. 
  But if we don't find what we are looking for, we should immediately expand the search.
  + [ ] Whole House mains monitor
  e.g: https://www.amazon.co.uk/KKmoon-80V-260V-Voltmeter-Multimeter-Transformer/dp/B07CLZ72L5
  ![image](https://user-images.githubusercontent.com/194400/92589853-1bdffd80-f293-11ea-9a24-8a8e98c324d6.png)
  > Note: this is just an example for reference, it's cheap and has good reviews. We can buy a closed source device as a reference for data accuracy, but we want to avoid using anything closed/proprietary in the long run.
+ [ ] Make notes of the available products.
+ [ ] Find out if anyone in the https://www.home-assistant.io community has figured out how to flash existing devices and integrate them into their smart home. Ask questions if you need to: https://iot.stackexchange.com/questions/tagged/home-assistant
+ [ ] Decide which units to buy so we can test them.
+ [ ] Is there anything here we can use: https://github.com/openenergymonitor + https://openenergymonitor.org
+ [ ] Is there a limit to how many devices we can collect data from? (_there shouldn't be_)

@th0mas would you mind taking this on as a mini-project? (_please/thanks!_)
Please share product links + screenshots as comments below.
Once you have shared your thoughts on what we need to buy, we will order everything to your address so you can set everything up and get all data streaming. Ideally we will use something like Home Assistant on a RPi, but if you find something better, please share!

Potentially relevant reading: 
+ [ ] Open source low-cost power monitoring system: https://www.sciencedirect.com/science/article/pii/S2468067218300610
  PDF:  [Open-source-low-cost-power-monitoring-system-S2468067218300610.pdf](https://github.com/dwyl/home/files/5198166/Open-source-low-cost-power-monitoring-system-S2468067218300610-main.pdf)
+ [ ] Building An Open Source Energy Monitor: https://www.rs-online.com/designspark/building-an-open-source-energy-monitor

**Comment by th0mas** [comment]
From my initial research there are *two* previously supported options for energy monitoring.

This is still a *niche* use of existing smart home services, with most people using them for automating other parts of there home - e.g. Solar Energy grid export / Timing Electric car charging with [Octopus Agile](https://octopus.energy/agile/).

There only seems to be **one fully open-source solution on the market**, although there are a few open source **software** solutions.

## Prelude

Most of my researched solutions involve using [OpenHAB](https://www.openhab.org/) as the home automation hub, due to its extendability and - as mentioned previously - ability to define custom automation patterns. I'm sure its *possible* to define a plugin for Home Assistant, but there are no community supported ones for this.

OpenHAB is more complex than Home Assistant, but is much more powerful and extendable - lending itself to true home *automation* rather than a virtual lightswitch.

## OpenEnergyMonitor

OpenEnergyMonitor the only fully open source option on the market. Its devices run either on Arduinos or Raspberry Pis come completely setup with the software and peripherals required.

![image](https://user-images.githubusercontent.com/9089056/92706898-c9631780-f34c-11ea-96f4-66072b24c256.png)

The Raspberry Pi based option also works as a base-station meaning no other devices are required to get it to work, and comes complete with an easy to use GUI called EmonCMS:

![GUI](https://guide.openenergymonitor.org/images/applications/home-energy/myelectric_webapp.png)

On top of this, OEM also provides an MQTT broker than any device can subscribe to and receive real-time updates. This means that it can be easily integrated with another smart-home system. An OpenHAB integration is provided and officially supported by OEM so I would suggest we use this.

OEM supports many input sources, and is expandable through its emonTx module that allows for 4 extra inputs.

For device-hub communication, OEM rely's on a non-standard serial radio transmission method that may cause interference with other devices. It would be nice if there was support for a industry standard transmission method such as Zigbee or Z-wave.

## Z-Wave devices.

There are several different Z-Wave devices that can monitor electricity usage, from a complete mains circuit monitor to per-plug monitors. 

Z-Wave is a reasonably plug and play mesh radio standard that is common in IoT and has plenty of support in OpenHAB.

AEON Labs manufacture several Z-Wave devices that can monitor electricity usage. They explicitly state on their website that they support using their Z-Wave devices with other hub systems:

> Like Wi-Fi, Z-Wave is a wireless communication technology. It allows all of Aeotec’s Z-Wave devices to talk to each other, and to other approved Z-Wave devices no matter who has made them. All of that communication happens reliably, without interference, without consuming a lot of power, and it all happens securely.

AEON devices seem popular with the OpenHAB community, as they produce complete engineering guides for their products:

https://www.cd-jackson.com/zwave_device_uploads/375/Home-Energy-Meter-Gen5---Engineering-Spec.pdf

Which means no reverse engineering is required. 

Their [Smart Home Energy Meter Gen5](https://aeotec.com/z-wave-home-energy-measure/) is fully supported by OpenHAB with very detailed documentation:

![image](https://user-images.githubusercontent.com/9089056/92710482-c0c01080-f34f-11ea-9c82-ee50d8d1de6b.png)

https://www.openhab.org/addons/bindings/zwave/thing.html?thingTypeUID=aeon_zw095_00_000

In addition, there are several AC plug Z-Wave monitors that are 'plug and play' for individual appliances. These can integrate with OpenHAB easily and can be used to automate the turning on and off of appliances based off custom rules.

### Z-Wave Devices
+ AOTECH Z-Wave Energy Monitor https://aeotec.com/z-wave-home-energy-measure/
+ Devolo metering plug https://www.devolo.co.uk/devolo-home-control-smart-metering-plug

------

I'm happy to do some more research on this - but I may not be able to take on this project and complete it in time. I only have a few weeks left before the Uni term restarts and I want to finish the existing Security System project before then once RBAC is complete.

This is a large project due to the amount of variables involved and will take a lot of time. In addition, I'm not an electrician and am in rented accommodation so will not be able to test these devices in my own home.

**Comment by th0mas** [comment]
https://www.youtube.com/watch?v=ah3ezprtgmc

![image](https://user-images.githubusercontent.com/9089056/92734624-9c286080-f370-11ea-976e-5c47486f3123.png)

**Comment by th0mas** [comment]
OpenEnergyMonitor did a kickstarter a few years ago and still seem to be going strong:

https://www.kickstarter.com/projects/openenergymonitor/emonpi-open-hardware-raspberry-pi-based-energy-mon

**Comment by nelsonic** [comment]
@th0mas have you been able to determine if the emonPi Energy Monitor _includes_ a Raspberry Pi?
https://shop.openenergymonitor.com/emonpi-energy-monitor-solar-pv-bundle 
![image](https://user-images.githubusercontent.com/194400/92758686-e1f02380-f386-11ea-9dad-5db9b3ccfcb1.png)

If not it will be quite expensive we then have to purchase and add our own. 💭

**Comment by th0mas** [comment]
> The emonPi is based on a RaspberryPi + emonPi measurement board. The emonPi measurement board is based on an ATmega328p 8-bit microcontroller running Arduino based firmware. The following video gives a good overview of what is inside an emonPi. Note that we currently ship RaspberryPi version 3b+ which has WiFi onboard rather than the older version featured in this video.

https://guide.openenergymonitor.org/technical/emonpi/

**Comment by nelsonic** [comment]
@th0mas thanks for looking into this. Looks like OEM is the way to go. 👍

**Comment by nelsonic** [comment]
Troy Hunt did a good overview of his use of Home Assistant: 
https://www.troyhunt.com/iot-unravelled-part-1-its-a-mess-but-then-theres-home-assistant
via: https://news.ycombinator.com/item?id=25184763

**Comment by nelsonic** [comment]
Why Home Assistant is the FUTURE of Smart Homes:
<img width="1030" alt="image" src="https://github.com/dwyl/home/assets/194400/8d6c56bf-9fe2-4413-aa91-57c9d299aef8">

https://youtu.be/hMlkzt-2qgk
