### ISSUE TITLE
Research Geothermal Heat Pump

### ISSUE THREAD

**Issue by nelsonic** [dwyl/home#145]
Can we use a Geothermal Heat Pump to cool/heat the Sunroom #14 making it useable year-round without a ridiculous energy bill?

# Relevant reading

+ https://en.wikipedia.org/wiki/Geothermal_heat_pump
+ https://www.nationalgeographic.com/environment/great-energy-challenge/2013/10-myths-about-geothermal-heating-and-cooling/

# Todo

+ [ ] Research Geothermal Heat Pumps
+ [ ] What ground work needs to be laid in order to setup the system _before_ the building is built?
+ [ ] Can we use the water rushing through from the Well to water-cool the pipes and thus rooms?
+ [ ] Search for "bomba de calor geotermica"
  + [ ] potential product: https://www.daikin.pt/pt_pt/product-group/daikin-altherma-hpc.html
  + [ ] English Site: https://www.daikin.eu/en_us/product-group/daikin-altherma-hpc.html
+ [ ] How much would the system cost (_up-front_) 
  + [ ] Extra digging 
  + [ ] Piping/ducting
  + [ ] Machines
+ [ ] What are the on-going costs (_maintenance, energy consumption, etc._)
+ [ ] Can we calculate the energy/cost efficiency up-front?
+ [ ] Is there a supplier in PT that can help us with this without charging us a fortune?
+ [ ] If _not_, what are our other options for heating/cooling the outside building?

**Comment by nelsonic** [comment]
https://www.leroymerlin.pt/produtos/aquecimento-e-climatizacao/aquecimento-de-agua/bombas-de-calor/bomba-de-calor-aqs-chao-bosch-cs5001-dw-260-85852595.html
![image](https://user-images.githubusercontent.com/194400/234015926-74789663-515c-4ef6-9597-8072fb86f17c.png)

Need to investigate what type of pipes we need to lay in the ground to connect to this heat pump. 🔍

**Comment by nelsonic** [comment]
In PT: https://www.daikin.pt/pt_pt/product-group/ground-source-heat-pump.html

**Comment by nelsonic** [comment]
Good basic overview of the tech: "Heat Pumps: the Future of Home Heating": https://youtu.be/7J52mDjZzto
<img width="907" alt="image" src="https://user-images.githubusercontent.com/194400/234024816-347bcfdf-432c-4bfc-8d75-a97658868137.png">

This is quite a good comparison of the various options:
https://www.gudenergy.pt/bombas-de-calor-de-geotermia/
![Screenshot 2023-04-24 at 15-17-05 A MELHOR MANEIRA DE EXTRAIR O CALOR GRATUITO DA TERRA](https://user-images.githubusercontent.com/194400/234024266-a0d55614-209b-4f09-9e88-5cd397949f93.png)

We will be using the horizontal type: 
![image](https://user-images.githubusercontent.com/194400/234025808-76f41fa2-3382-447a-aae9-1e40a9793950.png)
