### ISSUE TITLE
EPIC Attic Storage System

### ISSUE THREAD

**Issue by nelsonic** [dwyl/home#147]
All along we have planed to use the Attic @home as storage to declutter the lower floors.
The storage room is roughly 10m<sup>2</sup> (floor area) but it's triangular and the roof is sloped,
so it's difficult to find ready-made shelving suitable to maximising the available space:

![braga-attic-storage-empty](https://user-images.githubusercontent.com/194400/94016355-e7496700-fda5-11ea-8497-779c5ec0f0e8.jpg)

I want to build a wall-to-wall shelving system that is compatible with IKEA **`KALLAX`**
so that we have a range of options for storage boxes.

https://www.ikea.com/pt/en/search/products/?q=kallax
![image](https://user-images.githubusercontent.com/194400/94015608-04316a80-fda5-11ea-9780-000a21d37994.png)

There are a few options for storage boxes starting at **`€3/each`**
![image](https://user-images.githubusercontent.com/194400/94015656-11e6f000-fda5-11ea-97a3-287e5cc6bfe1.png)

**`DRÖNA`** **33x38x33 cm** storage boxes come in a range of colors:
https://www.ikea.com/pt/en/search/products/?q=DR%C3%96NA
![image](https://user-images.githubusercontent.com/194400/94015833-49559c80-fda5-11ea-9cc2-434d2d02da31.png)

> **Note**: ignore the smaller (25x35x25cm €2.50) version as it's only relevant for a different system.

I think it would be quite nice to use the colors as part of our organisation _system_. (TBD)
I wouldn't suggest multiple colors of boxes if the system was on constant display, 
but given that it's hidden in the attic and we want to _find_ things fast I think it makes sense. 💭 

The **`TJENA`** storage boxes with lids **`€5.50`** are a good option for things that are dust-sensitive.
https://www.ikea.com/pt/en/p/tjena-storage-box-with-lid-white-40469302
![image](https://user-images.githubusercontent.com/194400/94016887-a00fa600-fda6-11ea-8811-59b3811ae12e.png)

I plan to Laser Cut Kallax compatible _lockable_ storage boxes in the future for downstairs and have created a prototype in Fusion360: https://github.com/nelsonic/learn-cad-cam-cnc/issues/12
Need to convert it to Blender or FreeCAD because of https://github.com/nelsonic/learn-cad-cam-cnc/issues/32 

# Todo

+ [ ] **Re-measure** the attic space and determine how many 3x3 shelving units we need. 
  > Provisionally I've calculated **7 units** at ground level; **63 `DRÖNA`** Boxes!
+ [ ] **Design** the **3x3 shelving unit** to be cut out of **`15mm` Plywood** (_more than strong enough_)
  > Each 3x3 unit will be roughly **`107x107cm`** 
+ [ ] Buy/Order Materials
+ [ ] Laser Cut the shelving units
+ [ ] Assemble/Install
+ [ ] Buy (_or make_) storage boxes.
+ [ ] Organise all the things!

I don't have time to work on this today as I have code to write,
but I had a bunch of windows open on my computer related to this and wanted to close them.

@iteles if you can determine the priority for this issue, we can try and work on it together soon. 👍

**Comment by iteles** [comment]
I would suggest this should be our highest priority in terms of house _build_.
It will allow us to work out so many kinks in design and laser cutting workflow in the next week already!

I also think that now we have all our moving boxes here, the storage will make a big dent in improving mental clutter and this can't be underestimated 👍 

As soon as we're back from Lisbon, we should make a start on this.

**Comment by iteles** [comment]
@nelsonic I'm going to have to go to Ikea tomorrow morning, shall I buy 2 of these `DRONA` boxes to try out/have as moulds? Or more?

I favour the dark grey ones as they don't show the dirt like white ones do and they're less intense than the black ones which I actually think show _dust_ a lot more than the dark grey ones:

https://www.ikea.com/pt/en/p/droena-box-dark-grey-10443974/
![image](https://user-images.githubusercontent.com/4185328/95001152-299d5000-05bf-11eb-89d2-f52acf2381bc.png)

**Comment by nelsonic** [comment]
@iteles yeah the dark grey or beige ones are the best for our purposes in the attic. 
If you think we don't have any in our boxes, feel free to buy a few of them. 👍 
We can always build our own storage systems for stationary once we get our CAD->Laser process down. https://github.com/dwyl/learn-cad-cam-cnc/issues/35
