### ISSUE TITLE
General contractor snag list

### ISSUE THREAD

**Issue by iteles** [dwyl/home#149]
There are a number of snags, with most of them (and the 'tidy-up' work) falling to the general contractor.

This is not yet an exhaustive list, but should be added to as we go.

However, I do think that the top few should be considered the highest priority:
+ [ ] Check through the phenolic work done #126
+ [ ] Review and sorting out the wall situation from the air conditioning in the basement #99 
+ [ ] Closing up the walls and priming the doors for the upstairs wardrobe #148 
+ [ ] Lifting the reduced mobility bathroom floor tile to check the situation on psychodidae #125 
+ [ ] Finishing the flooring next to the attic staircase 
+ [ ] Items missing from the plumbing snag list #96 (mostly silicone)
+ [ ] Finding better finishing strips for the meeting of one type of flooring with the laminate flooring
  + These strips are currently most prominent at floor length windows (where 2 are already warping) and where tile flooring meets laminate flooring (both strips in the kitchen are coming off and wonky)
+ [ ] Reinforcing the grouting around the bathroom floors (around the outer walls there are some gaps)
+ [ ] Finishing off the painting of the basement leisure room (needs final coat)
+ [ ] Fixing divot in stairwell wall from where the attic staircase took a chunk out of it on the way up

**Comment by nelsonic** [comment]
@iteles this list is looking good so far only the Phenolic doors issue #126 has a priority label is that intentional? Guessing it is top of the list because you want to tick that off first. (_makes sense, I agree_) 👍 
I've added one item (_the last one_) to the list which isn't really "snagging" so feel free to remove it. But if Carlos could bring his flat-bed truck he could remove all the non-essential materials and tools from the garage and garden #150 which would make a big difference to the "building site" feel of the house and would help me move forward with my plans in the garage |> _workshop_.

**Comment by iteles** [comment]
### Hand dryers
Advice for adding the hand dryers is: pierce the wall at the joins and never near the edge of a tile.

### Flooring at the top of the main stairs
A final strip of laminate was added and we agreed a way forward for this. It's now sitting with the carpenter as the final strip required to 'join' the top step with the laminate will be a darker wood he needs to source

### Basement leisure room
Mostly completed, needs a final coat of paint

### Remove all non-essential building rubble
He said he'd come back Saturday with his pick-up truck to do this

**Comment by nelsonic** [comment]
![715F44F2-B6A8-424D-AA5C-9A6B88043C77](https://user-images.githubusercontent.com/194400/173072422-528adc5e-0cfc-4aa9-99d4-08d7d2a46620.jpeg)

luckily the place where this drywall is used is extremely unlikely to get any moisture. And it’s the “hydrofogado” type so it will somewhat resist moisture… but yeah, he really shouldn’t have used it *outside* … 🙄
