### ISSUE TITLE
Utility Room > Washing Machine Shelf/Structure

### ISSUE THREAD

**Issue by nelsonic** [dwyl/home#151]
Our plan is to stack our two clothes washing machines on top of each other to save space.
At present there is no shelf for stacking the machines but this is where it will go:

![washing-machine-dryer](https://user-images.githubusercontent.com/194400/95180293-b1e74500-07b9-11eb-89af-979bb8f0e203.jpg)

# Todo

+ [x] **Measure** the dimensions of the shelf
+ [x] **Design** the shelf sturdy enough to support the weight of the machine with a full load and forces/vibrations 
+ [x] **Prepare cutting list**
+ [x] Go to **hardware/wood store** with cutting list and get everything cut
  + [x] Buy acoustic insulation material to absorb/dampen the sound of the machine:
  https://www.leroymerlin.pt/Produtos/Construcao/Isolamento/Isolamento-acustico
  + [x] Buy **`2m`** washing machine hose
+ [x] Bring pieces home
+ [x] **Cut joints**
+ [x] **Assemble** (wood glue + pneumatic nail gun)
  + [x] Add anti vibration foam 
+ [x] **Install**

I expect this to take me the best part of a day and will be doing it _today_ so that Carlos #149 can help us to lift the machine into place (_it's very heavy!_)

Related to: https://github.com/dwyl/home/issues/124 Washing Machine Installation

**Comment by nelsonic** [comment]
@iteles I'm heading out to Leroy Merlin now. Do you need anything from the shops? 💡

**Comment by nelsonic** [comment]
Went to Leroy Merlin (our local hardware and home/construction supplies store) with cutting list:
![utility-shelf-leroy-cutting](https://user-images.githubusercontent.com/194400/95248394-26000800-080f-11eb-8677-f0aad235c23f.jpeg)

All pieces cut for _free_ using a high precision saw:
![utility-shelf-leroy-all-pieces-cut](https://user-images.githubusercontent.com/194400/95248469-3e702280-080f-11eb-99a2-c5c458124125.jpeg)

This is what the shelf/structure looks like without anything:
![utility-washing-machine-stack-empty](https://user-images.githubusercontent.com/194400/95248519-4e880200-080f-11eb-8463-65cd7c95de3f.jpeg)

I had to cut a hole for the electrical cable and water source:
![utility-shelf-with-hole-cut-for-cables](https://user-images.githubusercontent.com/194400/95248559-63fd2c00-080f-11eb-9edc-a81d6219622c.jpeg)

Added an anti-vibration mat:
![Shelf-with-antivibration-mat](https://user-images.githubusercontent.com/194400/95248589-6f505780-080f-11eb-96d9-02a1e9e1f5d4.jpeg)

It's a "friction fit" without any screws or wall fixings, I made it snug so it doesn't move.

With the machine on top:
![utility-shelf-with-machine-on-top](https://user-images.githubusercontent.com/194400/95248707-9b6bd880-080f-11eb-9468-d0a5cf4a535b.jpeg)

**Comment by iteles** [comment]
It's perfect, thank you!!!
