### ISSUE TITLE
Wood cover for the piping in upstairs built-in wardrobe 

### ISSUE THREAD

**Issue by iteles** [dwyl/home#152]
As per https://github.com/dwyl/home/issues/148#issuecomment-704816372 we need to add a piece of wood to cover the piping in the upstairs built-in wardrobe.

_Ideally_ this would be removable should we ever need to get into the electrical wiring but the likelihood of needing to do so is _extremely low_.

## Tasks
+ [ ] **Measure** the dimensions of the space that needs to be covered (taking **uneven walls** into account)
+ [ ] **Design** any simple mechanism required to ensure it stays in place/could have shelves added to it and it would be a good supporting wall for this 
+ [ ] **Prepare cutting list**
+ [ ] Go to **hardware/wood store** with cutting list and get everything cut
+ [ ] Bring pieces home
+ [ ] **Cut joints**
+ [ ] **Assemble**
+ [ ] **Install**

**Comment by nelsonic** [comment]
made an `MVP` of this a couple of years ago now ... ⏳ 
was one of my first `Laser` projects! ⚡ 
@iteles want to give feedback on it's suitability and/or suggest improvements?

**Comment by iteles** [comment]
Still working. When tested with actual people who don't care about it, I'm sure it'll be put through its paces properly.

**Comment by nelsonic** [comment]
Thanks for confirming. 👌
