### ISSUE TITLE
Utility Room Laundry Products Shelf

### ISSUE THREAD

**Issue by nelsonic** [dwyl/home#153]
Yesterday I completed a 1-day build of the Washing machine stacking shelf #151 (_the wood you can see below_)
Today my plan is to create a second box that fits on top of the current one so that we have a place to store all the laundry-related products (detergents, stain removers, etc).

![utility-shelf-with-machine-on-top](https://user-images.githubusercontent.com/194400/95313240-d1e53a00-0887-11eb-9edf-ce5f9bb1d3db.jpeg)

# Todo

+ [x] Measure the space available
+ [x] Draw Sketch of box
+ [x] Prepare cutting list to fit single sheet of 8 x 4 15mm Ply Wood
+ [ ] Go to Leroy, Get plywood cut, Load Pieces and return to @home
+ [ ] Assemble
+ [ ] Install!

Given my experience of building the shelf yesterday #151 I think I can get this done in 4h (_including 90mins of round trip to Leroy_) and around 1h of assembly @home. So I'm going to get this one done _today_. ⏳ 👷‍♂️

**Comment by nelsonic** [comment]
Cutting list:

![utility-room-cutting-list-inkscape](https://user-images.githubusercontent.com/194400/95323075-77eb7100-0895-11eb-8594-99c10f162213.png)

PDF for printing: [utility-room-shelf-cutting-list.pdf](https://github.com/dwyl/home/files/5340108/utility-room-shelf-cutting-list.pdf)

**Comment by nelsonic** [comment]
Done: ✅ 
![1A3DCEC6-B73F-4D9C-AA75-F295C8554ADD](https://user-images.githubusercontent.com/194400/95357407-bbf36b80-08bf-11eb-8e0c-21930f084b21.jpeg)

**Comment by nelsonic** [comment]
In use:
![5370C993-9300-4DB8-A424-59BAFB1536D6](https://user-images.githubusercontent.com/194400/95357817-3e7c2b00-08c0-11eb-8542-0c3bf2c0908a.jpeg)

**Comment by iteles** [comment]
All of our inherited detergent stock 😂😅
