### ISSUE TITLE
Sheet Material Cart

### ISSUE THREAD

**Issue by nelsonic** [dwyl/home#156]
At present we don't have anywhere to store our sheet materials in the workshop, so they are stored on the floor. 
This isn't great for humidity and keeping the sheet material _flat_. So we need to design and build a wheeled materials cart:

There are a few articles with plans and videos: https://www.google.com/search?q=sheet+material+cart
![image](https://user-images.githubusercontent.com/194400/95505637-9c833e00-09a6-11eb-82d8-2c2c13f7496d.png)

e.g: Rolling Lumber Rack: https://youtu.be/TbLNh486eeA
[![image](https://user-images.githubusercontent.com/194400/95506311-a5284400-09a7-11eb-82d4-9e27493dc562.png)](https://youtu.be/TbLNh486eeA)

Our needs are quite specific:
+ [ ] Store 20+ full sheets of 8x4" sheet materials in "landscape" (_as our ceiling is not high enough for vertical_)
  + If we buy 20 sheets (_the minimum quantity_) from our plywood supplier #123 and each sheet is **`15mm`** thick it's **`30cm`**
+ [ ] Store any "spare" random-size pieces on the reverse side of the cart.
+ [ ] Store 2 in. x 4 in. x 8 ft. studs 

# Todo

+ [ ] Design the Cart in CAD
+ [ ] Prepare cutting list
+ [ ] Get pieces cut at Leroy
  + [ ] Select and buy heavy duty locking casters (x6) 
    + [ ] Research: https://www.leroymerlin.pt/Produtos/Ferragens/Ferragens-para-moveis/Rodas
+ [ ] Get pieces _delivered_ by Leroy https://www.leroymerlin.pt/pt/entrega-ao-domicilio
+ [ ] Assemble

I expect I can design and build this in 2 days; 1 day for design/CAD and cutting list prep, then 1 for assembly.

**Comment by nelsonic** [comment]
https://www.inchcalculator.com/how-much-does-plywood-weigh
![image](https://user-images.githubusercontent.com/194400/95509723-c5a6cd00-09ac-11eb-8798-74c20451310e.png)

Each sheet of 15mm plywood weighs **`53 lb`** == **`24 kg`** so 20 sheets will weigh (20 x 24=) **`480kg`**.
The frame will probably weigh around **`60kg`** as it's made of 2x4"s and 1 sheet of **MDF**. 
I expect the "spare" pieces of wood to weigh around **`100kg`**
So the total weight of the (_loaded_) cart will be around **`600kg`**. 

We could buy 6 casters rated for **`100kg`** each, and it would be "OK", 
_however_ I'm thinking of getting 6 casters rated for ***`200kg`*** each so we have _double_ the load capacity 
so that if for any reason _two_ of the castors were to fail, the other 4 can still cope with the **`600kg`**.

**Comment by nelsonic** [comment]
Polyurethane (_non-marking_) **D125MM 200KG** casters. Locking: €30 x 4
https://www.leroymerlin.pt/Produtos/Ferragens/Ferragens-para-moveis/Rodas/WPR_REF_13609715
![image](https://user-images.githubusercontent.com/194400/95511170-030c5a00-09af-11eb-8663-0cdcbec612e1.png)

Non-locking €20 x 2
https://www.leroymerlin.pt/Produtos/Ferragens/Ferragens-para-moveis/Rodas/WPR_REF_13609701
![image](https://user-images.githubusercontent.com/194400/95511210-11f30c80-09af-11eb-82e5-a42270ddcf71.png)
