### ISSUE TITLE
Electrical taps not mixing hot and cold water correctly

### ISSUE THREAD

**Issue by iteles** [dwyl/home#157]
We are currently having a fun issue whereby none of our electrical taps (including showers) are mixing the the water correctly, so in order to get hot water coming from the taps, we have to switch off the cold water to them entirely and have hot water _only_.

***This is clearly an installation/configuration issue.***

The problem being that the plumbers who installed the taps are not experts in these more complex sensor based taps and as such, are taking a _long_ time to liaise with their suppliers to understand how to fix the issue.

## Tasks
+ [ ] Understand why hot water is not coming from the taps even though the boiler is working perfectly
+ [ ] Plumbers to come by and try something they've been advised to try on one tap so that the installation issue can be diagnosed
+ [ ] Sanilanhoso/Delabie experts to come and fix the issue
