### ISSUE TITLE
Circulation of hot water 

### ISSUE THREAD

**Issue by iteles** [dwyl/home#158]
The small motor that is supposed to circulate the hot water around `home` has now had a plug added to it by our electricians but when switched on, it doesn't do anything 🤦‍♀️ 

## Tasks for getting this fixed
+ [ ] Confirm that the electrical connections are all working as expected
+ [ ] Plumbers (who installed the system) to come and see if they can diagnose the issue
+ [ ] Speak to suppliers to understand who can review the issue
+ [ ] Fix!

**Comment by iteles** [comment]
Water re-circ motor was taken to be fixed, brought back and re-installed but we didn't notice any change in the hot water getting to the top floor so I have to get back in touch with them to let them know the problem isn't solved. Doing this now.
