### ISSUE TITLE
Laundry/linen room

### ISSUE THREAD

**Issue by iteles** [dwyl/home#162]
In the laundry/utility room, we have some clear space which we 'reclaimed' from a stairwell that had a particularly high ceiling.

I need to take a photo but it's to the right of this area: https://github.com/dwyl/home/issues/153#issuecomment-705039544

This are will be perfect for storing:
+ Everyday and quick access linens
+ Laundry products #159 
+ Cleaning products
+ I would also like this to be a bulk hygiene product storage so people could buy/get bulk products from us (shampoo, laundry detergent, soap) in whatever size they need whilst they're here to minimise both packaging and waste

As such, we need to measure the space and figure out what the ideal shelving system is because the ceiling is high and the shelf area is deep making it harder to access.

## Tasks
+ [ ] Take full measurements of the space
+ [ ] Design a possible shelving area which will fit the products described above
+ [ ] Design solutions to facilitate access
+ [ ] Create cutting list
+ [ ] Get materials cut
+ [ ] Sand to size
+ [ ] Assemble

**Comment by nelsonic** [comment]
@iteles thanks for opening this issue to capture the work that needs to be done. 👍 
Did you order the heavy duty drawer runners we looked at on eBay yesterday? 💸 
We need them (or at least their tech spec) before we can design the drawers. 📝 
But we can build the structure/shell with the upper shelves while waiting for delivery. ⏳

**Comment by iteles** [comment]
When discussing how to get to deep shelves, we discussed having shelves that roll out like drawers, to provide access to the contents. 
We have about 950mm of usable space infront of this shelving unit but there's no need for the whole thing to pull out, just enough for the back half of the shelf to be totally accessible.

Note: I'm calling these shelves because we don't want to have full sides on them as this will hamper accessibility for the taller shelves. But the will have a front to keep extra dust from finding its way in, a back to keep things from falling into the abyss and 30cm side panels at the back for the same reason.

We decided on these in the 700mm size:
https://www.ebay.co.uk/itm/141382827424?var=441265499685&ssPageName=STRK%3AMEBIDX%3AIT&fromMakeTrack=true
![image](https://user-images.githubusercontent.com/4185328/99567013-87e28e80-29c5-11eb-989c-3f7298fb7a1c.png)

Ordered 3 sets for delivery:
![image](https://user-images.githubusercontent.com/4185328/99572763-0db60800-29cd-11eb-82e3-a7d1a9271c95.png)

**Comment by nelsonic** [comment]
@iteles thanks for placing the order. ✅
