### ISSUE TITLE
Ficus Pumila - Covering the Exterior Walls in Green 🏡 

### ISSUE THREAD

**Issue by nelsonic** [dwyl/home#176]
Ever since we embarked on the @home project it's been our ambition to _cover_ the house in plants. https://github.com/dwyl/home/issues/8

![image](https://user-images.githubusercontent.com/194400/113523285-d1abca00-959e-11eb-81cd-e505c23527ed.png)

This is Ivy:
![image](https://user-images.githubusercontent.com/194400/113523647-e5f0c680-95a0-11eb-8e59-8226ce2652e3.png)
It looks _great_ but requires a lot of maintenance to keep it looking this good. 
The _major_ downside of Ivy is that gives a very "thick" cover which _can_ encourage pests like rats and snakes. 🐍 
The vine we are planning plant is quite tight against the wall so there's _less_ chance of pests. 
Luckily, we've never seen a rat/mouse @home outdoor. 

https://carminereddarter.wordpress.com/2015/08/11/my-favourite-buildings-in-london-the-house-overgrown-by-ivy-in-de-beauvoir-hackney

![image](https://user-images.githubusercontent.com/194400/113523744-a37bb980-95a1-11eb-8f30-e6f56eec3704.png)

After much research (online and IRL) we _stumbled_ upon **`Ficus pumila`** https://en.wikipedia.org/wiki/Ficus_pumila
While walking at **Conservatório Bomfim** http://conservatorio.bomfim.org/fotografias/#!
![image](https://user-images.githubusercontent.com/194400/113523523-d3c25880-959f-11eb-923b-b4243ef14307.png)

> **Side Note**: Braga has 4 highly rated music schools/conservatories. [google.com/search?q=braga+escola+musica](https://www.google.com/search?q=braga+escola+de+musica) 🎶 

The panorama of the wall really does not do it justice. It's 80+ meters of green wall and looks _amazing_!

![image](https://user-images.githubusercontent.com/194400/113523046-74634900-959d-11eb-8efb-c9d2620526b3.png)

The wall is north-west facing and it has only partial sunlight for around 2 hours per day. 

![image](https://user-images.githubusercontent.com/194400/113523053-804f0b00-959d-11eb-9dac-178af0d91577.png)

This close-up photo allowed us to use Google Lens to lookup:

![image](https://user-images.githubusercontent.com/194400/113523059-893fdc80-959d-11eb-840b-f321cad5cb21.png)

![image](https://user-images.githubusercontent.com/194400/113528541-c6659800-95b8-11eb-936b-958a8b7b445a.png)

The density of the foliage is excellent and it's **`evergreen`**, new leaves grow while the old ones are still on the vine.
Which means there are multiple colors of leaves at several times of the year. 
https://en.wikipedia.org/wiki/Ficus_pumila#/media/File:Ficus_pumila.jpg
![image](https://user-images.githubusercontent.com/194400/113523899-e25e3f00-95a2-11eb-9088-20637202595d.png)
![image](https://user-images.githubusercontent.com/194400/113524283-ad072080-95a5-11eb-9694-1a600ec2f778.png)

The most mature leaves are the darkest green:
https://en.wikipedia.org/wiki/Ficus_pumila#/media/File:Feuilles_de_Ficus_pumila.jpg
![image](https://user-images.githubusercontent.com/194400/113524093-4f260900-95a4-11eb-9f91-9d29506f17db.png)

The fruits are edible: http://www.eattheweeds.com/climbing-fig-creeping-fig they are used in Taiwanese cuisine.
![image](https://user-images.githubusercontent.com/194400/113524139-a4fab100-95a4-11eb-92fd-c3aeb6e23029.png)

Not that _we_ are growing the plants for their fruit; just we wouldn't grow them if the fruits were toxic to humans or animals.

![image](https://user-images.githubusercontent.com/194400/113524276-9e206e00-95a5-11eb-9951-945c066fa6b3.png)

This house has it's own wikipedia page: https://en.wikipedia.org/wiki/Warren_Wilson_Beach_House `#LifeGoals` 😉 
![image](https://user-images.githubusercontent.com/194400/113523814-24d34c00-95a2-11eb-95f9-533b5511356b.png)

### Additional Reading

There is conflicting info on how tall the plants grow. Some places say **4m**, but there is plenty of evidence of taller. 
We need ours to grow **7m** while maintaining decent coverage. 

+ https://www.rhs.org.uk/Plants/7210/Ficus-pumila/Details
+ https://www.uaex.edu/yard-garden/resource-library/plant-database/vines/creeping-fig.aspx
+ https://davesgarden.com/guides/pf/showimage/16737/

## Considerations

+ [ ] We need to plant one seedling every 1 - 1.5 meters to ensure consistent coverage. 
  + on the north wall, I think it makes sense to space the plants closer as we need them to grow to 7m tall and given that it less sunlight

[![image](https://user-images.githubusercontent.com/194400/113526264-4f78d100-95b1-11eb-9721-145573d8d508.png)](https://youtu.be/-Deool54Bqg)

## Todo

+ [ ] **Visit** **Conservatório Bomfim** and ask them who their gardener/groundskeeper is.
  + [ ] **Ask** if we can _buy_ (or just take) a few clippings of their plants. 
  + In total we need **100 clippings**. 🌱 
    + **52m** (25 + 15 + 12)  of exterior fence to cover. (the remaining **25m** will be Kiwi vine)
    + **50m** (15 + 10 + 15 + 10) of main building 
  > If we can get 10 clippings we could get the _West_ wall started and then take clippings of our own plants next year. 💭

**Comment by nelsonic** [comment]
Today on our evening walk we visited the Conservatório Bomfim (music school) and Inês talked to the caretaker. He kindly gave us these clippings:
![79B862F4-12CD-4D30-B05D-FA2905E43D55](https://user-images.githubusercontent.com/194400/113757763-e5743f00-970a-11eb-8b43-6fb503f75af8.jpeg)

![97D64E84-F807-4BBC-BC6A-9DA20C0FE0C4](https://user-images.githubusercontent.com/194400/113744361-8f989a80-96fc-11eb-83ac-4ef5cd104ac8.jpeg)

Following the instructions I found online for clipping propagation: https://www.gardenguides.com/101322-propagate-ficus-plant.html

![2EAB355C-A9B0-44DF-86A8-59D0EB7343A3](https://user-images.githubusercontent.com/194400/113758529-e78acd80-970b-11eb-82d3-30b28d3fa5a9.jpeg)

going to do the work now so they don’t dry out. 🌱

**Comment by nelsonic** [comment]
Placed 20 prepared cuttings into glass jars filled with filtered water. (Only 10 shown in this photo, we have another tray of 10 on the next windowsill):
![C323E01A-E970-4BFD-8802-FC9DDF1CC6AF](https://user-images.githubusercontent.com/194400/113774600-66d5cc80-971f-11eb-9847-3d230b4fe3e5.jpeg)

*really* hope this works. 🤞🌱

**Comment by nelsonic** [comment]
Good news! It’s been 5 weeks since we put the clippings in water and most of them have sprouted roots! 🌱

![40F640C0-345A-4650-B64D-859854F5A4DC](https://user-images.githubusercontent.com/194400/118394646-c63bcc00-b63d-11eb-8400-fe73a37701e4.jpeg)
![F1506C84-7519-45D2-8855-C7ED33050F25](https://user-images.githubusercontent.com/194400/118394658-d05dca80-b63d-11eb-88ad-ab478820125a.jpeg)

so I went to Leroy Merlin this morning and bought some small (15cm diameter) pots to transplant them into soil:

![57A04AED-2AD9-41B8-BEAB-241594178794](https://user-images.githubusercontent.com/194400/118394698-22065500-b63e-11eb-98df-5bad756562ee.jpeg)
![8FF4A4BD-226D-48BC-BA3C-DBB6C3EF9743](https://user-images.githubusercontent.com/194400/118394705-2a5e9000-b63e-11eb-8e65-66820e2e89f8.jpeg)

Going to do the potting of the seedlings this afternoon with A. Will continue to house them in our mini-greenhouse to keep them warm. But I will be using rain water (that I collected this week when it was *pouring*) to irrigate them as I think our tap water isn’t great for plants. 🤔

**Comment by nelsonic** [comment]
Transplanted the 16 cuttings with the best looking roots: 

![597DF18A-046C-41D2-AC35-602029CE5FE8](https://user-images.githubusercontent.com/194400/119410415-bdec2c80-bce0-11eb-9282-09cdfa920da3.jpeg)
![FF6CED2C-78DE-462C-A702-516C62E1D162](https://user-images.githubusercontent.com/194400/119410421-bf1d5980-bce0-11eb-9a9e-4b53db9a33d0.jpeg)
![7390B805-67CB-47DE-857C-5C075D888CC0](https://user-images.githubusercontent.com/194400/119410425-bfb5f000-bce0-11eb-8bea-b8135c72dda8.jpeg)
![ED471FA3-72AF-4224-A0A0-89060F48E953](https://user-images.githubusercontent.com/194400/119410427-bfb5f000-bce0-11eb-8c7d-287d428904c3.jpeg)
![880A2752-8CE1-4F8E-9122-9FCF96665DFD](https://user-images.githubusercontent.com/194400/119410432-c0e71d00-bce0-11eb-9ef1-2baccba3ff85.jpeg)

**Comment by nelsonic** [comment]
@iteles I've been spraying the leaves with tap water each morning to keep them hydrated.
I haven't added any NPK/nutrients to the water or soil; do you think we should add?

**Comment by iteles** [comment]
I think that it would be great to add some nutrients - give them the best start possible in life!
Will have to do some research on the most appropriate ones though :)

**Comment by nelsonic** [comment]
@iteles thinking of using worm tea from the composter diluted 1:10 with water. (not on the leaves, just add to the soil)

**Comment by iteles** [comment]
Worm tea sounds... 😂 🐛 Lovely!
But yes, great idea.

**Comment by nelsonic** [comment]
@iteles misting the leaves to keep them hydrated until the roots are established to draw enough moisture from the soil: 
![IMG_7302](https://user-images.githubusercontent.com/194400/120205103-7bb37580-c221-11eb-8b4e-473503548b75.jpg)

**Comment by nelsonic** [comment]
One of the things to have in mind when embarking on this kind of adventure 
is how we are going to _maintain_ the vine once it grows enough to cover the walls ...
_Specifically_ we need to avoid it growing above the roofline and onto the Solar Panels #20 ... these vines can _easily_ grow to cover the house and if not kept in check will become a nuisance!

![image](https://user-images.githubusercontent.com/194400/120208404-588ac500-c225-11eb-899c-a381c1cbc6a6.png)


A quick search for a telescopic pruner returned the "Fiskars UP86":
https://loja.jardinitis.com/fiskars-universal-vara-telescopica-varios-tamanhos-bfee7/?otcountry=PT&sku=F1023625

![fiskars-up86-vara-telescopica](https://user-images.githubusercontent.com/194400/120205747-3a6f9580-c222-11eb-98ff-c003cf5050f1.png)

> No point looking for this on the Leroy website, they only have the **4m** model. We want the longest possible one.
If we can find an 8m one we would get that instead of 6m. 


Fiskars UP86 Tree Pruner Revisited (long-term review): 
[![image](https://user-images.githubusercontent.com/194400/120206358-06e13b00-c223-11eb-8ca4-c5c59d9d1eac.png)](https://youtu.be/31BIWLPHkwg)
most of the down-votes are from people complaining about the sound ... 🙄  the content is decent.
One of the video comments is a question is about the **cutting diameter**: it's **32mm**.

> @iteles this means we could use it to trim the tree branches of the street trees that are dropping all the leaves/seeds into our yard ... given that the council isn't going to do it ... 🙄 

Usefully it appears to be easy to maintain the mechanism; the internal rope that operates the pruner is changeable 
and there is a replacement part kit: https://youtu.be/Pj2nUka0SaU
[![image](https://user-images.githubusercontent.com/194400/120207500-6db32400-c224-11eb-9485-ffd1ae15ce52.png)](https://youtu.be/Pj2nUka0SaU)
The blades are also sharpen-able / replaceable.

## _When_? ⏳ 

We don't _need_ to buy this for the next couple of years while the vines are establishing themselves.
We want to _train_ them with wire around the house (above head height) but not _prune_ them until they are mature. 

I'm just capturing this mini research so it's clear we have thought about how to _maintain_ the vines. 💭 

More detail: https://hgic.clemson.edu/factsheet/climbing-fig/

**Comment by nelsonic** [comment]
@iteles yesterday you mentioned that that you had read that **`Ficus Pulmia`** was "Toxic" ... 💭 
Would you mind sharing a link to where you read it so that I can dig a bit deeper? 

Sadly, I get the feeling this is Facebook-fuelled misinformation. 🤷‍♂️ 

http://www.eattheweeds.com/climbing-fig-creeping-fig/ (_shared in the OP above ... sharing again_)
![image](https://user-images.githubusercontent.com/194400/144326607-85406a6a-f475-4635-a40b-8c4ca94b21f5.png)


The **FDA** list of Poisonous that some non-experts refer to:
https://www.cfsanappsexternal.fda.gov/scripts/Plantox/Detail.CFM?ID=18120

![image](https://user-images.githubusercontent.com/194400/144320042-5fa4aead-476b-4eb5-bc55-f7b0edd24e70.png)

Does _not_  include **`Ficus Pulmia`**:

<img width="1170" alt="fda-website-toxic-plants-ficus-search" src="https://user-images.githubusercontent.com/194400/144318172-3f02cc4f-d0c3-4729-882d-122aa682b7cf.png">

The California Poison Control System: https://calpoison.org/topics/plant#nontoxic-common
![image](https://user-images.githubusercontent.com/194400/144320289-68584d20-4a9a-4f34-ab63-b97bd86f49b7.png)

**`Ficus Pulmia`** is listed in the **Non-toxic plants** by it's _common_ name "**Creeping fig**":
![image](https://user-images.githubusercontent.com/194400/144320479-9d7309f4-14b2-466a-8d7a-49027926939f.png)

North Carolina State University has this page with detailed info: https://plants.ces.ncsu.edu/plants/ficus-pumila/
![image](https://user-images.githubusercontent.com/194400/144321809-c45f1b95-8917-4a2e-90e7-5b835f8ad68a.png)

If you search the page for "***toxic***" (_or variants of the word_) you will find zero hits:
<img width="1441" alt="ficus-pulmia-edible" src="https://user-images.githubusercontent.com/194400/144322252-02c38079-3857-48be-87a8-9c8c2aefa6ba.png">

Similarly Clemson.edu College of Agriculture, Forestry and Life Sciences has a very informative **Factsheet**:
https://hgic.clemson.edu/factsheet/climbing-fig/
![image](https://user-images.githubusercontent.com/194400/144322762-5bc0eca2-6453-4c80-91e0-f94d0e75ce07.png)

The University of Florida Institute of Food and Agricultural Sciences has the following Fact Sheet:
https://hort.ifas.ufl.edu/database/documents/pdf/shrub_fact_sheets/ficpuma.pdf
![image](https://user-images.githubusercontent.com/194400/144323089-3b984953-b9fd-4909-a159-a47b54e8e66a.png)

Again, no mention of toxicity/poisonous. 

It references: https://www.cabi.org/isc
The "CABI" (Commonwealth Agricultural Bureaux International) Invasive Species Compendium
Which has a specific page for **Ficus pumila** (creeping fig): https://www.cabi.org/isc/datasheet/24162
![image](https://user-images.githubusercontent.com/194400/144323721-f60d2975-5a29-45fa-89cd-d65f8a710155.png)

"_In China, Taiwan, and Japan, it is commercially cultivated to make jellies from the fruit_"
![image](https://user-images.githubusercontent.com/194400/144323863-d6e7f7e3-f571-48f6-a42c-2381f9b2c32f.png)

In the Risk of Introductions section: https://www.cabi.org/isc/datasheet/24162#tosummaryOfInvasiveness
It says: "_is poisonous to mammals_" ... 
![image](https://user-images.githubusercontent.com/194400/144324065-b5761c5a-74aa-4ce7-a5d8-5c04b1b36cbb.png)
References:
Wiersema JH; León B, 1999. World Economic Plants: A Standard Reference. Boca Raton, Florida, USA: CRC Press, 749 pp.

Couldn't find a PDF of the book available online, but Google Books allows searching in the book:
https://books.google.pt/books?id=gZlWfNTm-boC&printsec=frontcover#v=onepage&q=ficus%20pulmia&f=false

The book basically a compendium of 10k+ plants with _tiny_ amount of info for each one. 
It says "**Poison (mammals)**" ... no other info. 🤷‍♂️ 

<img width="1274" alt="book-highlight-ficus-pulmia" src="https://user-images.githubusercontent.com/194400/144325327-1539ea8d-e576-4004-92cb-5d919491a4ff.png">

_Which_ "mammals"...?! 🤷‍♂️ 
If the fruit is eaten in several Asian countries, how is it "poisonous" ...?

**Comment by iteles** [comment]
> Sadly, I get the feeling this is Facebook-fuelled misinformation.

🙄 🙄 🙄 🙄 🙄  It's like you've never met me. Or like you think I've never met *you*. 🙄 

This is where I first saw it when I was looking at possibly buying some plants:
https://viveirosvl.com/produto/ficus-pumila-white-sunny/
![image](https://user-images.githubusercontent.com/4185328/144518523-64e5bb40-1ee4-4780-835d-069ca96a6d2e.png)

Then also see below:

https://hortology.co.uk/collections/trailing-hanging-plants/products/ficus-pumila-white-sunny-creeping-fig
![image](https://user-images.githubusercontent.com/4185328/144518844-acd1dac4-1e77-42c0-8135-71a944b379e2.png)

https://www.trees.com/house-plants/creeping-fig
![image](https://user-images.githubusercontent.com/4185328/144518879-4da10495-6a10-4000-97e3-58e995a85d40.png)

https://www.houseplantsexpert.com/growing-a-creeping-fig-indoors.html
![image](https://user-images.githubusercontent.com/4185328/144519138-e61eee4b-bc73-4008-90b9-f063a882560a.png)

I think we can safely conclude it's not _fatal_ but can be an irritant.

**Comment by tuxkernel** [comment]
Im attaching some pictures of my backyard. _Ficus pumila_ is the best choice for covering the wall. 

![IMG_20211108_101652](https://github.com/dwyl/home/assets/785911/642436ff-5afd-46fe-8700-3c7aac4192f2)
![IMG_20211108_101706](https://github.com/dwyl/home/assets/785911/f0d087bd-e15f-49c9-a5f3-ba1bd41e85d0)
![IMG_20211108_101807](https://github.com/dwyl/home/assets/785911/52ca8c67-86d4-401d-b46d-53e46e5011dc)
![IMG_20211108_101841](https://github.com/dwyl/home/assets/785911/0de751ab-5d53-4b6f-a702-ced8912928f3)

Some info about cares, benefits, myths and truths (spanish):

[ficus-pumila.pdf](https://github.com/dwyl/home/files/11551974/ficus-pumila.pdf) (letterpaper)
[ficus-pumila-2secciones.pdf](https://github.com/dwyl/home/files/11551990/ficus-pumila-2secciones.pdf) (signatures, letterpaper, 2 sections)

**Comment by nelsonic** [comment]
@tuxkernel this is _incredible_!! 😍 
How long did this take to grow? ⏳ 💭

**Comment by tuxkernel** [comment]
@nelsonic two years to grow. But with cares you can reduce the time. If you need additional info, don't forget ask me. Happy growing! ;-)

**Comment by nelsonic** [comment]
Sadly, the chap I asked to *water*  the already established Focus Plants took it upon himself to add a fertiliser to the plant 🌱...

![image](https://github.com/dwyl/home/assets/194400/b673b1e9-a325-44a8-8025-e90d9f14d2d1)

Again I had **not _asked_** him to do it, he did it *thinking* he was *helping*... And this is was the effect. Killed a perfectly healthy plant. 😭

This has made me *very* sad. 😭

**Comment by nelsonic** [comment]
# July 2023 Update! 

Our most well-established `Ficus Pulmia` plant is on the pillar below the main staircase:
<img width="582" alt="image" src="https://github.com/dwyl/home/assets/194400/b284155b-2f1f-4457-82c5-2e02cc1719ff">
It only gets 2-3 hours of sunlight per day but is already around `1m` tall and strongly attached to the wall. 

A month ago when we visited `Landim` I took around 30 clippings from various `Ficus` vines. 
I placed them in plastic bottles with water and 

<img width="916" alt="image" src="https://github.com/dwyl/home/assets/194400/cb847952-5027-4eaa-8b11-d423bedf33a2">

Our son is keen on plants & gardening. So when I told him we were going to transplanting he was excited!

We took a bowl and went to the construction gravel bag (Brita 1) to grab some gravel:
<img width="676" alt="image" src="https://github.com/dwyl/home/assets/194400/50d3e8e2-19b2-484c-8997-1fcf94868817">

Put a little bit of gravel into each of the 8 plant pots: 
<img width="667" alt="image" src="https://github.com/dwyl/home/assets/194400/bdc8ce4d-31b3-439b-8123-6d344edd1568">

Then got some soil ("Terra Preta") from the pile and put crumbled in into the pots:

<img width="645" alt="image" src="https://github.com/dwyl/home/assets/194400/ecb17d4f-2216-4fcf-bff1-2437b774b4fa">

Next we got some potting/germination compost and put a little in each pot: 
<img width="659" alt="image" src="https://github.com/dwyl/home/assets/194400/535d3d03-b79b-46cb-b739-9b3adf7ba507">

Selected the 8 clippings with the most well-established roots:
<img width="655" alt="image" src="https://github.com/dwyl/home/assets/194400/e6729e09-06e0-4782-be1b-931fd049ca80">

<img width="667" alt="image" src="https://github.com/dwyl/home/assets/194400/0738b373-dd9a-48ed-83e7-851b56f509fe">

Once we had transplanted 8 together we packed in the root section into the nutrient rich compost: 
<img width="585" alt="image" src="https://github.com/dwyl/home/assets/194400/a62aa0c4-6f00-41d7-95e9-a09052d15fe5">

Once the compost + roots was gently compacted, watered them: 
<img width="1140" alt="image" src="https://github.com/dwyl/home/assets/194400/a1b907c0-c006-4141-9258-b3591cf99b33">

The pots are placed in the trays on top of the wall where they can get good sunlight but not all day only around 2-3h/day:

<img width="1200" alt="image" src="https://github.com/dwyl/home/assets/194400/300f324a-e8d4-4291-82b9-2b236f07b43f">


The tray holding the pots allows us to water them generously: 
<img width="1181" alt="image" src="https://github.com/dwyl/home/assets/194400/2e65ea0f-cab3-4a39-ad05-a496e041383b">

And the water in the tray is pulled up by the plants by capillary action. 

Added a teaspoon of rooting agent to each plant, but far from the stem:
<img width="1194" alt="image" src="https://github.com/dwyl/home/assets/194400/faf42ba1-5376-4677-87b4-9d66ef3d7384">

When I gave them a final water the rooting agent filtered into the soil and will encourage the plants to establish.

Transferred the remaining cuttings into glass bottles with fresh water and rooting agent: 
<img width="961" alt="image" src="https://github.com/dwyl/home/assets/194400/222b0fe3-adfa-4941-89e0-8c9c0e16f667">

@iteles we need to axsk `DT` to water the plants `while` we're in Gerês next week. 🙏 

As for the remaining clippings, none of them have sufficient roots for transplanting, _yet_... 🌱 ⌛ 
The glass bottles with tapered necks reduce evaporation so they should be fine for a couple of weeks without us. 👌 
When we get back from Gerês, we will buy new pots for transplanting and prepare the next batch of 8. 👩‍🌾

**Comment by iteles** [comment]
Hooray! This looks like a fun morning too ❤️ 
I'll ask for the watering to be done 👍

**Comment by nelsonic** [comment]
The advantage of the trays is that `DT`/`Miguel` can can _visually_ see if the plants are "dry" and need watering. 🚰

**Comment by nelsonic** [comment]
Today we removed the protective “cage” from our second strongest plant l:

![IMG_1722](https://github.com/dwyl/home/assets/194400/b9b04c2b-2641-47f1-8bbe-45c5ca95665a)
![IMG_1723](https://github.com/dwyl/home/assets/194400/ba6ff0da-2d2c-4203-8ee6-11827b69d0ad)
![IMG_1740](https://github.com/dwyl/home/assets/194400/b9aa8b50-d6d3-426d-9dad-973f0e2fbca9)

I installed a support wire to allow the vine to grow against the wall:

![IMG_1741](https://github.com/dwyl/home/assets/194400/92809e25-03e7-4e43-b9ed-aac1374225d5)
![IMG_1742](https://github.com/dwyl/home/assets/194400/4493df02-a2e8-4ab1-9731-c80308a4a94c)

watered it generously - as there hasn’t been rain the past week - and considering adding some NPK tomorrow to stimulate growth. 🌱

**Comment by nelsonic** [comment]
According to: https://greg.app/creeping-fig-fertilizer/ (dunno if that link will last...) ![image](https://github.com/dwyl/home/assets/194400/8a650daf-8461-4579-8c2f-3f39bdaa5305)

We need a balanced NPK fertiliser to stimulate growth. Going to collect some 10:10:10 from Leroy on my next visit. 👨‍🌾🤞🏼

Also need to buy 3 Passion Fruit vines to plant. 🌱

**Comment by nelsonic** [comment]
This is the 3rd well-established ficus vine that had a protective plastic fence around it for the past couple of years:

![image](https://github.com/dwyl/home/assets/194400/a3b1cc70-d0ab-4597-bb44-eedfe328a516)

I removed the green plastic protection around it and added a white mesh to the stair banister vertical bars. The mesh serves as child protection as the gap between the vertical bars is too wide for child safety - the house was built *long* before those regulations existed!! - but it will double as a trellis for the ficus vine:

![image](https://github.com/dwyl/home/assets/194400/9b041356-dae0-44f3-a5f8-2b0510a058da)

The vine is now trained to grow on the trellis and I have watered it generously with the organic NPK mix. 🌱👌

**Comment by nelsonic** [comment]
My plan tomorrow is to plant out 7 more of the cuttings that are well-established in pots on the wall:
![image](https://github.com/dwyl/home/assets/194400/7b97448a-44ba-4e50-bc57-5d952976d61c)

![image](https://github.com/dwyl/home/assets/194400/600088e0-1964-4b2b-818a-8ab714453408)

I've planned where they will go. 
Just need to prep the support wires and _temporary_ green plastic protection mesh. ⏳
Super keen to get this done ASAP so the new cuttings can establish like the existing ones. 🤞🏼

**Comment by nelsonic** [comment]
Today @davcdj kindly cleaned the glass bottles we use for the Ficus clippings: 

![IMG_0451](https://github.com/user-attachments/assets/41a286f0-e6dc-4d2f-8f9b-783ba27022d0)

So this weekend (prob Saturday morning) we will prepare 24 clippings. 🌱 2️⃣4️⃣ 🪴

**Comment by nelsonic** [comment]
Sadly, having clean jars in the kitchen - that I had carefully collected for the seedlings - was seen as an invitation to _use_ them, and also sadly, two were broken! 😞 

So I only had 10 jars for the seedlings:

![IMG_2200](https://github.com/user-attachments/assets/5994505c-835e-432a-825d-0f26b699e774)

I added a table spoon of root growth powder and the same in NPK (plant food) to test if the seedlings grow roots faster on this experiment:

![IMG_2199](https://github.com/user-attachments/assets/76100298-d592-43e7-b460-b4d73c4e7c92)

![IMG_2201](https://github.com/user-attachments/assets/06c52e8e-68c9-4d2f-b27a-ebeccd163fda)

Took all the clippings from our own plants around the house for the first time:

![IMG_2207](https://github.com/user-attachments/assets/7a12f394-e6ae-4c8d-a4bc-162c00c3ce41)
![IMG_2204](https://github.com/user-attachments/assets/c20de8e4-0d2f-46b1-934d-3598e37cbe39)
![IMG_2208](https://github.com/user-attachments/assets/7fc97f52-966b-4123-a25c-f120fca65c61)

Prepared them by removing the bottom leaves off the clippings and stuck them in the jars with water:

![IMG_2210](https://github.com/user-attachments/assets/6fb513da-ac89-40bf-affa-6a35eafb4872)

hope these take root. 🌱🤞🏼

Meanwhile the other 10 that are in pots are more than ready to plant out! 😍

![IMG_2202](https://github.com/user-attachments/assets/e5aa2aff-0770-466e-8d61-416c53ed0e43)
![IMG_2203](https://github.com/user-attachments/assets/149c5418-9745-48f2-bfb5-8986d8ece320)

Very impressed with the growth of the plant under the stairs:

![IMG_2205](https://github.com/user-attachments/assets/fa2e3afb-39ab-4879-b46d-c60220be4eba)

It gets barely any sunlight and is very healthy and vigorous!
Gives me a lot of hope for the places I’m going to be planing others in the south garden. 🪴🤞🏼

**Comment by nelsonic** [comment]
The Ficus Pulmia plants we have already planted out continue to flourish. 🎉
This morning I took another 16 clippings off our vines:

![Image](https://github.com/user-attachments/assets/7066f654-d860-478a-a14d-2875aaacfdf7)
![Image](https://github.com/user-attachments/assets/5ae45e01-96e0-45d8-8402-eaad762a3dfc)
![Image](https://github.com/user-attachments/assets/3d87778b-dbeb-4c2f-a79a-f10dc9c782cf)
![Image](https://github.com/user-attachments/assets/206ad90e-ee19-4e81-ba6f-e7db3e2af04d)
![Image](https://github.com/user-attachments/assets/ae20fc04-1f6f-4304-883b-a3d2a4edfa2c)
![Image](https://github.com/user-attachments/assets/420fe235-11a6-457d-a64b-a7db138d5339)

They are in the mini (€20) greenhouse to form roots. 🌱
I put a quarter teaspoon of rooting hormone in each jar but zero nutrients (NPK); just rain/well water. 💧 
Let’s see how well this batch works. 

(The previous batch all died, I suspect because of the NPK which burned the roots… 😢)

**Comment by nelsonic** [comment]
Today was an _especially_ [hot day](https://github.com/dwyl/phase-three/issues/139) so I went to check on the ficus clippings in the mini greenhouse around noon. 🕛 

Half of them were dried out beyond saving! 😢

![Image](https://github.com/user-attachments/assets/bbc31d8b-0e43-4c7d-b4a1-1422df4e9a8c)

Scorched by the heat! ☀️ 🥵 
Definitely didn’t help that they were in a greenhouse that intensified the heat! 🔥🤦‍♂️

So I moved them to under the rear stairs on top of the Xodiac (pool heat pump):

![Image](https://github.com/user-attachments/assets/47ad6215-9f62-4c34-9c6f-cde6642b25eb)

I took fresh clippings to replace the scorched ones and put them in the jars which still had enough water in them.
The water hadn’t evaporated; just the leaves cooked in the sun! 😢

Going to fill a spray bottle and follow the leaf misting technique described above to keep them hydrated. 💦

Makes me sad to “kill” plants, 😢
but it’s all a learning process. 💭
And thankfully our 3 key vines are doing well enough that I can still take clippings from them. 👌

No more direct sunlight for the clippings. ⛅️

**Comment by nelsonic** [comment]
**_Three_ weeks later** and the spot in the shade under the stairs that gets indirect light has worked an absolute charm:

![Image](https://github.com/user-attachments/assets/46d0cfb4-4c90-4935-924d-5911bb9f6949)

All the clippings have decent roots, here’s an example:

![Image](https://github.com/user-attachments/assets/09623763-bf23-42d1-8c6e-13dcf252a953)

These can _already_ be transplanted to soil. 🌱
But I’m leaving them in water for another week to develop a bit more. ⏳🤞🏼

So the formula for successful Ficus Pulmia propagation appears to be:

1. Clip off all leaves below the waterline to avoid algae which suffocates the root growth.
2. indirect light or even shade which promotes rooting and deprioritises photosynthesis while minimising algae growth.
3. a quarter teaspoon of rooting hormone per jar and zero NPK (nutrients).

It’s taken several iterations to figure this out. But I feel like we’ve cracked it and can scale up production! 👌

**Comment by nelsonic** [comment]
Meanwhile one of the vines was killed by the pool people changing the water pipes from company water to well (filtered rain) water, you can just see the marks on the wall where it was successfully sticking to and growing in this photo:

![Image](https://github.com/user-attachments/assets/639b5f3b-b5bb-4e1e-a2e1-8ba0771b7b2b)

I carefully filled the hole with compost & soil and replanted a new (2-year old well-rooted) clipping:

![Image](https://github.com/user-attachments/assets/6ffb6ab4-5b08-4afb-8902-8caa4c66f6db)

Cut out the decking around the protective plastic “fence” which prevents further damage, both from careless adults and curious children:

![Image](https://github.com/user-attachments/assets/47502b23-b443-415b-b6be-e854b6c8f936)

I’m a _lot_ more confident in the survival chances of this vine as it has protection, plenty of fertile soil & organic fertiliser. 

Just gotta keep watering it throughout the summer months. 💦 

My goal for this vine is that it completely covers the front garden wall (west-side). 🤞🏼

![Image](https://github.com/user-attachments/assets/a0182bde-669f-4051-8ae9-e43804fa5154)

Just gotta be patient. ⏳



# “_My garden is my most beautiful masterpiece._" ~ Claude Monet

**Comment by nelsonic** [comment]
Also managed to get the next well-developed clipping planted next to the (future) green wall at the base of Ping Pong Palace:

![Image](https://github.com/user-attachments/assets/69dffd4d-0629-469f-8b6d-f8fe4ad1a000)
![Image](https://github.com/user-attachments/assets/a6f3dfab-91d9-4a4d-92a6-5f9db149de24)

David had kindly prepared the area.

So I just had to drill holes for the protective fence, put in the plugs and screw everything in:

![Image](https://github.com/user-attachments/assets/b2232f2c-2a0d-4ca2-8de0-1bd5bbd8006e)

Planted it and added plenty of adubo Azul (NPK) around the area, then covered with compost & terra leets:

![Image](https://github.com/user-attachments/assets/c3873c33-c740-4859-9c65-0f4784305f33)
![Image](https://github.com/user-attachments/assets/487d5140-072a-4aeb-8c15-8796497bd99c)

Again, I’m a _lot_ more confident this one will survive as its conditions are optimal. Just needs water 💦 and the occasional NPK top-up. 👌

**Comment by nelsonic** [comment]
This morning I decided to transfer the **16** best-rooted clippings to pots filled with compost & soil:

![Image](https://github.com/user-attachments/assets/5b7ea9e2-c195-498e-8b1c-966fd542b813)
![Image](https://github.com/user-attachments/assets/2be6032d-2266-4ff5-bc30-f11ef17ddf7f)
![Image](https://github.com/user-attachments/assets/139f67c1-22dc-4734-91c9-de6544b28ba2)

Each pot plant has a good amount of potting (germination) compost and the roots are gently compacted. On top of the compost there is a table spoon of Adubo Azul (NPK) which will dissolve gradually as the plants are watered. 💦

The remaining clippings will stay in the water-filled glass jars to continue rooting.

**Comment by nelsonic** [comment]
Given the success of the latest approach to clipping rooting in water, I’ve scaled up to 20 jars and 3 clippings per jar: 🫙 🌱

![Image](https://github.com/user-attachments/assets/91ad284b-3ca7-4731-9aae-c47251ea0371)
![Image](https://github.com/user-attachments/assets/cb6ae023-0831-4eb4-924f-fea333ee36cb)
![Image](https://github.com/user-attachments/assets/abcf6a01-69a4-4fb3-9769-8a0ece0a353f)

Will check back again to ensure they have enough water in the jars on a weekly basis. 👩‍🌾
Now it’s just a patience/waiting game. ⏳🤞🏼

As per my/the goal above, I want 100 of these plants all over the exterior of the house & walls. 
So need to scale. 📈

**Comment by nelsonic** [comment]
Very happy with the progress of the vine in the front (west) garden: 😍

![Image](https://github.com/user-attachments/assets/6b9eb3ed-cc45-40a2-88b1-b2ff657ecbdb)

Many of the branches are successfully adhering to the wall and climbing. 🧗 

I took 10 clippings from this vine this morning to tidy it up and get more plants. 🌱🤞🏼
