### ISSUE TITLE
Unpack, Tune and Setup the Piano

### ISSUE THREAD

**Issue by nelsonic** [dwyl/home#177]
### Context 

A family friend was downsizing and no longer had space for an upright piano. 🎹 
Rather than go through the hassle of trying to sell it and arrange shipping to the buyer - and knowing that we were furnishing our house - they offered it to us if we took care of transport. It arrived recently and has been sitting in the "storage" room wrapped on a pallet. 

Feels like a waste to have a piano in the house and _not_ use it. 💭 

## Todo

+ [ ] 1. **Discuss/agree** where the Piano will "live" (*even if just temporarily*). 
  + [ ] Should be free from moisture and direct sunlight to avoid damaging the structure and surface.
    > South-east corner of the leisure room?

+ [ ] 2 **Move** the Piano to where we want it to live 
+ [ ] 3. **Unpack** it in-situ

+ [ ] 4. **Organise** for **Tuner** to visit: https://www.google.com/search?q=afinador+de+pianos+a+domicilio 
e.g: https://www.salaomozart.com/footer/assistencia Guideline price: **€90**
https://www.custojusto.pt/porto/emprego-servicos/servicos/outros-servicos/afinador-de-pianos-4396301 
![image](https://user-images.githubusercontent.com/194400/117583186-a36d5d00-b0fd-11eb-8159-b468c38b2ffe.png)

+ [ ] 5. **Buy** Piano Stool e.g: https://www.salaomozart.com/product/quik-loc-bx-8  €36
or https://www.thomann.de/gb/thomann_kb_247bm.htm (2-person £72)
![image](https://user-images.githubusercontent.com/194400/117583316-7b322e00-b0fe-11eb-940d-6a31fe96480e.png)

These 5 tasks can be completed swiftly as soon as we agree on the priority for this.
I'd be quite keen to get it done reasonably "ASAP" so that you can dust off your piano skills and expose `A` to sounds.

@iteles thoughts?

**Comment by iteles** [comment]
Sorry, I’ve only just seen this. It’s not high priority but easy to discuss and do, number 1 is our biggest blocker because the leisure room is currently humid in the winter 🤔

**Comment by nelsonic** [comment]
Progress: we unpacked, cleaned and moved the Piano to its (medium-term) home in the Leisure Room. 🎹  
The Piano Tuner came last week and did a first pass at tuning it: 🔧 
![image](https://user-images.githubusercontent.com/194400/120203505-b1eff580-c21f-11eb-907a-8a855a627bf7.png)

It already sounds _really_ good, but the strings will still need to settle for a few weeks/months (with playing), 🎶 
and we will call the Tuner chap back in September to do a final tune; hopefully that will last a few years. 🤞

**Comment by nelsonic** [comment]
@iteles leaving this issue assigned to you as the final task will be the shop calling you to collect the piano stool. ⏳

**Comment by nelsonic** [comment]
@iteles has already been playing the piano with 👶  and they love it. 🎉 
![image](https://user-images.githubusercontent.com/194400/120204093-55d9a100-c220-11eb-8a18-102308470dc3.png)

**Comment by nelsonic** [comment]
https://www.aosom.pt/item/homcom-banco-de-couro-para-piano-banco-com-arrumac-o-75x35x50-cm~02-0707.html

![853EA921-87DD-4643-BE2F-F1FF675FAEAF](https://user-images.githubusercontent.com/194400/130689849-10b5fec8-5ee3-4040-8f70-56354fb48d88.png)

@iteles thoughts? 💭

**Comment by iteles** [comment]
We're looking for an adjustable height one 💭

Also, we had specifically wanted a matte version because from what we saw in-store, the shiny one didn't look good with the brown piano 🙈

**Comment by nelsonic** [comment]
@iteles yeah I ‘member that we wanted a Matte bench. But if we can’t get one because they are out-of-stock or discontinued, what’s the next best option? 💭

**Comment by nelsonic** [comment]
`priority-3` as "nice-to-have" but not urgent even though I would love to have a proper bench. 
Been using the cheap (€9.99) **IKEA `ADDE`** chair which _works_ but isn't idea because the seat height is **`45cm`** (_non-adjustable_) and it's _definitely_ not the "right" height for playing.

**Comment by iteles** [comment]
I had the perfect matte bench with storage on order from the music shop for 2 years and then they finally told me it wasn't going to be made available again 😭 

Just ordering this one to tick this off:
https://www.aosom.pt/item/homcomr-banco-para-piano-de-tamborete-com-altura-ajustavel-54-5x33x48-58-cm~02-0710.html
<img width="1242" alt="image" src="https://github.com/user-attachments/assets/53a7e516-d4cd-42f5-bde8-d0a5869ccc46">

**Comment by nelsonic** [comment]
Does this sit two people or just one? 2️⃣

**Comment by iteles** [comment]
It's a one person seat.

I don't fancy dropping €250 on this:
https://www.ludimusic.com/bancos-de-piano/banco-de-piano-roland-rpbd500pe-duet-preto-polido
<img width="1292" alt="image" src="https://github.com/user-attachments/assets/6df1cb63-70fa-4c2e-9c70-362b14ecb904">

**Comment by nelsonic** [comment]
@iteles fair enough. perhaps _two_ of the one-person benches side-by-side; one adjusted to _child_ height and the other to _adult_ would be better than a single (more expensive) bench. 💭 
So yes, _one_ to test first makes sense. Thanks. 👌
