### ISSUE TITLE
Library Bookshelf

### ISSUE THREAD

**Issue by nelsonic** [dwyl/home#179]
building a custom full wall book case to store/organise our books.

Standard book sizes: https://www.printondemand-worldwide.com/resources/printondemand-worldwide-book-size-guide/

Book sizes in cm and mm

+ Standard (19.7cm x 13.2cm) (197mm x 132mm) – Our standard book size.
+ Novel (20.3cm x 12.7cm) (203mm x 127mm) – A popular size for trade paperbacks in the UK.
+ A5 (21cm x 14.8cm) (210mm x 148mm) – This size is usually used for novels, notebooks, and pocket books.
+ Demy (21.6cm x 13.8cm) (216mm x 138mm) – The type of fiction you would see in a UK airport tends to be Demy – because it is slightly larger than UK trade books and attracts more attention.
+ US Royal (22.9cm x 15.2cm) (229mm x 152mm) – American trade books come in this bigger size.
+ Royal (23.4cm x 15.6cm) (234mm x 156mm) – Slightly larger than the US trade size and will also suit hardcover books.
+ A4 (29.7cm x 21cm) (297mm x 210mm) – A4 is the standard size used for many magazines and catalogues.
+ Square (21cm) (210mm) – We like this size for full-bleed images when using landscape or portrait formatting.

The full height (floor to ceiling) is **2770** mm.
We need **10cm** ground clearance underneath the bottom shelf so the Roomba #122 can clean under it so that it doesn't become a dust magnet. 

The baseboard is **70mm** so we need **30mm** of material to prop up the bottom shelf if it rests on the baseboard.

2770 - 100 - 335 - 630 = **1705**
1705 / 275 = 6.2 -> **6 shelves**.

Going to make: 
+ 3 shelves 30cm tall for larger books, folders, etc. 
+ 2 shelves 22cm tall for Non-fiction and the occasional intellectually stimulating novel.
+ 6 shelves 226cm tall for all the remaining books (of which 98% of our computer programming books will fit)

Going to draw this out on Ply board so I can get it cut today after work.

**Comment by nelsonic** [comment]
**2835** LED Strip lights are the most modern type:
https://hitlights.com/blogs/premium-led-strip-lighting/numbers-and-leds-what-does-2835-3528-and-5050-mean

**Comment by nelsonic** [comment]
Placed an order for these LEDs:
https://www.lightinthebox.com/en/p/zdm-3m-light-sets-180-leds-2835-smd-1set-mounting-bracket-1-x-12v-2a-adapter-1-x-pir-sensor-warm-white-cold-white-waterproof-new-design-self-adhesive_p6902528.html
![image](https://user-images.githubusercontent.com/194400/126883607-cb17d7f9-ab28-41b8-bf81-9a62ddbc36cd.png)

But not expecting the LEDs to arrive for another couple of weeks ... ⏳ 
<img width="1231" alt="order" src="https://user-images.githubusercontent.com/194400/126883632-c64d930a-82d3-464e-b7b6-808d15406bd1.png">

Luckily, the design for the shelves does not require the LEDs to be here before assembling and mounting the shelves.
I will mount the light strips retrospectively. A bit more work but not the end of the world. 🙄 

Going to visit Leroy Merlin tomorrow (Sunday) afternoon and get the **5 sheets** of **Plywood** cut.
There are 33 pieces to be cut, loaded into the car and brought back home.
Then there are another 44 smaller cuts to be made in our workshop.
This is easily the biggest item of furniture I've built so far in the house. 
I estimate that it will take me the whole week (of evenings) to get it all done. 4 x 4h ... ⏳ 👷 
Verrrrry keen to get it all finished before next weekend. 🤞

**Comment by nelsonic** [comment]
Went to get the Plywood cut at Leroy Merlin yesterday:
![corte-de-madeira](https://user-images.githubusercontent.com/194400/126976511-4efe9ae9-5230-4814-bc39-33f7d6ab57bb.jpg)

I explained to the chap doing the cutting that the cutting lists https://github.com/dwyl/home/tree/master/library _carefully_ maximised each board to minimise waste:

![leroy-cutter-guy](https://user-images.githubusercontent.com/194400/126976519-4c6797dd-64e9-432d-a19c-3f3a554095a2.jpg)

But sadly he did not follow my _precise_ instructions ... So there are quite a few pieces that are ***wrong***.  🤦 

![library-shelves-wood-cut-leory](https://user-images.githubusercontent.com/194400/126976907-547106d0-14ed-4920-95be-f221a3c53651.jpg)

This photo shows the cut pieces loaded in to @carolrmc's car: (_thanks again for lending it to me!_)

![libary-wood-in-car](https://user-images.githubusercontent.com/194400/126977041-27fea494-28de-446b-8fa0-1cadeffb057b.jpg)

That extra large piece on top is just _one_ of the mistakes. It's not in my cutting list/diagrams ... 

Suuuuuuper annoying. Gives me quite a lot more work (a) figuring out what pieces are missing and (b) cutting them myself from full Plywood boards *or* having to go back to the store to get new boards and cuts ... ⏳

**Comment by nelsonic** [comment]
Also, fun fact: The wall where I will be installing the shelves isn't flat/square. 📐 
This is the gap in the between the shelf and the wall at the middle of the shelf:
![wall-gap](https://user-images.githubusercontent.com/194400/126989924-8804a74e-accf-4af8-8f4a-836cdb55736d.png)

This is going to make life _interesting_ ... 🙄 

![mind-the-gap](https://user-images.githubusercontent.com/194400/126990247-71b10439-505f-43d2-bbbc-c122653fda82.png)

**Comment by carolrmc** [comment]
What a palava! Just to add to your headache 🤕

**Comment by nelsonic** [comment]
Yeah, you wouldn't want life to be _easy_ ... 😜 

![image](https://user-images.githubusercontent.com/194400/126991864-195b404d-7947-438b-9571-5a44f5d2c6e5.png)

**Comment by carolrmc** [comment]
🤨

**Comment by nelsonic** [comment]
I side-tracked to build the entrance shoe rack: https://github.com/dwyl/home/issues/181 👞 👟 🥿 
And a bunch of other work-related tasks ... ⏳ 

Going to resume the library shelving ASAP as my next highest priority DIY/Furniture task.

Currently waiting for delivery of a **`15mm`** Groove Cutting Router Bit:
https://www.amazon.co.uk/gp/product/B000XJ0CR4/?th=1
![image](https://user-images.githubusercontent.com/194400/148378877-595ff21c-f420-4faa-a3c3-87f78028d223.png)

I'm going to have to cut 40+ groves and I only have a **`12mm`** bit ...
It's fine to do 2 passes for the other _small_ items of furniture I've built.
But having to do setup for 80+ cuts (_two passes for each groove_) is **_mega_ tedious**.

So patiently waiting for delivery from the ES AMZN which was _cheaper_ than UK:
<img width="1444" alt="amazon-spain-router-bit-purchased" src="https://user-images.githubusercontent.com/194400/148379287-99a594fa-b2cc-4b11-816d-89fd1677fdc8.png">

**Comment by carolrmc** [comment]
Patience is a virtue …

**Comment by iteles** [comment]
Can't wait for this, it'll make such a difference ❤️

**Comment by nelsonic** [comment]
Going to focus on this on Saturday. 🤞

**Comment by iteles** [comment]
Could not be more excited. Totally making time to sit with you and do some of this.

**Comment by nelsonic** [comment]
Yesterday (Saturday) I got off to a **_slow_ start** because I didn't have everything ready... ⏳ 

I had to make _two_ jigs for routing (cutting) the grooves into the shelves;
this is the jig that turns my [Makita RT0700C](https://www.makita.pt/product/rt0700c.html) hand router into groove cutter:

<img width="1065" alt="image" src="https://user-images.githubusercontent.com/194400/153749769-2443c1a8-0a73-477c-a1cd-346e0c4252cb.png">

I have a Bosch plunge router (that I've owned for 10+ years) but the collet is 6mm (the part that grips the router bit) so it does not fit the new bit I bought for this project ... see above: https://github.com/dwyl/home/issues/179#issuecomment-1006520879 ⬆️  hence having to adapt the Makita (which has an 8mm collet) from a palm (detail) router which has a circular base that makes it tricky to cut straight lines ... to now have a flat edge that can track my straight line jig. 

Speaking of straight line jigs, this is the one I made for reliably routing the groves in the shelves:

<img width="1016" alt="image" src="https://user-images.githubusercontent.com/194400/153751093-730230d8-42de-4cf4-89e7-e88082c64ae9.png">

It doesn't look like much, but it dramatically simplifies the groove routing process so I can route each groove in about a minute including measuring, setup and cutting. So I could have all the groves for the shelves done in about 30 mins!

> If you're new to routing in the context of woodworking, see: https://en.wikipedia.org/wiki/Router_(woodworking)
And watch a few YouTube videos to get an even better idea, e.g: https://github.com/dwyl/learn-cad-cam-cnc/issues/42

This is my outdoor work area: (_I work outside because I don't yet have a dust collection system in the workshop ..._)

<img width="909" alt="image" src="https://user-images.githubusercontent.com/194400/153749724-1394e9fa-bc7f-4381-9439-0849f11dc44d.png">

In this picture you can see my mitre saw, table (job site) saw, router table and makeshift [workbench](https://github.com/dwyl/learn-cad-cam-cnc/issues/47). 


I managed to **fully assemble _one_ shelf** yesterday:

<img width="670" alt="image" src="https://user-images.githubusercontent.com/194400/153749966-d9d34bcb-7ea5-4c3b-9cde-67442a18f214.png">

This is what the front of a shelf looks like with the vertical support slotted into the groove:

<img width="948" alt="image" src="https://user-images.githubusercontent.com/194400/153750341-b83fae18-1ffb-415d-9d3d-9ea534de5a2e.png">

And here is a side-view of the end of the shelf showing the concealed French cleat attached to the shelf:

<img width="485" alt="image" src="https://user-images.githubusercontent.com/194400/153750382-fc3ae8b1-b0b8-491e-861d-6370629904ef.png">


Here's a shot of one of the supports from under the shelf:

<img width="1054" alt="image" src="https://user-images.githubusercontent.com/194400/153750236-d51c454f-b00f-4c8a-8728-50a7cf12d50f.png">

> **Note**: this is ***not*** "**finished**" yet; it still needs to be hand-sanded with 200 grit sandpaper and tidied before the clear-coat varnish is applied ... but you get the idea of the joinery.

# Production Plan 

Now that I've successfully built the prototype shelf, my next step is to "[productionize](https://en.wikipedia.org/wiki/Productionisation)" the process.

For the cutting & joining of the 9 remaining shelves, I need to:
+ [ ] Route (cut) the **4 groves** into each shelf using the hand router + Jigs: 4 x 9 = 36 (30 mins)
+ [ ] **Route** the back underside of each shelf on the router table: x 9  (10 mins)
+ [ ] Assemble/glue the **French cleat** for each shelf and allow 2h to cure x 9 shelves (60 mins)
+ [ ] Rip 7 x **`150mm`** pieces from the **`15mm`** ply boards for the vertical supports (10 mins)
+ [ ] Measure & chop the 4 vertical supports for each shelf 4 x 9 = 36 (60 mins)
+ [ ] Lightly sand each vertical support to deburr (_avoid splinters during assembly_) > (30 mins)
+ [ ] Glue each vertical support in the slot 4 x 9 = 36 (60 mins)

Once the 10 shelves are assembled, mounting them to the wall should be relatively easy because of the (locking) French cleat system. The steps are:

+ [ ] Measure and mark the holes for each French cleat (bottom) 4 x 9 = 36 (10 mins)
+ [ ] Drill the 4 holes & counter-sink each hole 4 x 9 = 36 (30 mins)
+ [ ] Measure the height we want the _top_ of each shelf to be at. (20 mins)
+ [ ] Use the Stanley laser level to draw the perfectly level line on the wall for each shelf (10 mins)
+ [ ] Mark the holes for mounting the French cleat to the wall. (10 mins)
+ [ ] Drill the holes 4 x 9 = 36 (30 mins)
+ [ ] Insert Rawlplugs into each hole 4 x 9 = 36 (10 mins)
+ [ ] Screw the screws into each French cleat strip (10 mins)
+ [ ] Soft-mount each shelf in place (20 mins)

Once we have soft-mounted each shelf we can bring them back down to the workshop and make any adjustments before  finishing (hand-sanding and varnishing) each shelf prior to final mounting with locks.

**Comment by nelsonic** [comment]
Yesterday I measured and routed all the groves for the shelves:

![AB06AD98-90BD-4015-BC5D-05EFD5C33DDF](https://user-images.githubusercontent.com/194400/153832510-55d28031-8741-4fa4-b641-796100fbadb1.jpeg)

> Sadly, I was distracted and made a mistake with one of the shelves. (The one on the right in this picture) but it’s ok, I think I might be able to use it for something improvised. 💭

Here’s a bit more context for how the jigs work:

![D7333323-3C1A-4E6A-BAD0-5DB9756CEEBF](https://user-images.githubusercontent.com/194400/153832607-5a1faabe-7b3c-44a5-a7b8-4e99332a2797.jpeg)

![819DEC6D-1D23-47D4-AC57-1D74AEC043EF](https://user-images.githubusercontent.com/194400/153832640-eea31c07-61ed-4ba3-a0e5-6567d8cb7e51.jpeg)


![20368F07-6310-41C6-B3F5-9307005E6E4B](https://user-images.githubusercontent.com/194400/153832741-93d004e3-21d7-4e4e-ac1f-21de0adfa7fa.jpeg)
![0E5CC1F1-5407-4701-ADF1-2EE1A77F6360](https://user-images.githubusercontent.com/194400/153832754-f93446fa-fbba-4d49-80de-cdf96ac1759a.jpeg)
![94F92A4D-0CAF-4541-B4AD-19825436EB72](https://user-images.githubusercontent.com/194400/153832765-5c80f040-620c-4cc8-b2c2-793bf5790bc4.jpeg)


By the end of the day I had mounted all the French clear strips to the shelves: 

![A330FF15-131D-4900-821C-FBC51D485D0C](https://user-images.githubusercontent.com/194400/153832904-514add6c-c3ca-4f3f-a822-0231c341b68d.jpeg)

**Comment by nelsonic** [comment]
Next in the production plan:

Rip the support pieces on the table saw (150mm) and then chop them down to size on the mitre saw. 🪚 

Going to try and get this done this evening. 🤞

**Comment by nelsonic** [comment]
Got a warning saying there was a critical security update for MacOS: 🐛 
https://www.kaspersky.com/blog/webkit-vulnerability-cve-2022-22620/43650/
 
<img width="713" alt="update-macos" src="https://user-images.githubusercontent.com/194400/153882260-a548b446-3ff4-4978-b595-6e5e159cd69a.png">

so I set my Mac updating at lunch time ... ⏳ 

![image](https://user-images.githubusercontent.com/194400/153880867-b4873550-eae7-474b-8d17-c8ef9f1a499a.png)

Used the fact that I couldn't do work-work to spend a few mins (_of my lunch break_) cutting the **`150mm`** strips:

![image](https://user-images.githubusercontent.com/194400/153884196-46e2a0db-2ea5-42b7-a595-6bd0a6fdd71f.png)

Only did 6 because I think it might be enough ... 🤞  (still have the table saw setup so can easily cut more if needed)
Took me _less_ than **5 mins** because the saw fence was already setup so I just had to run the board through the saw.

So the **next step tonight** will be to **cut** the **vertical supports** on the **mitre/chop saw**. 🪚 
Looking forward to getting it done ... But need to focus on my work-work now. 🧑‍💻

**Comment by nelsonic** [comment]
Made decent progress this evening.
Cut and Prepared the vertical supports for the 8 shelves:

![9177575A-73C3-401A-B43C-E0A5288B684F](https://user-images.githubusercontent.com/194400/154166181-3120c120-26ae-4604-a260-2238def97be8.jpeg)

glued the supports for 4 of the shelves.
Will do the rest tomorrow.

![5C819073-9D5E-4698-8F9D-3EBF2B3521F7](https://user-images.githubusercontent.com/194400/154166343-f9e213ca-9115-4bc2-9ff1-063f11018423.jpeg)

had a visit from the supervisor while gluing-up the supports for a shelf.

**Comment by nelsonic** [comment]
Super not to scale, but this is the positioning for the 9 shelves we have:

![45CE41B9-8502-4189-AFCC-6EC59DB68346](https://user-images.githubusercontent.com/194400/154166634-f1031946-1ca7-40e7-bffb-308fd5e736c4.jpeg)

going to do the laser measuring tomorrow evening, then drill on Thursday and mount on Friday. 🤞

**Comment by nelsonic** [comment]
Transferred the levels/measurements to the wall using the laser level:

![1A9EF1AB-F6FD-4977-8FD8-196BAF9A3D29](https://user-images.githubusercontent.com/194400/154377583-731cd0e8-55fe-4b6a-b0e0-14f350c51dae.jpeg)

All the French Cleats strips are ready to go on the wall tomorrow:

![6076DECD-A1DE-4510-AA84-BD4873D2B51A](https://user-images.githubusercontent.com/194400/154377640-95485a65-d4b4-4603-bf07-011bb9251176.jpeg)

And the bottom shelf is gluing:
![0619BBED-C652-42BD-942B-DDF0DF59DFA1](https://user-images.githubusercontent.com/194400/154377705-75760fcd-b084-4aa2-ac17-e78cb0e0260b.jpeg)

**Comment by nelsonic** [comment]
I need to buy more clamps …

![2C8AC7C3-90F2-47F6-88F3-EC6A6D0F2517](https://user-images.githubusercontent.com/194400/154377961-640fd6fa-418a-4845-8daf-f3d594996b92.jpeg)

**Comment by nelsonic** [comment]
Finished installing the shelves on the wall:

![image](https://user-images.githubusercontent.com/194400/154865126-786bbc52-362f-4558-b8ad-49e17f642471.png)

In the _middle_ the shelves are level:

![image](https://user-images.githubusercontent.com/194400/154865144-f3392a0a-ffc3-45e7-b7e1-0d714816b23a.png)

![image](https://user-images.githubusercontent.com/194400/154865154-802d05fb-509b-4971-89d7-4598c108d6ab.png)

But on the ends some of them are not. It's _mega_ frustrating.
But I've learned several valuable lessons in the process and already know _exactly_ how I would build them differently "_next time_" ... 
To counteract the non-flat wall by using 3 _vertical_ strips of wood fixed to the wall at various points.
Then fix the shelves to the vertical support. The end result would be _far_ more consistent. 

Anyway, not going to re-do it now as it would be a huge waste of materials and time.
Just going to get on with _using_ it for books and will do it _much_ better next time. 

![image](https://user-images.githubusercontent.com/194400/154865308-d07364e0-5283-455a-851e-fce0240a6f93.png)

**Comment by carolrmc** [comment]
Already looking quite busy❗️👏🏻

**Comment by nelsonic** [comment]
@carolrmc indeed. I've unpacked quite a few boxes already. Took this photo Saturday night. It already looks quite different. Will update once _all_ the books are unpacked. Might need more shelf space ... 🙄

**Comment by carolrmc** [comment]
Die Appel val nie ver van die boom nie🥰

**Comment by nelsonic** [comment]
@carolrmc indeed. 🍎  🌳  📚  ...
But when we build our _next_ house in a forrest it will have an expandable/extendable library so we _never_ run out of space for books. If we read too much, and need more space, we'll just add it. 👍 

e.g: https://youtu.be/E8Bq4DbMaRU?t=470
[![image](https://user-images.githubusercontent.com/194400/154866662-cea5d039-fb8c-4f1c-9478-bbee60abb6d8.png)](https://youtu.be/E8Bq4DbMaRU?t=470)

**Comment by nelsonic** [comment]
Stoked that we built the extra shelves: https://github.com/dwyl/home/issues/190#issuecomment-1052675411 ✅ 
We _almost_ have enough space for our books now ... 📚

**Comment by nelsonic** [comment]
![image](https://user-images.githubusercontent.com/194400/157213078-60120d93-5591-4490-9ae9-49ff415f10d5.png)

https://www.goodreads.com/quotes/82833-rich-people-have-small-tvs-and-big-libraries-and-poor

**Comment by nelsonic** [comment]
This is what the library Shelves look like today:  (thanks to @Stephanymtr in #216) 🎉 

![image](https://user-images.githubusercontent.com/194400/211461916-79932b83-eeac-4b55-8061-030ae550cc0c.png)

Still want to **`make` _more_ shelves** #215 to avoid having books horizontal ... 😕 
But thinking of something _even_ more ambitious for that! 😜
