### ISSUE TITLE
Entrance Shoe Rack

### ISSUE THREAD

**Issue by nelsonic** [dwyl/home#181]
At present our shoes are on the floor at the entrance of the house:

![image](https://user-images.githubusercontent.com/194400/132123181-1a014092-88f5-4a9e-8235-1a882299a721.png)

It's messy and we need to fix it ASAP as it's the _first_ thing people see when they enter the house .

I researched the dimensions and sketched a basic shelving unit that _maximises_ the available space:
![image](https://user-images.githubusercontent.com/194400/132123231-c991b7da-fc63-4159-bde6-c0319bd76df1.png)

I have a _strong_ preference for purpose-built furniture especially at the _entrance_ of the house where 
We have the material to make the shelving unit and I estimate we can build and install it in about **`T6h`** of cut & assembly time. There are 33 cuts to be made using 3 different saws & a router. The end result is zero visible fixings, just wood and wall. 

@iteles besides storing shoes, do you have any other requirements?
(_I can think of a few things to store at the entrance and was thinking of using the top shelf for a storage boxes..._)

# Todo

+ [x] Build it!
  + [x] buy materials
  + [x] measure & cut pieces according to sketch
  + [x] assemble pieces
  + [x] finish with round over bit
  + [x] apply varnish
  + [x] apply epoxy resin to high friction areas
    + [x] wait patiently for epoxy to cure ... ⏳ 
  + [x] `#ProgressiveEnhancement`
  + [x] Mount to wall

**Comment by nelsonic** [comment]
@iteles keen to get started on _building_ this so that we can have some tidy storage at the entrance.
If you have time, please have a think about any requirements you want to add so that we can factor them in.
Thanks.

**Comment by iteles** [comment]
👍 

These are the things I would like to keep in/on the entrance:
+ Masks
+ All of our shopping bags (this is 100% where they should live so anyone can access them)
+ Mail in-tray (it needs to be visible that there is stuff in there)
+ Outgoing mail and small parcel tray (also needs to be visible or it won't get taken out)
+ Plants!


I would say that ideally we have one cubby for each person staying in the house so they can walk in and swap out their indoor shoes for outdoor ones and vice-versa.

**Comment by nelsonic** [comment]
Cool. I had a similar list in mind. 💭 

Additions:
+ [ ] Keys - we're using them for the foreseeable future.  🔑 
+ [ ] Store/loyalty cards - for discounts 💳 
+ [ ] Errand items - similar to outgoing mail, but for small reminder things that need to be replaced/bought/fixed/etc. 🎗️ 
+ [ ] Hand sanitiser? (or do we just encourage people to wash their hands in the bathroom?) ✋ 

Some items we want to keep **_always_ visible**, others we want to tuck away because they are unsightly. 👀 
Want to help design a **_visible_ organiser** that goes _on top_ of the shoe rack? 💡 

As for **plants**, as much as I want to integrate plants into _everything_, 🪴 
I'm resisting doing that now as it will make this mini-project take a lot longer than it needs to. 
I just want to get the _initial_ version on the wall ASAP so we can start _using_ it. 
The beauty of using french cleats for fixing the unit to the wall is that it can _easily_ be removed 
and we can adapt/modify the design in response to the feedback we collect. ♻️

**Comment by nelsonic** [comment]
This evening after work I did 2h (20:30 - 22:30) work on this mini project. Managed to do the first 17 cuts and measure out the next 10.

![C58C7C55-2F47-40F9-8A9B-A589FC331C23](https://user-images.githubusercontent.com/194400/133161720-de14d234-e86b-49ea-b184-082f13b7c239.jpeg)

I think I can get the remaining cuts done tomorrow if I don’t have any distractions. Then assembly on Wednesday, Varnish on Thursday and Mounting on Friday. 🤞
All-in I think this item will take me about a day 12h of effort. But spread over 6 days it takes a bit longer because of setup/tidyup time each session.

<hr />

p.s. No regrets buying the oversized (500mm) Speed/Try Square: https://www.wolfcraft.com/products/wolfcraft/en/EUR/Products/Measuring-Tools/Universal-Angle-%26-Try-Square/p/P_5205 it’s been useful on this project where my 200mm one wouldn’t have been long enough. 👍🏻

Wolfcraft Universal Angle and Try Square 5206000 | Angle and Try Square with A 500-Mm Leg For Accurate Marking and Drawing, with A 90° Back Square and Adjustable Angle Measuring Ruler
![66143999-BC7A-41F4-A4E5-424BFAD68107](https://user-images.githubusercontent.com/194400/133162287-50c13031-e2a6-42c8-9191-4cba7f73eb1e.png)

Amazon U.K. Sells them for £20-ish.
I got mine for €15 from Planeta Huerto: https://www.planetahuerto.es/venta-escuadra-universal-280-x-500-mm-wolfcraft-5206000_32766 (ordered a bunch of useful tools and got free shipping).

**Comment by nelsonic** [comment]
Today I made 21 cuts (20:45 - 22:20) and measured+marked the remaining 14 cuts:

![D891030B-1934-43E1-8656-813B08829369](https://user-images.githubusercontent.com/194400/133338741-4cd593c8-4b85-4ef7-9dfc-edcfa43f625b.jpeg)

Did a dry-fit of the border pieces and they work well. I expect the remaining 14 cuts to go quite fast now that they are all measured and ready to go. If I could still make noise today I would do them right now. But gotta be considerate of the neighbours… (mostly their dogs that bark when I’m using the saw/router …) so going to need to add another day (2h) to my estimate. 

I’ve made a *mountain* of fine sawdust in the garage over the last couple of days… 💭
With there was a practical use for it … 
It it was untreated lumber sawdust I would compost it. But plywood had epoxy and I don’t think it’s good for the compost worms … 💭

anyway, made decent progress today. Still on-track to finish this by the end of the week. 🤞

**Comment by nelsonic** [comment]
I might need to do a little detour … https://youtu.be/4kBWKFhOFOM 🙄

**Comment by nelsonic** [comment]
Today I finished the remaining cuts (21:35 - 22:20) and started the assembly:
![CD9BFC6D-EC2D-46EB-A16A-F73F4A434A3C](https://user-images.githubusercontent.com/194400/133513468-e2dcb5ce-1541-40c8-bfbb-3d2a0269db90.jpeg)

My respirator (dust mask) is decent but I can definitely feel some of the micro-dust particles in the air. 🙄
Going to make the dust extractor as a priority before my next mini-project. (Would love to make it on the Laser for precision…)

anyway, will continue with assembly tomorrow night. Sleep time! 👷‍♂️

**Comment by nelsonic** [comment]
Yesterday’s initial assembly went well:
![0F648723-FFE4-4912-BF8B-B6FBCEFE5692](https://user-images.githubusercontent.com/194400/133674202-a978f3b3-4c86-4384-842d-90a9779e56c9.jpeg)

Need to visit the hardware store tonight to buy a couple more supplies for assembly. ⏳

**Comment by nelsonic** [comment]
Leroy was ***Closed*** when I went there at 20:30 last night despite their signs saying they’re open till 21:00 …
![56A4237C-9152-4544-8E44-1CFE3648B52C](https://user-images.githubusercontent.com/194400/133761289-327f175e-4938-4bbc-9240-384c329e2733.jpeg)

So I didn’t make as much progress as I would have liked yesterday … 😔
but I did glue up the center piece:
![83FAA422-9DA9-4BDC-96CB-E6EFC8E64410](https://user-images.githubusercontent.com/194400/133761502-4777d9cb-3b7d-42dd-ab2e-0291e8235e04.jpeg)

And after much trial & frustration with commercially available corner clamps - I bought 3 different kinds! - I made my own jig to glue the mitre joints! Initially I tried just butting them in the corner:
![E11EC804-9EB1-4B3E-A306-B2A8B8C7A3BD](https://user-images.githubusercontent.com/194400/133766944-d5e69286-e105-4c27-98b4-56aeb6043b7b.jpeg)

That kinda worked but I wasn’t happy with the edge. 💭
I needed something that would apply pressure to the outside of the joint … this is what I settled on:
![6654EE0C-86B5-4EE6-8519-46424BDE267C](https://user-images.githubusercontent.com/194400/133767071-b58e3be5-b825-42b1-8703-ac6d7b4ee368.jpeg)
![115D8F3F-79F7-477B-BE99-B0C7304B8DC8](https://user-images.githubusercontent.com/194400/133767078-ca6a1ff0-f436-404a-a8e9-705b1e3c050b.jpeg)

I use the irwin quick-grips I bought at Costco in Edinburgh in 2004 … **#NotSponsored**

I’m  fairly confident this is going to be a good mitre joint. 🤞
The fact that there is glue “squeeze out” suggests that there’s a tight fit:
![7E98A998-7528-43DC-BDDC-438BDF641A7D](https://user-images.githubusercontent.com/194400/133767172-f84b4464-77e7-427a-97b0-f0149f096380.jpeg)

We’ll see how it turns out tonight on the ***Next Episode*** of “***Why Didn’t I Just Buy It At IKEA***?” stay tuned! 😜

**Comment by nelsonic** [comment]
Yesterday’s glue-up worked well. 🎉

today I had to waste a bit of time making a make-shift extra-long clamp-extender in order to compress the sides of the care:
![A2F97710-BAB8-4B8B-B6F4-66331FE21CB3](https://user-images.githubusercontent.com/194400/133859954-190ac933-d207-46bf-b0ad-afbf60090ec0.jpeg)

The hardware store didn’t have longer clamps so I had to improvise using scrap materials. 

Once the clamp extender was ready I used it to mount the first two shelves:
![2CE4E3C6-15E9-4A0F-93A6-973201B32C7F](https://user-images.githubusercontent.com/194400/133860025-20dcaf03-2fcd-47b4-9221-9d0f3f35f8f4.jpeg)
![A4F79913-7176-4BBB-8CBE-7BD8F2820367](https://user-images.githubusercontent.com/194400/133860035-555203de-328c-4975-a6c5-4321ab08f7ed.jpeg)

tomorrow _morning_ (Saturday!) I will mount the 3 remaining shelves and proceed to finishing. ⏳

This evening I practiced routing using the round over but on scrap material for the finish. I think it’s going to look decent. 🤞

**Comment by iteles** [comment]
I love how _creative_ in terms of problem solving this is turning out to be!

**Comment by nelsonic** [comment]
I used to make all my own jigs/mounts from scratch when I made stuff as a kid. Couldn’t afford to buy anything ready-made and in many cases they just weren’t available from the stores… problem-solving from first principals using scrap/found materials is my DNA. 😜

**Comment by nelsonic** [comment]
Finished gluing the last shelves:
![D970144A-6AB3-45EA-983C-4B8703945A19](https://user-images.githubusercontent.com/194400/133887661-0d5aab53-b109-4e59-ba0a-5fb9306a152a.jpeg)

now going to edge-route with round over bit.
Before sanding, varnishing and epoxy #173

**Comment by nelsonic** [comment]
Before:
![Uploading 2A10150A-1C18-4064-9B35-835AF3A3567C.jpeg…]()

After:
![F1BEDDB8-7BC2-4140-A5C3-5B10FBFC795E](https://user-images.githubusercontent.com/194400/133888612-63816def-8d28-4a48-81c4-ac2ec27d30ab.jpeg)

Rounded edges for that “furniture” feel. 😉

**Comment by nelsonic** [comment]
Installation
![7AAAFC7F-4E22-480B-A87A-C229741766DB](https://user-images.githubusercontent.com/194400/133890000-7916330e-d492-4459-86c0-7af1a4477ada.jpeg)
 context:
![C7B3565E-E3D4-4DEC-9411-2799FEC97B1D](https://user-images.githubusercontent.com/194400/133889992-6dd023fe-c2eb-429b-8a1a-debe697c8854.jpeg)

**Comment by nelsonic** [comment]
Before varnish:
![83C95E75-8B57-4E56-BCB1-EC86760369E3](https://user-images.githubusercontent.com/194400/133908428-11cfb2cd-d95d-4ae3-bdf8-f75ccbfd8108.jpeg)

after:
![01021609-5D4B-434C-8811-BA473D6B643E](https://user-images.githubusercontent.com/194400/133908426-551cd64c-9890-4b25-bfdf-dd69095c71c1.jpeg)

it’s a “clear coat” … but it does make the piece a *lot* darker … 💭
I’d prefer the original, but given that shoes can be dirty, I felt that protecting the piece was more important than the color.

**Comment by iteles** [comment]
How many coats of varnish does it need?

**Comment by nelsonic** [comment]
@iteles good question. I bought enough Varnish for 3 coats. How many would *you* apply? 💭

**Comment by nelsonic** [comment]
Meanwhile on the *top* of the unit, where I expect to put things like keys and in/out tray, I’m going to coat it in **Epoxy Resin** for high durability.

My bulk order of Epoxy #173 hasn't arrived yet so I’m going to use this small container I bought at Leroy (for the price of gold!!): https://www.leroymerlin.pt/Produtos/Tintas-e-drogaria/Preparar-antes-de-pintar/Reparacao-da-parede/WPR_REF_81972961

![2C004E00-BD9A-42A0-A8A1-5845B9507864](https://user-images.githubusercontent.com/194400/133920772-644ba622-cb56-4018-ab1e-524829c51c4d.png)


![A5F0DB6F-8ED7-4A66-8033-1FFB162E85FC](https://user-images.githubusercontent.com/194400/133920735-91446f4e-1ab3-41d7-b2d6-dc8e02ddd458.jpeg)

![185AC7DA-11CB-4C55-A60C-C871F57957E9](https://user-images.githubusercontent.com/194400/133920744-a98548b6-97fc-43ad-9322-38675bf7e46a.jpeg)

The bulk order is around €10/kg. A lot cheaper than €57/kg … 🙄

The expensive one is a **Sunk cost** so just going to use it. (Can’t take paint/finishing products back to the store…) also, having it here means I can get this work done *now*, which what I *really* want. 💭
But don’t want to waste any so only mixing/preparing what I need!

Using the epodex online calculator:
https://www.epodex.com/en/epoxy-resin-calculator looks like I need around 500g of resin:
![51C5F231-F147-4B0D-89DF-B671819F4D3D](https://user-images.githubusercontent.com/194400/133920892-17bf3fce-9e86-4b4a-84aa-60cef88d947e.png)

Going to prep it now. ⏳

**Comment by iteles** [comment]
@nelsonic I was thinking 2, but 3 on the flats where the shoes will go. Cool!

**Comment by nelsonic** [comment]
Cool. Varnishing is my least favourite part of furniture building, so thanks for offering to do it. 🎉❤️

**Comment by nelsonic** [comment]
According to the Epodex calculator I need 500ml to cover the surface area. The container I have is 1000ml. So I need to measure half of each component.

A: 625/2 = 312.5
B: 375/2 = 187.5

# mise en place:

![2DC215F5-4CF4-436F-AC1B-A385A609333E](https://user-images.githubusercontent.com/194400/133923152-b835b0d1-134f-4177-a47b-eaa50215474d.jpeg)

Using a “free” bottle from the recycling bin instead of a disposable plastic mixing cup. And a “free” bambu chopstick as my mixing stick. I will still dispose of all items in the hazardous waste at Leroy when I next visit.

![335951EF-AEF1-4174-9EEB-8DDD3D0E0EEE](https://user-images.githubusercontent.com/194400/133923260-ccd60ee7-0747-4e79-aaa6-d19f07f8b223.jpeg)
![07F3CA44-BC8C-45DB-B4EF-1C453D0A4448](https://user-images.githubusercontent.com/194400/133923268-b1b761bb-c131-4a05-9eda-67e86ef3e0c6.jpeg)
![A17C744E-9DE8-4B66-80FF-0FB20A8722E3](https://user-images.githubusercontent.com/194400/133923270-d994863d-45d5-4931-88f1-a93c3d72d25b.jpeg)
![74EFC20C-FFEC-465D-9A42-9D53B691AE32](https://user-images.githubusercontent.com/194400/133923271-0a224856-907e-4b7d-bf7a-3dd7c9bb6add.jpeg)

Turns out that 500ml is *way* more than 3x what I needed for just the top shelf!! So I covered *all* the “treads” (surface area that will be exposed to friction) with epoxy! It’s a case of making lemonade 🍋… this way the whole thing will be a *lot* more durable than just the varnish. 🙌

![CDD06060-45DF-4E35-9260-864D600C7A27](https://user-images.githubusercontent.com/194400/133923376-b7f6e58f-15fe-4c8d-ba19-a555b84f2186.jpeg)

finished comfortably within the **30 mins** “work time” (before the epoxy starts to cure). Now gotta wait for it to harden. It’s got a “old yacht” furniture feel. Should out-last all of us. And when it does eventually wear down from use it will look “used” which I’m super keen on.

**Comment by iteles** [comment]
"Old yacht" 😂
How long til it's completely dry? 🤩

**Comment by nelsonic** [comment]
@iteles epoxy package says 24h … ⏳
Plenty of other things I can do in the mean time. 

Heading to Leroy to buy 3000 grit sand paper disks …
https://support.ecopoxy.com/how-to-finish-an-epoxy-table
![08F7790C-20C2-41C4-9676-B34DE62C68F6](https://user-images.githubusercontent.com/194400/133924727-25bd9b32-4ace-4e10-bf45-25b506855249.png)

**Comment by nelsonic** [comment]
Tested the epoxy this evening. it's nowhere _near_ dry/cured. Oh well ... just have to be patient. 🙄 ⏳

**Comment by nelsonic** [comment]
Tested the Epoxy again this morning during my break from work. Still not completely cured so the 24h is not fact. 🤦‍♂️ 
Good thing I didn't have a deadline for this ... 🙄

**Comment by nelsonic** [comment]
Just gonna be patient on this and wait till tomorrow to follow up on this. ⏳

**Comment by nelsonic** [comment]
Another 24h have passed and the epoxy still hasn’t completely cured … 🤦🏻

![EA384932-F351-4991-8F31-E02ED13ED5D8](https://user-images.githubusercontent.com/194400/134148590-bc109de4-4686-43bf-a12a-5a2b06587b3c.jpeg)


https://www.maverickcomposites.com/blogs/news/epoxy-resin-cure-at-us

![B4319E38-9E9C-4DB8-8DAF-B0BA9CC8CCA4](https://user-images.githubusercontent.com/194400/134148601-97b2ba1b-723a-414f-920a-f455eaf078db.png)

So I’m thinking of placing a portable heater near the piece and blasting it with warm air … 💭

**Comment by nelsonic** [comment]
Last Tuesday I put the heater on in front of the curing piece. Left it blasting overnight. On Wednesday the epoxy was *less* cured (more tacky!) than before the heater!! 🤦🏻
![4FBDAEF3-8EA4-4201-8C79-7DF1497AF679](https://user-images.githubusercontent.com/194400/134801248-8ac19d0c-dcb4-473e-a174-d783275155c4.jpeg)

so I switched off the heat and just used the fan.
A day later it was the same. 🤷🏼‍♂️

**Comment by nelsonic** [comment]
Just occurred to me that I didn't upload the photos of this ... 
we've been using it for 3+ months and it's been good. ⌛ 

The Epoxy failed badly: 🤦‍♂️ 

![image](https://user-images.githubusercontent.com/194400/148375261-d2d75f40-c550-4e32-b32c-239407af2191.png)

so I ended up stripping it off: 🔥 

![image](https://user-images.githubusercontent.com/194400/148375345-309007d2-e605-421a-bc08-55316ed1491a.png)
![image](https://user-images.githubusercontent.com/194400/148375318-4d7311cd-783a-4b0c-996b-9f891db7e1a8.png)
![image](https://user-images.githubusercontent.com/194400/148375431-006b9028-5d6b-4ccd-a44c-c9322026cec9.png)

![image](https://user-images.githubusercontent.com/194400/148375379-cff7049e-a393-41aa-a989-79ccf46fe8e3.png)


Bought some paint: 🛒 

![image](https://user-images.githubusercontent.com/194400/148375770-960c5339-7948-4721-bc03-cfbe7fe333b6.png)

Supposedly eco-friendly, no nasty chemicals. 🤞 

![image](https://user-images.githubusercontent.com/194400/148375869-c6439307-b2d6-47b6-a7a8-4cc539a67d41.png)
![image](https://user-images.githubusercontent.com/194400/148375824-6716180f-4278-46cd-9aca-0d211c6b3863.png)


Painting the rainbow: 🌈 

![image](https://user-images.githubusercontent.com/194400/148375091-34f94857-09de-4902-a47c-9351eb6c23e6.png)
![image](https://user-images.githubusercontent.com/194400/148376192-2441a905-7009-4858-8160-546be1f7179f.png)

Fitting:

![image](https://user-images.githubusercontent.com/194400/148378209-44e7ac21-cbde-4f44-b171-29cf19369a8b.png)


Installed: ✅ 

![image](https://user-images.githubusercontent.com/194400/148376357-26ca6d79-b463-4200-870e-b87e5b379c45.png)

## UAT:

![image](https://user-images.githubusercontent.com/194400/148377704-29d2c5b1-2ff5-48e7-b981-e231a0ce578a.png)

The fact that Alex's hair is this short and shows how long ago this was taken ... 

Inês removing the painters tape:

![image](https://user-images.githubusercontent.com/194400/148378151-56f06dc0-9089-4d9c-a853-fda96ece533d.png)


# _Conclusion_

I learned a lot from this project/experiment.
Specifically what _not_ to do ...
If I had to do it again, I would use different material, specifically laminated plywood. see: https://github.com/dwyl/home/issues/123
That way it would already be finished and I wouldn't have to _think_ about applying any finish.
The material costs more up-front (probably double) but I will easily save that in time!

The carpentry/joinery part of the piece was relatively quick; **6h**.
_Finishing_ first with the varnish, then epoxy (_the fail and then stripping took ages!!_) then paint took _considerably_ longer than I expected; **15h**. 
Which reminds me .... I _really_ need a better way of keeping track of how much time I spend on things so I'm not relying on my memory/estimation of how long it took ... https://github.com/dwyl/product-roadmap/pull/22

**Comment by iteles** [comment]
I really really like the stripped back epoxy finish but agree that laminated plywood is 100% the way to go for things like this that require more than just a coat of varnish 👌🏻

It's been working well! Thank you!
