### ISSUE TITLE
Replace Wooden Deck with Composite

### ISSUE THREAD

**Issue by nelsonic** [dwyl/home#183]
The wooden deck in the back garden was not properly treated when it was installed in 2019. 
As a result some of the deck pieces have warped despite the installer assuring us they would not. 🙄 

I propose that we research Composite Decking and find a competent installer to replace the decking before next summer.

https://www.leroymerlin.pt/Produtos/Pavimentos-revestimentos/Pavimento-exterior-relva-artificial/Decks/WPR_REF_82661076
![image](https://user-images.githubusercontent.com/194400/132315895-67792d5a-bba9-4295-8644-756481032fde.png)

Local installer: https://www.olx.pt/d/anuncio/instalao-de-deck-compsito-IDGylWc.html
![image](https://user-images.githubusercontent.com/194400/132314525-9be313ed-32b0-448e-8eac-c751fe02738d.png)

**`priority-3`** as this is _unsightly_ but still _functional_. 

# Todo

+ [ ] Measure the area of decking we need to replace
+ [ ] Research available products (_the Leroy deck looks decent IMO_)
+ [ ] Contact installers to ask for quote
+ [ ] Get the work done & pay them
