### ISSUE TITLE
Setup Teepee

### ISSUE THREAD

**Issue by nelsonic** [dwyl/home#186]
My sister recently made a Teepee for us from scratch and brought it over during the holidays.

She used the following YT video as a guide: https://youtu.be/t9OZ8Zlfj9I

![EFAE5310-5E06-4CCE-B9DB-95EE872FBB04](https://user-images.githubusercontent.com/194400/148695222-1e030a38-b050-4b7e-8c88-4096ebec469c.jpeg)

> yes, this sewing channel has nearly 400k subs! 🤯

If you watch the video, you can see that the poles for the teepee don’t actually need to be cut. We just need to have the holes drilled at the right point to thread the string to bind them together.

# Todo

- [ ] convert measurements from inches/yards to cm
- [ ] Drill holes in the 4 poles at the correct measure.
- [ ] sand the poles for any tear out from drilling
- [ ] Mount the teepee with the string (brand new high durability shoelace I had spare)
- [ ] UAT!

**Comment by nelsonic** [comment]
The measurements for the poles are given in the first 2 mins of the video:

72 inches pole length = 182.88cm
10 inches from top = 25.4cm
2 yards string  = 182.88cm

Our poles are 240cm. 

The measurements *definitely* don’t need to be exactly what the lady did in the video because the fabric pattern is not an exact copy, so I’m rounding the centimetres to the nearest whole. 


240 - 183 = 57 cm
57 + 25 = 82cm

so I need to drill a 4mm hole in each pole at 82cm.

this should only take me 5 mins (mostly setup time); the actual drilling will be less than a minute for the 4 holes. 

Doing it now.

**Comment by nelsonic** [comment]
Scratch that. It’s dinner time. Gotta be a the table even though I’m fasting. Will pick this up later. ⏳🤞

**Comment by nelsonic** [comment]
Got 5 mins now. Going to get it done. 🤞⏳

**Comment by nelsonic** [comment]
Holes drilled. ☑️
setup complete:
![763CD348-2A72-4E99-B04F-78F8F4FAD98B](https://user-images.githubusercontent.com/194400/148700581-faa6fc32-1817-4b8f-8e29-f9cd9631efaf.jpeg)

**Comment by nelsonic** [comment]
We could definitely trim the poles down … however I was thinking we could do an *inverted* teepee on the top with a hole in it and make it a “basket” the kids can store things in. 💭

UAT tomorrow morning. 🤞

**Comment by nelsonic** [comment]
Our son has been playing in the TeePee for the past 5 days and loving it. 🎉 

@iteles what are your thoughts on cutting the poles? 💭 ✂️

**Comment by iteles** [comment]
I quite like it the way it is, feels like it's the way it's meant to be !

https://imgc.allpostersimages.com/img/posters/native-american-teepee-grand-island-nebraska-usa_u-L-PXR8LE0.jpg?artHeight=550&artPerspective=n&artWidth=550&background=ffffff
