### ISSUE TITLE
Coat Rack for Cloak Room

### ISSUE THREAD

**Issue by nelsonic** [dwyl/home#195]
Now that I've tested the Workshop Cloak Rack dwyl/home#194, it's time to build the _real_ one and incorporate all the learning.

# Todo

+ [x] Take detailed measurements.
+ [x] Create the design in Lightburn
+ [x] Cut it on the Laser
+ [x] Assemble the pieces
+ [x] Mount it on the wall!

Given that I've already done the "hard" part of designing the hooks dwyl/learn-cad-cam-cnc#57,
 I expect the design of Cloakroom coat rack to take around 20mins in lightburn 
and then I will leave it cutting while doing other DIY tasks.
