### ISSUE TITLE
Microwave Positioning

### ISSUE THREAD

**Issue by nelsonic** [dwyl/home#200]
The plan for the microwave ovens is to have them in the Small Kitchen Appliances Rack.

at present it’s _temporarily_ sitting on the temp counter:

![1DBD7049-F2C4-4E1B-BB22-6B83FE817153](https://user-images.githubusercontent.com/194400/166102505-185450bc-02bf-40ec-8a74-348eee252b39.jpeg)

Want to place it on the top shelf as seen in this pic.

# Todo

+ [x] measure the height of the _current_ microwave oven
+ [x] Move the height of the shelf to accommodate
+ [x] place the cover plate on the electrical socket 
+ [x] plug into available under counter socket.
+ [x] Subtask: resolve the issue with the protruding microwave electrical plug ...

think this will take around T10m. Going to get it done _now_ so that it’s done.

**Comment by nelsonic** [comment]
adjusted the height of the top shelf in the cupboard and placed the microwave inside it:

![6DAAC348-8B35-4C98-A469-7A149E1FD83E](https://user-images.githubusercontent.com/194400/166121906-96fc7f84-4035-46eb-a6b2-230909615b3b.jpeg)

Problem is the eléctrica socket is behind the microwave and the plug 🔌 pushes the micro beyond the edge of the shelf/unit so the door does not close. 🤦‍♂️
so I need to either:
1. buy a new right angled plug and change the plug (this is the cleanest solution)
2. Buy an extension with a right angled plug and plug the microwave into that.

either of these subtasks requires a trip to the hardware store. Might do that tomorrow morning. 💭⏳

**Comment by nelsonic** [comment]
Leroy opens 09:00 tomorrow. 🕘 
Going there after swimming 🏊  so that I have the materials we need 🛒 
and can _finish_ this task tomorrow after we get back from lunch. 🤞

**Comment by nelsonic** [comment]
Past the point of no return:
![E3A00D31-3B68-45F1-AFBA-4C799913A403](https://user-images.githubusercontent.com/194400/167250817-a292a1c3-9197-491a-bcab-1efcfa6731f3.jpeg)


Wired up:
![2915B0DA-5B40-4526-96D6-3433CD98DD13](https://user-images.githubusercontent.com/194400/167250829-bd07130e-6776-4ac0-a390-f9644f07ddc9.jpeg)


Before:
![539CCDBB-0DD6-43D7-856B-B9436D13C54E](https://user-images.githubusercontent.com/194400/167250840-22967097-efb8-404a-832c-7cb43cf3308e.jpeg)

after:
![F3DF0F35-3CF6-455F-B5F6-7555E80EC666](https://user-images.githubusercontent.com/194400/167250872-f1856b9b-a26c-44ae-a51d-372484cd3914.jpeg)

***muuuch*** slimmer profile! 👌🏻

Installed:
![9CDF3750-CB6B-46E2-9D2D-D1B70E8F12C7](https://user-images.githubusercontent.com/194400/167250915-d9e99d1c-aee1-40fe-afef-d86a96268595.jpeg)


Cupboard Door closes flush:
![629647FA-4FA8-4927-A50E-C0F48628A40A](https://user-images.githubusercontent.com/194400/167250928-310acfa2-1699-41ca-b279-3c3a40404b0e.jpeg)

ready for testing! 🤞

**Comment by Stephanymtr** [comment]
Love the appliace garage! Haha I'm a huge fan of the clean look and clutter free counter tops. 

Because it's out of sight, it's also out of mind. When the microwave isn't being used, it's easy to forget to give it some love. It might be a good and specific task to add to the cleaning list. 
![20220524_111609.jpg](https://user-images.githubusercontent.com/91985721/170009985-c19c7517-7bba-4e92-9d95-968edde0c2a8.jpg)

**Comment by nelsonic** [comment]
@Stephanymtr thanks for the feedback! 💬 
Definitely needs to be added to the cleaning checklist. ✅

**Comment by iteles** [comment]
Turns out our cleaner didn't even know it was there 🤦🏻‍♀️🤦🏻‍♀️
I spoke to her today and it's now clean. Thanks for catching this @Stephanymtr !

**Comment by nelsonic** [comment]
Closing as the original requirement has been met. ✅ 
@iteles if you have anything `else` related to the Microwave, please open a `new` issue. 🆕 
Thanks again. 👌
