### ISSUE TITLE
Welcome [Relevant/Useful Info] Screen

### ISSUE THREAD

**Issue by nelsonic** [dwyl/home#210]
When re-doing the house we left space for a screen at the bottom of the stairs that will "greet" people as they enter the house; we refer to it as the "Welcome Screen". The longer name could be "Welcome - this is what you need to know right now - Screen".

The idea is to display the most relevant information and nothing more.

### What _could_ be displayed on the screen?

+ [ ] **Time** (clock)
+ [ ] **Calendar** with up-coming activities / events 
  e.g: music lesson in the leisure room 09:30 - 10:30
  cleaning person @home 14:30 - 18:30
+ [ ] **Temperature** / **Weather** both current and forecast (e.g. remember to take an umbrella!)
+ [ ] Lunch menu (meal plan); 
+ [ ] Who is where and doing what? 
  e.g: Nelson is in the studio working on issue `#X` 
this can fetch data from our [App/API](https://github.com/dwyl/app).
  **`A*`** is sleeping (_please be quiet_).
+ [ ] **Decibel meter** informs of the noise level e.g: https://github.com/dwyl/iot-decibel-meter
+ [ ] **Energy Consumption** - so everyone can learn/know how much energy we are using in real-time
+ [ ] **Message board** - and useful info/instructions that everyone should be aware of.

We will power the screen with a Raspberry Pi which will allow us to monitor presence and turn the screen on/off in response to motion and time of day. e.g. don't turn it on after 20:00.

**Comment by iteles** [comment]
I don't think we need to have a screen on for the sake of having a screen on, but if it's displaying _interesting_ information like noise levels and energy consumption, I'm super keen on this!

**Comment by nelsonic** [comment]
@iteles feel free to _prioritise_ (label) this issue and see where we can squeeze it in. 
The info on the screen can be iterative. i.e. just put up a landscape picture on it for now ...
The work of installing the screen + raspberry pi is the first step.
