### ISSUE TITLE
Chore: Organise Library -> Clear Thinking Sanctuary 💭 

### ISSUE THREAD

**Issue by nelsonic** [dwyl/home#216]
As noted in https://github.com/dwyl/home/issues/211#issuecomment-1344301222 the Library shelves are a mess! 😖 
When I unpacked the books from the _many_ boxes, 📦  
I put them into _rough_ categories but _definitely_ not a "system". 🔣 

# Story

As a `person` who is exceptionally time-poor but wants to have a calming place to sit and read,
I `want` a De-cluttered and Organised Library 
`So that` I can `focus` on my reading/thinking and not get distracted by disorder.

# Todo

+ [ ] **Take `before` Photos** of both sides of the library. 📱 📸 
  + [ ] Upload the photos to this issue
+ [ ] Remove anything that doesn't _belong_ in a library e.g. greetings cards, xmas decorations. Musical/noisy books.
  + [ ] Neatly place these on the shelf under the main staircase
+ [ ] Take **`first step`** Photos with clutter removed. 📷 
+ [ ] Remove all books and magazines from the 3<sup>rd</sup> (now child-accessible) shelf [the shelf where @iteles' greetings cards box is currently ...] and stack them on the table _temporarily_ while the re-org happens. 
+ [ ] ***Organise*** the books into relevant categories. 
  + [ ] Place books back on the shelves in their relevant categories.

+ [ ] Determine how much additional book shelf space we're going to need: https://github.com/dwyl/home/issues/215

> **Note**: This is a good opportunity to review the books we have ... 💭 
> But is _not_ the time to do a _full_ catalog which is a multi-day exercise requiring a bit of up-front work: https://github.com/dwyl/library/issues/73
> We need to update our App and add Barcode/QR scanning ... 🧑‍💻 ⏳ 

+ [ ] Optional/Bonus Level: Add Labels to the Shelves! 🏷️  ... 
  these can be _general_ like "Startups", "Finance", "Health" etc.
  + [ ] Use the `Brother PT-D600VP Label Maker` https://github.com/dwyl/home/issues/135 ideally with Black-and-White `12mm` Labels. 
  We should still have a roll of them: https://github.com/dwyl/home/issues/135#issuecomment-907004071 but if you don't find them, please just add the **`copy`** (proposed text) for the labels in a comment in this thread so that when we do find the label tape/cartridge it's a `T10m` sub-task. 👌 
  

> **Note**: I'm fully aware that having a _dedicated/separate_ room in the house specifically for reading/thinking is considered by many to be a "luxury". My counter-argument is this: _many_ people have a living room with a Television. They could easily just remove the TV and have a library. TV robs you of your time. Books give you time back because they allow you to learn skills faster and apply them in your life/work.

**Comment by Stephanymtr** [comment]
I'm happy to take on this task next time I go over to the house.  

1. You mentioned "Startups", "Finance" & "Health". Could you share a list of all relevant categories I should follow ? Even if it's a rough list. I don't know all the books that are in your library atm. Therefore, a rough category listing should help me quickly place each book correctly after a quick skim through. 
2. How would you feel about displaying baby books on the bottom shelf, A1's/toddler books on the 2nd shelf and older children's books on the third shelf?
3. I also have been trying to stick with a 'forward facing book shelf display' for all children's books. Should I continue doing that ?
4. I've replaced batteries of books that needed batteries changed. I can double check that as I go through them. However, I know there are a few books that need some TLC. Can I use transparent tape or did you have something else in mind you wanted me to do with those books?
5. What should I do with any odd shaped/big books that only fit sideways?  I could be wrong, but I believe you have a few big books that are currently placed horizontally.

**Comment by Stephanymtr** [comment]
Step 1 - Before photos:
![image](https://user-images.githubusercontent.com/91985721/209297423-291b8924-009e-4d49-bca8-19bfab570e8a.jpeg)![image](https://user-images.githubusercontent.com/91985721/209297442-103cadf2-5b5c-41a2-ab4f-7b18de9a1859.jpeg)![image](https://user-images.githubusercontent.com/91985721/209297466-fb30a082-d1e2-423a-817f-a94b799c17c3.jpeg)![image](https://user-images.githubusercontent.com/91985721/209297489-2bdcf00f-906a-4861-9c7c-50a224e9060a.jpeg)

**Comment by Stephanymtr** [comment]
Step 2 - clutter removed ![image](https://user-images.githubusercontent.com/91985721/209301309-a52fd1fa-b7bf-412c-bfd8-93a7e5b741ef.jpeg)![image](https://user-images.githubusercontent.com/91985721/209301323-3f817b11-9870-40f7-899b-c9b3e4964270.jpeg)

**Comment by Stephanymtr** [comment]
How would you guys feel about storing cookbooks in the kitchen ?

**Comment by Stephanymtr** [comment]
Step 3 - books from the 3rd shelf have been removed. ![image](https://user-images.githubusercontent.com/91985721/209306105-5ea4c331-ddba-4dbe-970f-3e2c373894e9.jpeg)![image](https://user-images.githubusercontent.com/91985721/209306121-f1e21391-22e8-4d50-b7b7-c5747fca40dc.jpeg)

**Comment by Stephanymtr** [comment]
These are some photos of large books that only fit sideways ![image](https://user-images.githubusercontent.com/91985721/209312247-b0b59d13-fb07-426b-827a-7f21065acb40.jpeg)![image](https://user-images.githubusercontent.com/91985721/209312262-7d4641c9-2430-41a2-8660-689b3b3b6830.jpeg)![image](https://user-images.githubusercontent.com/91985721/209312270-d6fa327c-657a-4895-a96e-a8f2c8092c59.jpeg)![image](https://user-images.githubusercontent.com/91985721/209312277-175da4bd-c5db-44df-be65-a00696d611a1.jpeg)

**Comment by Stephanymtr** [comment]
More questions: 
1- Just to be clear, do you want me to reorganize all the books or just the ones from the 3rd shelf ? (Plus 1st and 2nd self aka all children’s books ofc)
2- I suggested above saving the 3rd shelf for older children's books, so I wanted to ask if I should place any adult books back on the 3rd shelf Ex: cookbooks.  
3-Is it okay to collect ALL the books I see around the house and bring them back to the library? I believe I saw one or two in the dining (which might be new children’s book) and cookbooks in the kitchen too.

**Comment by iteles** [comment]
@Stephanymtr my answers to these last 3 questions so you can keep going:
1. I believe the idea is the WHOLE library which is why this is such a mammoth task!
There are a couple of shelves which you shouldn't have to worry about, like the big shelf at the very top that is already all tech/programming books
2. I think we'll struggle even more for book space without that third shelf 😏 But we can always choose a small category of books to leave out for now and have somewhere else for example. That third shelf is definitely child accessible and should be for children. We'll build more shelving for the books that are left out. 
3. Yes, definitely collect all the books from around the house please!

**Comment by Stephanymtr** [comment]
Hi, can I place the magazines behind the books like this? (Photo1) Ex: food magazines behind cookbooks... as a temporary fix, at least. 
I found a lot of books for older children which were all moved to the 3rd shelf. Therefore, it's been really challenging making room for the adult books that were on that 3rd shelf.

![image](https://user-images.githubusercontent.com/91985721/209356082-f31d91f0-14ee-491e-80d4-6b41a87f0b53.jpeg)2)

**Comment by Stephanymtr** [comment]
Due to the time I won't be able to finish tidying up the Library today. @iteles @nelsonic where should I place the extra couple books that still need to be organized? There's no more space on the shelves.

**Comment by Stephanymtr** [comment]
I didn't have a chance to post an update on Friday:

- I removed all the books from the first 3 shelves and wiped everything down. I put only children books back on the those shelves.
- The 4th shelf had some extra room, so that's where I was planning to place most of the adult books from 3rd shelf. However, the 4th shelf is not as tall compered to the 3rd shelf. It was tricky finding a subject/category where all the books are of that height or smaller. I moved some back and forth many times trying to make sense of it, but I ended up running out of time. 
- Because of the shelf height/book sizes, it forced me to place/display some of the books horizontally (including children's books).
- I wasn't sure (question above!*) where to place the extra books that were out, so I kept them in library *off the floor* until next week when I come over to continue tidying up. 
- There were also lots of magazines which I put under the main staircase while I was cleaning...so I kept them there until next time. 
- I tidied up all the stuff that was under the main staircase to make room for the musical/noisy books along with all the random bits I found in the library. 

I def will need more time to continue the work on tidying up/organizing the books.

![image](https://user-images.githubusercontent.com/91985721/209453933-b109bef7-cdc3-43dd-80ed-8fa90230aeb5.jpeg)

![image](https://user-images.githubusercontent.com/91985721/209453930-851543e0-bbe6-44fc-88b3-1ab17f187ef1.jpeg)

**Comment by nelsonic** [comment]
Hi @Stephanymtr, thanks for reading and replying. 🙏 
Here are some quick answers to your questions:

1. No. I don't have a list to follow. The categories will _emerge_ from the organization exercise. 📝 
  That's kind of the point of the exercise. To save _me_ the time of having to do the manual organizing ...
   However _most_ of my books fall into 5 broad categories: 
   1. Non Fiction 
   2. Personal Development
   3. Finance/Investing
   4. Science & Technology
   5. Business. 
   
  Within these there are niche sub-categories such as "Memory Techniques", "Technology Startups", "Revenue Funded Small to Medium Business" or "Rental Property Management". The _specific_ category of these books doesn't really matter. Just group _similar_ sounding books together and we can create the **`label`** for them _later_.

2. Displaying Baby books on the Bottom shelf is _exactly_ the plan. 
    Just not in the library _right now_ ... Rather we will do it on the bottom shelf 
    under the main staircase where there will be a rug for "tummy time". 🔜 

3. Forward facing books will be placed on the wall _outside_ the library in the coming months.
    For now we need to maximize the tidiness of the shelves in the library and therefore need to _minimise_ the number of cover-facing books ... i.e: we don't have enough ***space*** to display the covers of all our books ... 😞 (which library does?! 🤷)

4. Replaced the batteries in the "books" ... battery-powered paper toys aren't books they are toys. They don't belong in the library. They belong on the shelf under the main staircase. we need a _hard_ rule on "no noisy toys" in the library otherwise it ceases to be a place for quiet reading & reflection and becomes a **ZOO**; literally. 🦁 

5. Odd-shaped books need to be placed on a pile and their dimensions captured [separate issue]. As much as I like the larger format books they are a bit of a pain in the but from a library planning perspective so we need to consider where/how to store them longer term.

**Comment by nelsonic** [comment]
@Stephanymtr thanks very much for doing the initial tidy of the library it looks much better. 👍 
Sadly a few books were left on top of the footstool and that looks _mega_ cluttered. We need to move them ASAP. 🙏 
We still need a _lot_ more shelf space in order call this "done". ⏳

**Comment by Stephanymtr** [comment]
@nelsonic Yes, saving the 3rd shelf for children's books only meant that we weren't going to have enough shelving space for some other books (aka the ones on top of the footstool and under the stairs) . Could I move them (temporarily) to under the stairs ?

**Comment by nelsonic** [comment]
100%. Under the stair for now. 🙏
