### ISSUE TITLE
Research Quest: Visit London's Living Walls [Image Heavy!] 🌱🏡 

### ISSUE THREAD

**Issue by nelsonic** [dwyl/home#22]
From **day 1** of us viewing the Braga House as a potential Home for Creative Technology, 
I've been "_dreaming and scheming_" of _how_ to wrap the _entire_ building in plants 
and make the first "_reclaimed by nature_" building in Portugal. 

Instead of a characterless concrete block, I believe _all_ buildings should look like this:

![image](https://user-images.githubusercontent.com/194400/48312317-ce19e180-e5a4-11e8-81ed-2a3cc0be6b36.png)

Cities should become carbon-neutral _forests_ and looking out of a window should feel like _nature_ no matter where you are. People will _feel_ better, healthier and happier. This is why we are investing in researching all the plants #8 to "grow fresh air indoors".

![image](https://user-images.githubusercontent.com/194400/48312629-a5e0b180-e5a9-11e8-90f0-f8426428ea05.png)
> Image credit: http://www.plantdesigns.co.uk/single-post/2017/04/05/Lush-Living-Walls

> ‘The health benefits of the great outdoors: A systematic review and meta-analysis of greenspace exposure and health outcomes’ is published in the journal Environmental Research on 6 July.
see: https://www.uea.ac.uk/about/-/it-s-official-spending-time-outside-is-good-for-you

> The architect(s) we hired to help us with securing our planning permission for renovating the house were _unenthusiastic_ about the idea of a "Living Wall" ... they didn't _understand_ the "vision" of a carbon-neutral house that feels like you are entering a "secret garden". And instead they wanted us to paint the outside in "tones of grey" and make it look like every other bland modern box ... 😕 
Sadly, we didn't have much of a _choice_ for Architects, otherwise I would have considered an alternative who "_gets it_". I _firmly_ believe that the _future_ is buildings _covered_ in plants! 
And any architect who is _not_ designing their projects this way will be on "losing side" of history. 

# "The future is already here — it's just not very evenly distributed." ~ [William Gibson](https://en.wikipedia.org/wiki/William_Gibson)

_Some_ architects are using Living Walls as a "feature" or "selling point" of their high-end buildings, e.g:

![image](https://user-images.githubusercontent.com/194400/48312533-f9520000-e5a7-11e8-9017-0edb2d62ae54.png)

see: https://www.ansgroupglobal.com/living-wall/case-studies/douro-street

But it's more of a "token" than a genuine commitment to the idea.
I get the feeling that the Architects are _afraid_ that if they _cover_ the building in green,
the people won't be able to see their signature slabs of concrete and glass and they won't get any _recognition_ for their hard work ... this is a narcissistic _fail_ akin to software developers who keep their code "closed source" out of fear when _opening_ your code creates orders of magnitude more value for you and the world!

We will be doing the "Living Wall Project" _after_ we complete the interior of the house. 
The _outside_ of the house does not need to look _incredible_ ***`before`*** we can open the house to friends/family/guests; this is very much a "Post MVP" enhancement which is why it's not even _mentioned_ in the main `README.md`! 

# Todo

+ [ ] Visit the Athenaeum Hotel in London to observe it _in-person_.
  https://www.athenaeumhotel.com/athenaeum-life/off-the-wall
+ [ ] Visit Rubens Hotel https://www.rubenshotel.com/about/the-living-wall
39 Buckingham Palace Road | Victoria, London SW1W 0PS 
https://www.google.com/maps?q=39+Buckingham+Palace+Road+%7C+Victoria,+London+SW1W+0PS
+ [ ] Visit 20 Fenchurch Street: http://www.biotecture.uk.com/portfolio/20-fenchurch-street/

![image](https://user-images.githubusercontent.com/194400/48312263-08cf4a00-e5a4-11e8-9f19-f8edfcbd3642.png)

![image](https://user-images.githubusercontent.com/194400/48312560-9876f780-e5a8-11e8-9378-25c4a667940b.png)

![image](https://user-images.githubusercontent.com/194400/48312563-a0cf3280-e5a8-11e8-9a0c-00d0390ce7bc.png)

![image](https://user-images.githubusercontent.com/194400/48312653-feb04a00-e5a9-11e8-9545-80a694189c06.png)

![image](https://user-images.githubusercontent.com/194400/48312585-f7d50780-e5a8-11e8-818f-7f7b21b431e6.png)

![image](https://user-images.githubusercontent.com/194400/48312662-230c2680-e5aa-11e8-86e9-1dcb5ed5a450.png)

![image](https://user-images.githubusercontent.com/194400/48312649-e2aca880-e5a9-11e8-832b-0fab888046bf.png)

If you _live_ in London and want to join us on our little field trip next week, please leave a comment below and we will be in touch to organise logistics. 💬

**Comment by iteles** [comment]
❤️ Love this.

Looks like any day next week is a good day. 

![image](https://user-images.githubusercontent.com/4185328/48312699-bc3b3d00-e5aa-11e8-9228-85b0ff62daf3.png)

**Comment by nelsonic** [comment]
@iteles I believe the photos for the visit were taken on your phone. 📷 
Please upload one (_or more_) when you can. 👍

**Comment by iteles** [comment]
![img_4119](https://user-images.githubusercontent.com/4185328/50573607-67a88700-0dcf-11e9-96a5-da7aa83e5a1a.jpg)
![img_4120](https://user-images.githubusercontent.com/4185328/50573608-68411d80-0dcf-11e9-8fda-82ba33fa12c2.jpg)
![img_4124](https://user-images.githubusercontent.com/4185328/50573609-68411d80-0dcf-11e9-9d6a-6ac2b26f27d7.jpg)
![img_4126](https://user-images.githubusercontent.com/4185328/50573611-68411d80-0dcf-11e9-8e69-a6155980d5b3.jpg)
![img_4127](https://user-images.githubusercontent.com/4185328/50573612-68411d80-0dcf-11e9-8300-cce96943c7b1.jpg)
![img_4133](https://user-images.githubusercontent.com/4185328/50573613-68d9b400-0dcf-11e9-8529-6c16a9fc1aec.jpg)
![img_4134](https://user-images.githubusercontent.com/4185328/50573614-68d9b400-0dcf-11e9-9f7e-f06b8bc6a6ac.jpg)
![img_4135](https://user-images.githubusercontent.com/4185328/50573615-68d9b400-0dcf-11e9-8905-34df8c1b54a8.jpg)
![img_4136](https://user-images.githubusercontent.com/4185328/50573616-68d9b400-0dcf-11e9-8e6c-843fae3ccb73.jpg)

**Comment by nelsonic** [comment]
@iteles thanks for uploading the photos.
Now you see why/how uploading images from a mobile phone requires the ability to rotate... 😉
