### ISSUE TITLE
Homebridge?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/home#233]
I'm considering installing `homebridge` on one of our Raspberry PIs to run some @home automations.
See:  https://homebridge.io

![image](https://user-images.githubusercontent.com/194400/235644955-0b3ff70d-7b1c-4fdf-b381-75918700b074.png)

https://github.com/homebridge/homebridge & https://github.com/homebridge/homebridge-raspbian-image

I have a few in mind but the basics are:
+ [ ] detecting windows/doors left open 
+ [ ] disabling the motion sensors on corridor lights after "bed time" because the lights are _way_ too bright. 
  > Don't worry, there will be "night lights" on the same control system so that people can still see where they are going!
+ [ ] View the security cameras and _specifically_ the doorbell on other devices (not just my iPhone)

## Pros

The pros of this are obvious: connecting "not yet supported" 

## My Chief concerns are:

+ [ ] How to secure the Pi both from **_internal_ access** and **_external_ threats**.
  > Is it _enough_ to lock down the Pi from a network perspective and put it in a locked cupboard?
+ [ ] What happens when "we" (@iteles and I) _leave_ @home and all the automations are tied to _our_ iCloud account(s)?
  > Should we setup a **`new`** iCloud Account that "owns" all the automations and figure out how to _share_ the access?

# Todo

+ [ ] ***Investigate*** the security & ownership concerns 
and 
  + [ ] ***open*** at least **_one_ question** for each on the **relevant forum**. 🔍 + ❓ 
+ [ ] ***Timebox*** setting up a RPi 4 with `homebridge` image. 
  + [ ] Use it connect to one of the IKEA sockets to turn on a light.
