### ISSUE TITLE
Chore: Move the Cloud Key to secure location?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/home#235]
At present the `Cloud Key` https://github.com/dwyl/home/issues/130#issuecomment-1117938928 is colocated with the `Switch` in the workshop:

![image](https://user-images.githubusercontent.com/194400/236616532-be404b1f-7044-4088-8f3b-eb4bc970f4ec.png)

> **Note**: this area is _definitely_ not yet finished! that mass of rolled-up network cables 
and the unfinished conduit section is far from "done".
This photo is just to illustrate where the `Cloud Key` is _currently_. 

While I plan to protect the `Switch` from tampering [TBD]
I still feel that having the `Cloud Key` (which has the hard drive where security cam recordings are stored) 
should be stored in a secure location so that if a malicious person were to reach the `Switch`,
they would not be able to rip out the `Cloud Key` which has recorded their shenanigans. 

# Todo

+ [ ] Check if there is an `RJ45 Port` we can use in the Attic. (`T5m`)
+ [ ] Determine what equipment we want to run (e.g. do we want a `4-port PoE Swtich` and `AP` next to it?
+ [ ] Plan the move and buy a compact _lockable_ box that we can affix to the wall.

> **Note**: I had originally planned to place these kinds of critical infrastructure components
in the "cellar" ... but sadly the humidity level is too high for running a hard drive. 💧 

Reason for having this as a `priority-1` is that there no point having security cameras if the hard drive recording the attempted entry is sitting in plain sight for the intruder to remove the evidence ... so getting this somewhere safe **ASAP** is a _very_ good idea ...

**Comment by iteles** [comment]
Yes, that makes perfect sense. Very much agree with this.

**Comment by nelsonic** [comment]
A Waterproof enclosure like this could work in the Cellar for protecting the HD from humidity? 💭 
https://www.aliexpress.com/item/1005003422416426.html
<img width="1452" alt="image" src="https://user-images.githubusercontent.com/194400/236617788-64f6c20f-9959-4aef-87f4-9380d804a131.png">
