### ISSUE TITLE
Pool Cleaning Tool/Pole Holder 🏊‍♂️

### ISSUE THREAD

**Issue by nelsonic** [dwyl/home#253]
# ⚠️ This issue contains “_first world problems_” … 🙃

> Top tip to anyone wanting financial security for themself or their family: build something the “1%” _love_ and sell it to a few of them for - what they perceive to be a “bargain” price and you will _never_ be short of cash! See: https://github.com/nelsonic/nelsonic.github.io/issues/747#issuecomment-1676256845

# Context

we have a pool. Love swimming. It’s good exercise. Kids love it. #Yolo #NoRegrets etc.
We have a bunch of cleaning tools on long poles and nowhere to store them so the end up laying around:

![IMG_7172](https://github.com/dwyl/learn-cad-cam-cnc/assets/194400/4601392b-a666-466b-88d1-567005b0f778)

# Need

what we need is some sort of storage rack for these tools so that the tools are:
a) well organised and not messy
b) easily accessible to adults
c) _not_ accessible to children who are often tempted to copy the adult and play with them which could be dangerous if they fall into the pool … 🙅‍♂️
d) away from the ficus plants so that we don’t drip salt water on them and kill them!
e) easy to make from commodity materials on our laser cutter

# Todo

+ [x] gather measurements (already did this in my paper notebook):

![IMG_7173](https://github.com/dwyl/learn-cad-cam-cnc/assets/194400/eb6c4382-ee8e-4963-b220-be09c8e91f44)

+ [x] create sketch in lightburn

+ [x] laser cut the parts

+ [x] Glue double-parts

+ [x] Paint

+ [x] Assemble parts into wall mount

+ [x] Varnish plywood exposed parts

+ [x] mount to the wall

I think I can get this done in **`T2h`** ... ⏳ 
The _reason_ I'm building something _custom_ is that I haven't found anything online. 🔍 🤷‍♂️ 
Let’s go!! 🚀

**Comment by iteles** [comment]
These look fantastic! And totally out of the way. I particularly enjoyed the photos of your little DIY buddy, he had the best time :heart: 

If we ever re-print for some reason: "Pass**e** o tempo a bombar"
