### ISSUE TITLE
Chore: Front Lawn Patchy -> Plant New Grass Plugs 🌱 

### ISSUE THREAD

**Issue by nelsonic** [dwyl/home#254]
Sadly, the type of grass that is planted on our front lawn is quite weak/wispy so we have ended up with patches:

![IMG_9933](https://github.com/dwyl/home/assets/194400/24207bc4-94dd-481e-a29d-0e22f62d475c)

We need to strategically plant “plugs” 🌱 of a stronger more hard-wearing grass in the “gaps” and allow the stronger grass to gradually take over.

this is a non-urgent aesthetic/cosmetic task but it bugs me every time I walk past so I’m opening the issue to at least capture it. 💭

# Todo

+ [ ] @iteles to ask Didi where they bought their hard-wearing grass. Specifically did they buy rolls or plugs and who did the planting. 

> If we can buy a tray of 24 plugs that would be enough to fix the whole front lawn. 
If we cannot discover a supplier of hard-wearing grass, we have a (hopefully) good alternative …

+ [ ] find or _buy_ seeder trays where we can plant grass seeds. 
+ [ ] buy germination compost 
+ [ ] Plant seeds and water generously. 
+ [ ] Monitor closely.

**Comment by nelsonic** [comment]
Sadly, we haven't prioritised this because our son uses the front garden as a "play area"
and he treats the lawn as his "digging area" ... no matter how much we tell him not to!

**Comment by nelsonic** [comment]
@iteles FYI: I’ve ordered 5 trays of Grass Plugs:

![Image](https://github.com/user-attachments/assets/403ce90c-2e51-4a29-b1ca-71efb17d353d)
![Image](https://github.com/user-attachments/assets/0071fd44-b03e-4b5b-bca8-1b57760e33d7)

![Image](https://github.com/user-attachments/assets/789aa50b-5c06-4f65-b9c5-755e78ca3c14)
![Image](https://github.com/user-attachments/assets/24cb59ea-6fa1-45c0-a883-93c38cd67ff3)

Should arrive early next week. 🤞🏼

Paid €29
