### ISSUE TITLE
Chore: Get TigerShark XL Pool Cleaning Robot Repaired/Serviced

### ISSUE THREAD

**Issue by nelsonic** [dwyl/home#255]
This morning while cleaning the pool I noticed that someone had broke the pool robot and not said anything… 😢

![IMG_1571](https://github.com/dwyl/home/assets/194400/2c24a9ed-74b5-47be-a3ea-9ffd6b45cc9a)
![IMG_1574](https://github.com/dwyl/home/assets/194400/5fa94570-cd6b-4bb1-89a9-c603b3fc45a7)
![IMG_1575](https://github.com/dwyl/home/assets/194400/7eec043a-babe-43ee-89df-dbe84930b9ed)
![IMG_1576](https://github.com/dwyl/home/assets/194400/7ec3624e-7ac2-41ae-a4fe-a39ac72758cb)

Clearly it has been dropped off the side of the pool because the side panel was off and the impeller is broken into pieces. This makes me _very_ sad. Another unforeseen expense/task …

# Todo

+ [ ] Research where we can take/send the machine for repairs & maintenance.
+ [ ] Book in the repair
+ [ ] Take the machine to the service centre
+ [ ] pony up the money 💰
+ [ ] Collect it once it’s fixed

@Stephanymtr would you mind researching where we can get this fixed? 🙏

we originally bought it at Leroy Merlin when there was an end-of-season sale. I think it’s out-of-warranty and there’s a newer model. If we can just:

A. Find the Manual for the exact product version we own.
B. Figure out which pieces we need to replace/renew.
C. Buy the pieces online or at Piscinas Ramos

I can *easily* repair it myself or we can ask Mr. Rios (your Papa) - the mega-experienced Mechanic - if he doesn’t mind helping … 💭

**Comment by Stephanymtr** [comment]
Sad to hear the pool cleaning robot broke. 😢 

- **When was the date of purchase ?**
I'm asking because if you go on this page: https://www.leroymerlin.pt/produtos/jardim/piscinas/tratamento-e-manutencao-de-piscinas/limpa-fundos-e-robots-de-piscinas/limpa-fundos-automatico-qp-tiger-shark-12758725.html?src=clk  <img width="928" alt="Screenshot 2023-10-03 at 10 26 13" src="https://github.com/dwyl/home/assets/91985721/4dfddfe7-57f4-44e5-8136-ce239fec86a8"> You will find there's a 3 year warranty. 
<img width="214" alt="Screenshot 2023-10-03 at 10 32 25" src="https://github.com/dwyl/home/assets/91985721/83806367-5972-44cd-a558-451c7271cf4f">


- **Is this QP the type robot you own ?** I didn't see a photo of the label above showing the model. Is the broken robot outside by the pool ? I can go outside and look for this info later as I'm currently holding a 😴 👶🏻.

-----
Manual I found:
- [Aspirador de pó robótico HAYWARD TigerShark Series](https://manuals.plus/m/24d530fa7459f7f48da661ef15f3eefdad20e804324e4b381ac665848cb0159e_optim.pdf) [pdf] Manual do proprietário
TigerShark, TigerShark QC, TigerShark 2, limpador robótico da série TigerShark, série TigerShark, limpador robótico

Only after checking the model number is when I'll be able to confirm the manual above is for the exact product version you own. If not, Hayward's products manuals can be found here: https://manuals.plus/pt/hayward/?expand_article=1

**Comment by nelsonic** [comment]
Indeed the 3-year Warrantee would be applicable if we could prove that the failure is due to materials ...

<img width="470" alt="image" src="https://github.com/dwyl/home/assets/194400/b8861196-f003-4cba-91e5-a29e0383c23a">

Sadly, I doubt they will fix it under warranty because it looks like it was manhandled. 🙄 
According to some reviewers, Leroy aren't very helpful with after sales for these robots:

<img width="796" alt="image" src="https://github.com/dwyl/home/assets/194400/e054a92e-3f7a-439f-88c4-b98bf67a0bb4">


Also saw those manuals when I opened the issue. (thanks for including the links) 🔗 
But didn't find one for the `XL` model ... 🤷‍♂️ 
Guessing the manual is _similar_ and the `XL` just has a higher capacity. 💭

**Comment by nelsonic** [comment]
Exact model number and serial:

![IMG_1763](https://github.com/dwyl/home/assets/194400/77489215-6e5b-4131-b77f-8338faf75b38)

Aquavac motor unit with confirmation of id:
![IMG_1762](https://github.com/dwyl/home/assets/194400/12ad76e1-f108-427d-a197-22f9e163eb9a)

rust on the shaft inside:
![IMG_1760](https://github.com/dwyl/home/assets/194400/551f516b-a749-4589-a782-be75220ecfb2)

Roller out:

https://github.com/dwyl/home/assets/194400/5d93d759-887d-4a2c-a40f-aad5a0c47389

Could you try calling Leroy Customer Service and explaining the situation? I think we’ve had it for less than 3 years. And the invoice is attached to @iteles Leroy account, which they can lookup using her phone number. 💭

**Comment by nelsonic** [comment]
Confirmed purchased July 2021. So just over 2 years ago and well within the 3 year warranty. 👌 

<img width="635" alt="image" src="https://github.com/dwyl/home/assets/194400/7fb5e851-0b9e-4568-a321-faec7e2bf5fa">

**Comment by nelsonic** [comment]
Someone is selling our _exact_ model for **`€275`** (the pump works but not roller motors):
https://www.olx.pt/d/anuncio/aspirador-piscina-tigershark-xl-para-peas-ou-reparar-IDHgNbO.html
<img width="1231" alt="image" src="https://github.com/dwyl/home/assets/194400/2d87b710-bc1b-4932-b791-7cc30fd51b9c">

If the repair is more than €200 I would consider buying this second hand one and attempting to salvage it for parts. 💭 
But our _first_ course of action is to attempt to get it fixed under warranty. 🤞

**Comment by Stephanymtr** [comment]
Cool! Let's try to use the 3 year warranty in your favor. I'm happy to call them for you, but my downtimes are during A2's naps. I would be to schedule it for a time you or Ines can stay with them for me to make that call 🙈

**Comment by Stephanymtr** [comment]
@nelsonic I called LM and the customer service agent explained to me this has to be done in person by bringing the product with the receipt to the shop where it was purchased. If you prefer, there is a "formulário de contacto" on their website that can be filled out, but the customer service agent did say the process will be a lot faster if you bring the robot the shop/assistência técnica. I asked her other questions, but her only response/instruction was to bring the product and receipt to the shop.

**Comment by nelsonic** [comment]
Ok, in which case, @iteles given that it’s your account do you want to try and dig out a receipt?🧾 
***or*** should I just head in there and hope that they can find it on the system? 🔍🤞🏼

**Comment by iteles** [comment]
@nelsonic Unfortunately the receipts in the app only go as far back as June 2022 😢

**Comment by nelsonic** [comment]
Will they have it on the system at the store? 🙏

**Comment by iteles** [comment]
You were at LM customer service today. Did you ask by any chance?

**Comment by nelsonic** [comment]
@iteles there are _twooo_ Leroy Merlin stores in Braga. 2️⃣ 
We went to the _construction_ one to attempt to get our cement mixer serviced. 🙃 
They have nothing to do with "consumer" products like pool robots ... 🙄 
Will try and visit the _consumer_ Leroy this week and go past the customer service. 🤞

**Comment by iteles** [comment]
Confirmed we can get the receipt from LM if we have the date and value of the purchase.
It was either on 28th or 29th July for €799.

Our only problem will be if we bought other things too but I'm going to speak to our accountants first to see the July 2021 receipts as it might just be in there.

**Comment by nelsonic** [comment]
@iteles are we just going to request the "segunda via" (second copy) of the invoice (fatura)?

**Comment by iteles** [comment]
Like I said in the comment, I'm going to ask the accountants _first_ because the segunda via may not be possible if we bought other things on the same receipt (they might not be able to find it).

**Comment by nelsonic** [comment]
@iteles sounds good. 🤞

**Comment by nelsonic** [comment]
Sadly this didn't happen and the warranty elapsed ⏳ 
so now we have a very expensive bunch of parts taking up space in our storage. 😢 
Closing. ✅
