### ISSUE TITLE
Contents insurance in Portugal :lock:

### ISSUE THREAD

**Issue by iteles** [dwyl/home#28]
We have big plans for `home` that allows everyone to learn, create and be joyful. 
This means some nice tools, equipment, furniture and lots and lots of books! 📚 

The practical side of this 🤓 is contents insurance, which I know nothing about in Portugal yet! 🇵🇹 

## Tasks
+ [ ] Research contents insurance providers
+ [ ] Create a list of common requirements across all of them (information required for quotes)
+ [ ] Apply for quotes
