### ISSUE TITLE
Map of Braga

### ISSUE THREAD

**Issue by nelsonic** [dwyl/home#293]
Having had a quite a few people stay @home this past summer 
I _wish_ we had a giant _paper_ map we could point people to on the wall
to explain where certain things are in the city & surrounding areas.
This is the first hit on Google for the search: "mapa de braga papel"
https://www.google.com/search?q=mapa+de+braga+papel

https://www.cm-braga.pt/archive/doc/Mapa_de_Braga.pdf
<img width="1128" alt="image" src="https://github.com/user-attachments/assets/c9825726-21c0-41d0-9890-dd59c6e22ecf">

https://www.cm-braga.pt/archive/doc/Guia_Percursos_de_Braga.pdf [47mb!]
<img width="1284" alt="image" src="https://github.com/user-attachments/assets/770f707c-7cc5-4673-93e5-e239a18a931d">

> **Note**: Saw this _artistic_ print: 
https://lusaprints.pt/loja/quadro-mapa-da-cidade-braga-em-portugal-estilo-classico-a-preto-e-branco-linhas-das-ruas-e-estradas-poster-com-moldura/
<img width="1359" alt="image" src="https://github.com/user-attachments/assets/715af396-8c67-4ab4-bb39-4e58a69fda08">
This is _not_ what we want at all. 🙅 
We want something _useful_ that people can use to find museums, parks, famous/good restaurants and other points of interest.

# Todo

+ [ ] Visit the Turist Information Centre in the City Centre next time we are walking that way.
+ [ ] Ask about _paper_ maps for visitors. Optionally mention we have an "Alojamento Local"
   and would like to have a few copies of paper maps with points of interest.
+ [ ] Ask if there is a high resolution PDF version
