### ISSUE TITLE
Laundry Room Storage System

### ISSUE THREAD

**Issue by nelsonic** [dwyl/home#311]
At present, the laundry room is a mess:  ( a case of `#EverythingEverywhereAllAtOnce` ... )

![laundry-mess-1](https://github.com/user-attachments/assets/8df0c8c7-2efb-412c-b1e5-0b203bd3132f)

All surfaces are _covered_ in products, which, `while` many _related_ to laundry are _not_ organised ...

There are duplicates and bulk-buys of products dumped on the shelf that was meant for the second machine:

![laundry-mess-2](https://github.com/user-attachments/assets/38f0e3f7-6844-4438-9ae3-bb444053d474)

And the shelf where "kitchen things" should be stored is a ***smorgasmess*** of products:

![laundry-mess-3](https://github.com/user-attachments/assets/b243e5bf-c36e-4f04-91a8-11fb89acc589)

The original shelf above the machines for the laundry products is not used
because it is too high up for our `1.5 m` Tall cleaning lady ...

![laundry-mess-4](https://github.com/user-attachments/assets/803e4215-aa11-4541-844d-0d260009bf79)

This is not a _system_ #113 anyone can follow it's _chaos_. 😕 
There is _nothing_ written down (_printed & laminated_) for how it should all work. 🤷‍♂️ 
Inês has to _verbally_ explain it to people how to do laundry. 🗣️ ⏳ 

Verbally explaining things is _fine_ if someone has _never_ done laundry before in their lives!
But if they have used a _different_ machine before, then the instructions are simple!

# Laundry Instructions (Outline)

1. This is the machine you should use.
2. The laundry detergent is stored in this place.
3. Use `X ml` of detergent for a large load, `Y ml` for a medium and `Z ml` for a small wash
4. Pour the detergent into this compartment
5. Place the laundry in the tub and close the door
6. Select the settings on the dial(s) / button(s)
7. Start the machine
8. Start a timer on your phone corresponding to the time displayed on the machine so you get your laundry as soon as it's done.
9. Hang your washing on the drying racks on veranda upstairs (yes, even if it's raining they will dry!)
10. Once your laundry is 100% dry (e.g. in summer when it dries in a few hours) or 90-95% dry (e.g. winter when it's cold), take off the line. ***`if`*** your laundry is not _fully_ dry, then use the drying machine. We don't use the dryer to dry from 100% wet to 0%, we _always_ hang the laundry on the line/rail first to extract _most_ of the moisture for _free_ before using the machine to remove the bulk of the moisture otherwise we are _wasting_ energy. 

> It might not _seem_ like a waste to use a couple of `kWs`  to dry laundry. 
> But multiply it by 3-4 loads a day (20 people in the house) and you're wasting ***`MEGAWATTS`** per year!!
> Our energy may be renewable but it's not "Free"! 
> And if we waste it, other customers can't use it and thus more coal/gas is burned!! 🔥 
> https://www.energysage.com/electricity/house-watts/how-many-watts-does-a-clothes-dryer-use/

# Todo

+ [x] Measure the available storage area
+ [x] Decide how to most effectively _use_ the area. 
+ [x] Build shelves that work with the depth available
+ [x] Mount them in place. 
  + [x] Linear Guide Rails: https://github.com/dwyl/workshop/issues/167 `#SideQuest` 👷 
+ [ ] Create a _hyper_ organised ***SYSTEM*** that _anyone_ can follow and _never_ have clutter/mess again!

**Comment by nelsonic** [comment]
Detailed/precise measurements captured with lasers ⚡️

![image](https://github.com/user-attachments/assets/755117ab-bc1d-49ea-931b-a916690f6bff)

**Comment by nelsonic** [comment]
Rail distance measured with laser:

![image](https://github.com/user-attachments/assets/a5aec29e-4b98-4752-8430-f008c438ea6c)

**Comment by nelsonic** [comment]
Busy building a prototype rail. 🧑‍🏭⏳

**Comment by nelsonic** [comment]
Can you see where it's going? 

![image](https://github.com/user-attachments/assets/f8b8faf2-1bed-42ad-8496-1439fbc9a1bd)

![image](https://github.com/user-attachments/assets/116f9125-1164-4b1c-bddf-cd7c403ca126)

![image](https://github.com/user-attachments/assets/3ffb8765-d712-4cf0-b62d-e24dc4d2fbee)

![image](https://github.com/user-attachments/assets/639167c2-c8ec-4b0f-ab8e-e9b198755a3c)

![image](https://github.com/user-attachments/assets/131cc2d3-3b65-4b7e-9ce0-375711012714)

We're about to have an *insane* amount of storage for all laundry & kitchen items! And _most_ importantly a *system* that _anyone_ can follow. 🤞🏼

**Comment by iteles** [comment]
Love it. This solves the problem so well!!
I'm surprised the walls will hold this much weight - even the steel rail let alone the wooden shelves and all the weight ontop.

**Comment by nelsonic** [comment]
We did detailed study of the walls before embarking on this adventure. 🕵️‍♂️🔍
Each rail can hold 200kg of products comfortably. The wall mount is good for 400kg. It's all carefully over engineered to withstand severe punishment from curious children.

#PleaseTest

**Comment by nelsonic** [comment]
For anyone following along, the rail is an IPN 80. It's 1960mm long and can hold 800kg in the center. We tested it by hanging from it. Not even the slightest flex. It's mounted using custom fabricated steel plates welded to each end and hardened steel screws in holes drilled into granite & brick walls. Again, over engineered. Zero concern of failure. 👌

**Comment by nelsonic** [comment]
Finished painting the yellow one:

![image](https://github.com/user-attachments/assets/e49205f6-a15b-4e37-995c-82da471e6d60)

It has carefully made-to-measure shelves to store specific kitchen items. Each shelf will have a clear label on it and it will be *immediately* obvious where everything is. 👌

Painted it in the office so that it's out-of-the way from the workshop and can dry without any dust. Paint is non-toxic water-based. 

Next I'm going to prepare the linear rail for the next 3 units as an epic batch. This will mean we can *finish* mounting them all faster. 🤞🏼

Very keen to get this *finished* so we can have *one* room in the house that is *hyper* organised. ⏳🙏

**Comment by nelsonic** [comment]
Going to make the tolerances on the runners *much* tighter now that I've tested the first one. 👌
Still welcome more testing from others... 🙏

![image](https://github.com/user-attachments/assets/1c7659ef-affc-4cc2-925b-f4fa9b4ffb0c)

**Comment by nelsonic** [comment]
Busy preparing the runner for the second rail which will be for the green storage box:

![IMG_4637](https://github.com/user-attachments/assets/c987df92-f2ec-46c8-bed1-ca94aba22951)

just going to well it up now before heading to bed so it’s ready to assemble tomorrow.

thanks @MikeRund for helping me to prepare the pieces. 👷‍♂️👌

**Comment by nelsonic** [comment]
Second storage unit is up! 🙌

![IMG_5197](https://github.com/user-attachments/assets/03bafa25-ea5e-4c54-8b17-ccc3d6fe45b7)

thanks to @MikeRund and @d4vcsj for help! 🙏

> **P.S:** Yes, the smoke detector was factored into the planning and the unit does not impair its functioning. Don’t worry. There’s a plan. 😉👌
https://youtu.be/NsUFBm1uENs 🏧

**Comment by nelsonic** [comment]
Yesterday evening after work, I made the runners for the third rail/box:

![IMG_5391](https://github.com/user-attachments/assets/37db2ba7-191c-4e29-81d9-ef6890babe38)
![IMG_5392](https://github.com/user-attachments/assets/aff93a78-3b0c-41f0-9d1b-ef159090260b)
![IMG_5393](https://github.com/user-attachments/assets/416c07d8-c100-49b4-8d7f-ae1bc3c69c76)

Today I’m going to di the 4th set:

![IMG_5424](https://github.com/user-attachments/assets/74b2ab4c-6785-4081-9a8d-9a9302b9268a)

I’ve been a *lot* more systematic with tolerances on these so the will glide better than previous iterations! 👌

still _comfortably_ on-track to get the last two storage units installed before @d4vcsj leaves on the 18th. ⏳🤞🏼🎄

**Comment by nelsonic** [comment]
Managed to get all the runner welding done this morning before work day started:

![IMG_5425](https://github.com/user-attachments/assets/6b946924-85ca-4548-bf2a-de0c249ca9f1)

this is *by far* the most difficult & time-consuming part of the project. 👌

**Comment by nelsonic** [comment]
Today I managed to prepare *all* the pieces for the next two rails:

![IMG_5458](https://github.com/user-attachments/assets/ce1af8e0-dc58-409f-80a7-bae0540901d6)

but when I try to go in the laundry to do measurements and draw markings on the walls in preparation for *installing* the next two rails, I see that the products have all been returned to the platform/shelf that we had carefully cleared on Tuesday in preparation for getting this work done … ⏳😢

![IMG_5459](https://github.com/user-attachments/assets/d605dc4e-816c-4598-9044-8ac77567978c)

@iteles there appears to have been a miscommunication somewhere along the line … 🤷‍♂️
Could we *please* not put *anything* in this area for the next *week* so I can get my work done in the extremely limited time I have available. 🙏🙏

**Comment by iteles** [comment]
You got it.

**Comment by nelsonic** [comment]
We finished installing the other two running storage units on Dec 17 2024:

![IMG_7977](https://github.com/user-attachments/assets/32998854-bf6c-455c-8a36-f1c1e161af75)

I just _spaced_ on updating this issue! 🤦‍♂️

@iteles could you please share some feedback so we can fix any snags and call this closed? 🙏

currently the storage units are not being used, there are still products in the area where the second washing machine needs to return to:

![IMG_7976](https://github.com/user-attachments/assets/b44aa04f-f1c7-4839-8c27-ca7e607aaa0e)

what can we do to _move_ all the products to their new _organised_ home? 💭

**Comment by iteles** [comment]
This was done whilst I was busy packing everything for the festive season away a few days later and we've only been back a handful of days (which have been busy) so I haven't had a huge amount of time to test everything. Certainly no time to pack anything away 🤷‍♀️ 

It looks really awesome and I'm so excited to have all this storage! 

## Constructive Feedback
1. **The yellow box is side-heavy which means the green and yellow boxes scrape against each other**.
This is only a problem because it makes them _way_ harder to pull out and of course with time will wear quite a bit.

<img width="585" alt="image" src="https://github.com/user-attachments/assets/16cfb8be-3285-47c8-981c-98d876b6270e" />

I originally thought it was because the yellow box was weighted too heavily on the back side because of all these bottles:
<img width="452" alt="image" src="https://github.com/user-attachments/assets/9378194f-1f95-4ee1-81f8-b792cf76bf58" />

But in actual fact I think it's because of the weight of the wooden structure on the front side which is pushing that side down and pushing the whole box back towards the green one. 
<img width="433" alt="image" src="https://github.com/user-attachments/assets/abeb628d-6750-4f1d-ad78-c682538b4db8" />

**I was surprised that the weight of all those heavy bottles wasn't enough to counter-act this weight on the front.** Adding more weight with products isn't really a great system though.

2. **The mechanisms aren't well-oiled yet and pulling out the boxes is very noisy for upstairs** and a little jumpy for the red box especially.

Just adding more of the oil used so far is not the solution though in the first couple of  days I noticed some oil stains on some of the clothes that were in the laundry room awaiting washing (agree, this is not the correct system anyway) and it turns out the oil was pooling on the rails and dripping:
<img width="1055" alt="image" src="https://github.com/user-attachments/assets/d88a09cf-5993-40c2-adc4-18a5f822486e" />

3. A minor point, **we should add some foam to the edge of the boxes that touches the wall**.
Even myself being the most interested party in being careful, found I didn't always judge the distance properly and sometimes the boxes hit the wall at the back pretty hard which will quickly cause unnecessary damage.

4. `wont-fix`: Worth noting that when the blue box is open, it largely covers the light. 
Given this is a windowless room, even in the daytime this means that products in this box can't be seen as easily. Not something to 'fix' but something for me to be aware of when deciding what to put in this box 👍

**Comment by nelsonic** [comment]
@iteles "very noisy" is _highly_ subjective. Did you **_measure_ it** with a **decibel meter**? We have one in the office. 🎤 
Crucially, did you **_measure_ it** from other rooms? How _often_ will the boxes be opened/moved per day? 🤷‍♂

**Comment by iteles** [comment]
I didn't measure with a decibel meter.

I packed everything away last night and labeled with masking tape temporarily whilst we figure out if these are the most useful spots for things. Will make permanent labels in a month. 

Using the green one for storage of things for the kids, a mix of:
- Trays and baskets which I always end up having to traipse up and down 3 floors for like 8 times per materials rotation
- Things that require the kitchen for usage: play dough making ingredients, food dyes, etc.

**Comment by nelsonic** [comment]
@iteles has the noise of sliding the storage unit been an issue? 
Any other feedback? Or can we close this now? Thanks.

**Comment by iteles** [comment]
It doesn't affect me and I try to never use it when the kids are asleep. I think this is just wonderful, thank you!!

The yellow box is still tipping but I don't think this is an issue for now as these are mostly for internal use and not guest use (aside from the one closest to the washing machine which is working like a dream.

**Comment by nelsonic** [comment]
**`DT`** uses the Laundry one multiple times a day (during nap times) and it's never been an issue.
the yellow one needs to be counter-weighted to straighten it out, please feel free to do it. 👌

**Comment by nelsonic** [comment]
A year later and the Laundry Room Storage System is still working like **color-coordinated clockwork**: 🕰️

![image](https://github.com/user-attachments/assets/992b3bbe-0a94-4c34-a926-ea4b9f6abbd6)

Every day use kitchen items like food storage bags, aluminium foil and baking paper are easily accessible in the yellow pull-out organiser:

![image](https://github.com/user-attachments/assets/dcfafebf-cde6-4178-b76d-fe95c605f2f0)

With the "spares" equally easily retrievable by fully-opening it:

![image](https://github.com/user-attachments/assets/0cab3c11-381c-453a-b484-d1d82d260c79)

The laundry detergents & specialty liquids are located in the **Blue** organiser:

![image](https://github.com/user-attachments/assets/be3d6287-8b6d-4d06-8d55-15ffde7ff9f9)

Sadly, this has lead to more stock-piling ... but if it means we can bulk-buy and save a few €'s without overflowing the available space, it's all good. 👌

A little bit of clutter creeping into the **Green** organiser:

![image](https://github.com/user-attachments/assets/7f18dbb2-1e2b-4743-82b3-449fe253b93e)

I would *much* rather these items were in "warm" storage, e.g: a SAMLA Box upstairs: https://github.com/dwyl/workshop/issues/214

Very keen to build more storage systems to continue organising.

> **Note**: there was a minor issue with the **Yellow** organiser getting stuck a few months back, but it was addressed by greasing the rail/runner and now slides smoothly again. I cannot find an **issue** on GitHub for that ... @iteles did you open one at the time? (Just useful for knowing when it was ...)
