### ISSUE TITLE
Which 3D Printer?

### ISSUE THREAD

**Issue by nelsonic** [dwyl/home#37]
# Context

We've designated a decent chunk of space @home as our workshop or ["maker space"](https://www.makerspaces.com/what-is-a-makerspace/).  👩‍🔬 
Our plan is to have a (_reasonably complete_) set of prototyping/fabrication tools 🔨 
that _anyone_ staying in the house can (_learn to safely_) use to create anything 💡 
from a basic 3D-printed replacement part to a product idea including electronics! :electron: 
In the near-term we are going to _use_ the 3D printer to manufacture the cases for our [IoT devices](https://github.com/dwyl/home/issues/8). 🌐 
(_this makes sense for our limited runs <20 where we expect tons of iteration ... more on that later_) 

We need to _invest_ in the _best_ 3D printer to suit our needs (_not the most expensive_).

# Todo

We need help/advice on: 

+ [ ] Which ***existing/available*** printer to buy?
(_we backed an "affordable" mass market 3D printer Kickstarter printer over a year ago_: https://github.com/nelsonic/nelsonic.github.io/issues/418#issuecomment-336930599 _and it has yet to materialise ..._ 🙄 
_so we are not considering any suggestions for "future products" ..._)

### Our criteria is:

+ [ ] Affordable **_Total_ Cost of Ownership**. We aren't interested in something superficially "cheap" which it then turns out has _super_ expensive consumables (_filament_), low durability and poor tech support.
  + [ ] **Low _Maintenance_**. (_because we are based in PT, getting parts shipped to us will take **weeks** ... we cannot afford for our 3D printer to be "offline" for that time. Does this **rule out** ["**SLA**"](https://youtu.be/Srl96IoeWJs) printers...?_ see: https://youtu.be/6BaRpF8h-Ko)
  + [ ] **_Medium_ Format**. The typical size of the printed parts we are going to make is about **200mm**<sup>3</sup>
We aren't going to be making human prosthetics or car parts (_yet!_), this should guide our spend limit ... 
  + [ ] **Affordable _Consumables_**. No Proprietary resins/filaments that have huge markup and low availability or take ages to ship and are never "in stock"!
+ [ ] **Durable Printed Parts**. While we will (_probably_) print a few toy pieces, we are mostly going to be using the printer for Product Design Prototypes which will need to be _field-tested_. The parts need to be _durable_ and withstand a beating! In my (_limited_) experience of 3D printed parts, they can be brittle compared to injection-moulded parts made with similar materials ... 
+ [ ] As **_Open source_** as _possible_. Both the hardware and controller software. This is (_really_) "nice-to-have". We would _prefer_ to (A) support people doing _open_ work and (B) be able to _contribute_ improvements if we are _able_ to. 
+ [ ] **Environmentally friendly** [filaments](https://all3dp.com/1/3d-printer-filament-types-3d-printing-3d-filament/). (_we know that printing "throw away" pieces using ABS/PLA isn't sustainable so we would **love** it if the 3D printer we buy **supports** eco-friendly e.g: recycle-able or biodegradable filaments see: https://www.aniwaa.com/eco-friendly-3d-filament  ..._)
+ [ ] **Good online support / community** for when we have questions or need help.
+ [ ] _Reasonably_ **Beginner Friendly**. Personally, I have only printed a _couple_ of things at https://www.imakr.com so I'm still a "Noob", but I'm not a "afraid" to [RTFM](https://en.wikipedia.org/wiki/RTFM). 

The "_budget_" I have in mind is reasonably _flexible_. 💭 
Having previously done a bit of [research](https://www.youtube.com/watch?v=Sqh3FM12KVg) into this, I feel that spending around **£3k** ($4k USD)
will get us something of pretty high quality. _Obviously_ if we can spend less that's _good_,
or if we can _justify_ spending more for faster/cheaper prints, better "future proofing" etc, we will.

# Help Wanted!

If you have experience with 3D printers (_i.e. you have **used** or **owned** one and printed a decent number of things_) _please_ share your insights. We are looking to order ours by the end of **February 2019** so that we can begin _using_ it to make parts!

@achingbrain I know you recently bought a 3D printer. Which one did you get? What was _your_ criteria?

**Comment by nelsonic** [comment]
Requested advice/help on HN: https://news.ycombinator.com/item?id=19061374 
(_not expecting anyone to reply ... but on the off-chance ..._)

**Comment by nelsonic** [comment]
The Peopoly Moai https://peopoly.net/products/moai looks _sick_! https://youtu.be/Srl96IoeWJs 
(_super high resolution (Laser SLA)! reasonably affordable resin and **fast**!_)
Tom's review: https://www.tomsguide.com/us/peopoly-moai-3d-printer,review-5338.html
suggests that it's _not_ for "beginners" 

https://www.imakr.com/dlpsla/1979-moai-sls-3d-printer.html
![image](https://user-images.githubusercontent.com/194400/52160958-1f260700-26b6-11e9-82f9-6050edace36e.png)

**Comment by nelsonic** [comment]
The "ASK HN" Question did not get a lot of attention. (_I suspect because I asked it on a Friday Night_!<sup>1</sup>)
But the comment it did get was _insightful_:
![image](https://user-images.githubusercontent.com/194400/52164298-126dd700-26e7-11e9-9bb6-e8035d2c9a27.png)

Don't buy a _high end_ (i.e. "_expensive_") 3D printer because people will be "afraid" to use it!

> Thankfully, we have already Backed/Ordered a pair of [Cubibot](https://github.com/nelsonic/nelsonic.github.io/issues/418#issuecomment-336912417) (_easy to use_) 3D printers on Kickstarter so people who are **`new`** to 3D printing or just want to print a low-res replacement "settlement" for the Catan board (_because Scott, the family monster Labrador eat it!_) can do so easily on the Cubibot.

I feel quite tempted by the Moai (Laser SLA) shared above. The quality is _sick_, it uses generic or specific ("_strong_") resin and there's a good online forum: https://peopoly.net/pages/support
[![image](https://user-images.githubusercontent.com/194400/52164468-b2c4fb00-26e9-11e9-960d-fa199a95cdd9.png)](https://youtu.be/NxVY28C3Cg8)
https://youtu.be/NxVY28C3Cg8

[![image](https://user-images.githubusercontent.com/194400/52164446-4ea23700-26e9-11e9-9bcf-b531dbe71678.png)](https://youtu.be/OoVvQids1DA)
https://youtu.be/OoVvQids1DA


<sup>1</sup>We need to scrape HN (_or find a "dump" of it_) to determine what the best day 
to post is when people will _read_, up-vote and _respond_ to questions.

**Comment by nelsonic** [comment]
The "Monoprice" the HN commenter refers to is: 
Pro: https://www.monoprice.com/product?p_id=15711
![image](https://user-images.githubusercontent.com/194400/52167838-4bbf3a80-2719-11e9-94c1-a82a0498837f.png)

Mini: https://www.monoprice.com/product?p_id=15365
![image](https://user-images.githubusercontent.com/194400/52167780-5e853f80-2718-11e9-8a1a-998621d199e0.png)

The _reason_ I'm _not_ ordering a Monoprice a comment on this video: https://youtu.be/rErgaoGGldY
![image](https://user-images.githubusercontent.com/194400/52176314-f3d01480-27a8-11e9-9159-4e7138cd6faf.png)
It might be PEBKAC but I get the feeling that in order to make the printer _cheap_,
they are compromising on quality ... I don't have _time_ for that.
Need to _invest_ up-front to not _waste_ my time with poor quality.

**Comment by achingbrain** [comment]
I have a [Mk3 Prusa i3](https://shop.prusa3d.com/en/3d-printers/180-original-prusa-i3-mk3-kit.html) PLA printer and the [Peopoly Moai](https://peopoly.net/products/moai) SLA printer you mention above.  Before that I had a [LittleRP](http://www.littlerp.com) but the guy who makes them seems to have thrown in the towel.

I chose the Prusa partly because it has [great reviews](https://all3dp.com/1/original-prusa-i3-mk3-review/) but also because it has loads of great features that other printers have copied and I think it's good to reward people for innovation.  I bought some [cheap filament](https://www.amazon.co.uk/gp/product/B01CEBIEIC) once the bundled reel ran out which was find but took a bit more dialling in than the Prusa produced stuff and also had a slightly lower melting point so was a little susceptible to [elephant foot](https://all3dp.com/2/elephant-s-foot-3d-printing-problem-easy-fixes/).

Since then I've bought their own-brand [Prusament](https://shop.prusa3d.com/en/42-prusament) filament which the Prusa version of [Slic3r](https://www.prusa3d.com/slic3r-prusa-edition/) has presets for and is priced pretty competitively with generic stuff from Amazon, though I found that 3 reels is the max you can order before the shipping cost gets too much.

The Moai like most resin printers is something you should get into forewarned with the knowledge that you're going to spend a very long time experimenting with calibration, settings, model supports, resins and vats etc.  You're also going to need either sympathetic/understanding housemates/significant others or better yet a garage or outbuilding to store the printer in as the resin smells bad.  Like, really bad.  It also gets everywhere so you'll need to put matts down around it, not have it anywhere near carpet and to keep a box of [nitrile rubber gloves](https://www.amazon.co.uk/Large-Black-Mamba-Nitrile-Gloves/dp/B00CSFV08G) handy (not latex as it's dissolved by the resin).  In short there will be a lot of faff, a lot of "test prints" and not much time producing actual viable prints - anything less than a [Form2](https://formlabs.com/3d-printers/form-2/) is very much at the hobbyist end of the spectrum.

Peopoly have their own support/gcode generation software called [Asura](http://wiki.peopoly.net/doku.php?id=moai:asura) which is based on [Cura](https://ultimaker.com/en/products/ultimaker-cura-software) - it has distortion correction for the laser which is really important for larger prints but at the moment it's Windows only.  A Mac version has been promised for the start of this year but no sign of it as of yet.

For durability, once the resin has cured it tends to be quite brittle so it's not really suitable for making parts that need to stand up to any sort of stress - these types of printers are more popular with dentists, model and jewellery makers who would then cast the pieces they make.  If you really want to make durable components, then the Prusa with PETG filament would be better as it makes much stronger bonds.

In terms of being environmentally friendly, resin printers are most definitely not.  PLA filament is biodegradable (in that it degrades under UV light, something to bear in mind if designing things to be used outdoors) but PETG generally isn't (you can get some PETG filament with additives that make it biodegradable but it's expensive and who knows what it'll do to the durability).

I'd certainly recommend the Prusa, and the Moai too as long as you're not put off by the above - for your budget you can afford both!

Wow this is long, sorry for the brain-dump.

**Comment by nelsonic** [comment]
@achingbrain that’s quite a brain-dump! I can see why it’s _aching_... 😉
I feel like I’ve gained a glimpse into your *years* of research, “test prints” and accumulated knowledge.

Thanks for the heads-up on the resin smell ... fumes? 🤔
We have a dedicated corner for the 3D printers in the garage/workshop.
Sounds like we might need to store it *outside* to avoid the smell. 

I/we have a lot to learn. 
Thank you! ❤️

**Comment by nelsonic** [comment]
# Anycubic Chiron (Larger Build Volume) i3 Printer
https://pt.aliexpress.com/store/product/ANYCUBIC-Chiron-3D-Impressora-Plus-Size-TFT-Auto-nivelamento-Titan-Kit-Impressora-de-Bico-Extrusora-Dupla/721071_32896071619.html

![image](https://user-images.githubusercontent.com/194400/52200775-87651c00-2861-11e9-8e07-48e2686eb817.png)

The reason this 3D printer is _tempting_ is because 
it has a larger build volume 400mm * 400mm * 450 mm
and heated bed which according to the review videos 
opens the possibilities for more _ambitious_ projects.

**Comment by nelsonic** [comment]
# Prusa Powder-coated Sheets Out-of-Stock!

https://shop.prusa3d.com/en/3d-printers/181-original-prusa-i3-mk3-3d-printer.html
Prusa have "_**temporarily disabled new orders** of printers with **powder-coated sheets** until all orders from long-waiting customers will be shipped_"
![image](https://user-images.githubusercontent.com/194400/52230655-e782af00-28af-11e9-9f31-8233af980fb7.png)

I feel that ordering an Original Prusa i3 MK3 _without_ the powder-coated sheet negates one of the _major_ benefits of the MK3 ... according to https://www.prusaprinters.org/autumn-update-powder-coated-sheets-prusament-slic3r-mmu2 there is quite a big backlog of orders ... 😞 

@achingbrain did you get the textured powder-coated PEI surface? 
Is it _that_ much better than the "_standard_" _smooth_ one? 
(_is it worth waiting to order for the powder coated PEI to be back in stock...? 
  or just order now with smooth?_)

**Comment by achingbrain** [comment]
The safety guy in that resin printer video is a bit paranoid.  You can touch the uncured resin but it's hard to get completely off your hands (use IPA first, then soap & water) so gloves are best, otherwise it gets everywhere - light switches, cupboard doors, mugs, water glasses, cutlery, you name it.  In that quantity it won't make you sick but it doesn't taste nice. Learnt that the hard way.

You can reuse gloves (though latex ones will start to get sticky as they dissolve) but obviously they'll have resin on them and it'll get on whatever you handle, so maybe that's what he means.

To dispose of IPA with uncured resin in it, no need to go to a specialist disposal place - just tip it into a ziplock bag and put it in the sun.  The uncured resin will solidify over a few hours or days (in the UK..), then you can pour the IPA through a sieve back into the cleaning vat for reuse and throw the now-cured resin in the bin.

IPA itself is water soluble so can go down the sink.  It is inflammable though and evaporates quickly so keep the lid on the bottle and away from anything that could ignite it and if pouring down the sink, flush it down with plenty of water.

It can also crack certain types of acrylic so if you drop resin on something made of perspex it's usually better to just wipe it off with a paper towel instead of using IPA.  Also learnt that one the hard way.

Other than that he's spot on.  The aluminium baking tray thing is a good idea, if you can find one big enough.

> Once I get good at using an FDM printer, I will consider "upgrading" to an SLA.

I don't think it's really a case of upgrading - whether you use one or the other depends on what you want to print - SLA/DLP typically has [much higher resolution](https://formlabs.com/blog/3d-printer-resolution-meaning/) than FDM so things like [Hero Forge](https://www.heroforge.com/) figures can't really be done well on an FDM printer - take a look at their [examples](https://www.heroforge.com/DigitalDownload/) for the difference.  Chunky mechanical parts are best on FDM though.

Most skills will transfer but there are some that don't - for example positioning models to minimise suction and adding supports to models destined for a DLP/SLA printer is a [bit of an art](https://support.formlabs.com/s/article/Model-Orientation?language=en_US), though it's completely learnable, it just involves failing a lot 😉 

The Moai group on Facebook is full of very helpful people who can help out with model rotation and support generation.

**Comment by nelsonic** [comment]
@achingbrain thanks for your patience and _detailed_ answers! 🎉 
What I meant by "upgrade" is in terms of quality (_resolution_) and _skill_. 
I feel like I'm going to need a _lot_ of time to get into SLA/DLP. (_I'm cool with "failing", just not right **now**_)
For the types of things I intend to print (_custom enclosures for Aduino + [Raspberry Pi Robots](https://github.com/dwyl/learn-raspberry-pi/issues/10#issuecomment-459744000)_),
I don't think we will _need_ the higher resolution of SLA for the time being. Just "standard" FDM |> ABS.
But when we do _need_ the bump in resolution/quality, the Moai will be _top_ of our list to consider. 

Thanks for confirming that you have the "standard" PEI surface for the i3 Mk3. Ordering that. 👍

**Comment by nelsonic** [comment]
@iteles similar question to https://github.com/dwyl/learn-raspberry-pi/issues/10#issuecomment-459929086 ... 
Given the March 2019 delivery estimate, should we get the 3D printer sent to @home or  Carca?

**Comment by nelsonic** [comment]
@achingbrain last question: what filament should we get _now_ with our i3 MK3? 
This is what I have in our "cart":
![image](https://user-images.githubusercontent.com/194400/52242631-178d7a80-28cf-11e9-8974-1af45f920d52.png)

We've added a 4 types of filament (_including the eye-watering "flexfill" @ €33,99 / 500g!_)
We feel this should be a good starting point. (_we know there are [cheaper](https://github.com/nelsonic/learn-3d-printing/issues/1) places to buy filament but want get the "official" stuff so to minimise the print failure rate in the beginning..._) 

## Is this "enough"? (_or should we order anything **`else`**_?)

**Comment by nelsonic** [comment]
Not to seem "_impatient_" but the sooner we place this order the sooner we will _receive_ it. ⏳ 
So I'm going to order what Alex recommended (the i3 MK3) and a few filaments. 🤞 

![image](https://user-images.githubusercontent.com/194400/52435887-d41f5000-2b0a-11e9-85fd-12e37667e86d.png)
Can't say I particularly _trust_ this page ... 🙄 
![image](https://user-images.githubusercontent.com/194400/52435899-d8e40400-2b0a-11e9-8490-a48820940122.png)

Visa verification using OTP is a _good_ sign:
![image](https://user-images.githubusercontent.com/194400/52436415-257c0f00-2b0c-11e9-9334-7f82a90440ca.png)

![image](https://user-images.githubusercontent.com/194400/52436421-2a40c300-2b0c-11e9-8f9a-3d0a9a4f692e.png)

Our order:
![image](https://user-images.githubusercontent.com/194400/52436550-7be94d80-2b0c-11e9-92c9-526f336e566f.png)

No indication on when it will be dispatched never mind delivered.
Just have to be _patient_ ...

![image](https://user-images.githubusercontent.com/194400/52436757-029e2a80-2b0d-11e9-8f51-93bfbe34e889.png)

**Comment by nelsonic** [comment]
Yesterday Josef Prusa announces the MK3S: 
https://www.prusaprinters.org/original-prusa-i3-mk3s-and-mmu2s-release-sl1-and-powder-coated-sheets-update/

It’s not a “major” upgrade but it’s improved a few things.
So, given that our order has not yet been dispatched, I contacted them to upgrade it.
The MK3S is the *same* price as the MK3 so I didn’t think it was *unreasonable* to request the upgrade.
Sure enough Radek sent us this email confirming the upgrade:
![c32845f9-e747-4467-b8cc-f8d61b807d8e](https://user-images.githubusercontent.com/194400/52880048-cf851800-3158-11e9-962b-0f88fba2357a.jpeg)
Refreshing to see people care about customers and able to make decisions.
Obviously if I didn’t *ask* I wouldn’t *get* it.
And it won’t affect the profitability of the sale.
There is *plenty* of margin in this transaction for Prusa.
But still, they didn’t *have* to update our order, they are being nice!
So I am *grateful* they did. ❤️
