### ISSUE TITLE
Handing in the projects at CMB - all the bureaucracy!

### ISSUE THREAD

**Issue by iteles** [dwyl/home#44]
I went to the town council to ask a few questions about handing this in and came away with a _lot_ more information than I bargained for. _Just as well_ because otherwise we would have had to wait to get the same feedback after we had already handed everything in but **man, is this a lot of bureaucracy!**

### Overall Requirements
+ We now need to change the name on the process from the previous name to our name
  + This in itself is a whole other ball game and needs a separate issue
+ For handing in the projects, each project needs:
  + Not just the plans but 4-7 supporting documents such as calculations etc which were not specified at all in the letter the town council sent originally 🤦‍♀️ 
  + Each document has to be digitally signed by the technician/architect who is accountable for it (using their ID card)
  + Each document must have the correct 3-4 letter prefix to the document name, as established in a long excel document from the town council
   + All projects much be handed in on a CD and cannot be emailed in (❗️) and named as required 

### Ensure these are in hard copy:
+ Requerimento to change the name
+ Requerimento for the project filing
+ Copy of CMB's original letter

## Tasks
+ [x] Change of name for process
  + [x] Fill out Requerimento to change the name
    + [x] Fill in everything I know how to fill in
    + [x] Fill in ARU (awaiting confirmation from architect)
  + [x] Gather documents for changing of name
    + [x] Notarised marriage certificate because of my own name change last year
    + [x] Documentos que confira legitimidade - awaiting confirmation from lawyer on exactly what is needed here
    + [x] "Certidão de registo predial" - Awaiting confirmation from lawyer that this is the same as the certidão permanente do registo predial which I have a copy of
    + [x] "Certidão de registo Comercial (Constituição de sociedade)" - Awaiting confirmation from lawyer this is not necessary
+ [x] Fill out Requerimento for the project filing
    + [x] Fill in everything I know how to fill in
    + [x] Fill in section on date of architecture approval and phase of construction -Awaiting confirmation from architect
+ [x] Gather documents for projects
+ [x] Organise documents into correct folders
+ [x] Ensure each document has the correct prefix
+ [x] Ensure each document has the correct name (ours and not previous process name)
+ [x] Ensure each document has been digitally signed by the relevant technician
+ [x] Print hard copy of requerimento & sign
~+ [ ] Scan up hard copy with wet signatures~
+ [x] Ensure requerimento docs are in CD folder
+ [x] Burn CD
+ [x] Compile and hand into town council!

## Second round of Tasks
Following a first response from the town council, the following need to be done for the additional projects demanded by the town council:
+ [x] **External works**: awaiting alterations from February to come in for review and agreement
  + [x] Review project when it comes in 
  + [x] Requested changes made and approved
+ [ ] **Stability project:**
  + [x] Get budget
  + [x] Agree work 
  + [x] Review project when it comes in
+ [ ] **Electromechanical project:**
  + [ ] Get budget
  + [x] Get information from pool people on machinery
  + [x] Agree work 
  + [x] Review project when it comes in
+ [x] **Gas project:**
  + [x] Get budget
  + [x] Agree work 
  + [x] Review project when it comes in 
  + [x] Requested changes made and approved
+ [x] **Water works**:
  + [x] Get budget
  + [x] Agree work 
  + [x] Review project when it comes in 
+ [x] Fill out new form for CMB (town council): https://www.cm-braga.pt/pt/0502/municipio/camara-municipal/apoio-ao-cidadao/requerimentos/item/item-1-8954/download (requerimento de junção de elementos)
+ [x] Confirm all projects are as per the form, print out form, sign and scan back up to digital
+ [x] Print out 2 'empty' copies of the form with just the key information filled out in case there is an error in how I have filled it out (can still sign new ones, scan them and burn the CD at the town council, but will have no access to a printer)
+ [x] Compile everything onto a CD (including scanned form)
+ [x] Hand in to town council

### Last couple of projects
As per https://github.com/ideaq/home/issues/44#issuecomment-495943654
+ [x] Print out requerimento (I had already fully prepped this for the engineer to hand in)
+ [x] Sign requerimento
+ [x] Scan signed requerimento
+ [x] Review all electromechanical project documents
+ [x] Prepare all electromechanical project documents for CD
+ [x] Prepare all stability project documents for CD
+ [x] Burn CD with requerimento

Spreadsheet to track all project statuses for handing in: https://docs.google.com/spreadsheets/d/1JTJSRixoEBSfxUrZE-9k4-w9IzYnSPXHXi8v6EZg0JA/edit#gid=726363784

**Comment by iteles** [comment]
Updates needed to forms for new certidão permanente, need to reprint and re-fill out.

**Comment by nelsonic** [comment]
Printer is setup in the kitchen. 🖨 👍

**Comment by nelsonic** [comment]
300Mb to run a printer ... 🤦‍♂️ 
![image](https://user-images.githubusercontent.com/194400/53057233-7691e880-34a6-11e9-830b-2fb1e85d8671.png)

**Comment by iteles** [comment]
We got everything back from the engineers and architects in time  _except_ the 'arranjos exteriores' but  when we handed them in at the town council, almost every document had an issue with it. 
However, we were able to hand in the forms to change the name from the previous owner's names to ours (which should hopefully avoid some confusion and lessen delays caused by unnecessary issues).

## Change of name on the process
We got this handed in, paid the requisite €10 for handing in paperwork and then got a letter earlier this week saying the process would be complete after we go to the town council to pay an additional €50.

## Handing in the projects themselves
I sent everyone requests for the necessary updates last week and have been actively chasing every day since 6-Mar-2019. 
Keeping track of status in https://docs.google.com/spreadsheets/d/1JTJSRixoEBSfxUrZE-9k4-w9IzYnSPXHXi8v6EZg0JA/edit#gid=726363784

Half of the engineers were complaining that they signed the documents (digitally) in  exactly the same way they sign for every other town council document, using the government's official signature app.  
I had to do some digging but it seems the Braga town council has special rules, displayed on: https://www.cm-braga.pt/pt/0101/municipio/camara-municipal/apoio-ao-cidadao/operacoes-urbanisticas

I have emailed all the engineers this morning with detailed instructions and some trouble-shooting for the signature portion of this.

**Comment by iteles** [comment]
Managed to get everything back (apart from 'arranjos exteriores') by last night.

We went to hand in all the documents this afternoon and there were still a few minor issues with the documents we already have to hand:
+ PAR & PAA - digital signature needs to be 'qualified' and is not
+ TRPE - needs to be in PDF/A format (currently only PDF)
+ DAP21 & ARC21 - need to be in PDF/A format and have 'qualified' digital signatures.
+ We also don't have the amended versions of the 'arranjos exteriores' yet which the architect assured me he would be looking at tonight (though I'm not holding my breath)

I spent the afternoon speaking to people, looking up information for them and emailing them and at the moment, we have everything correct except:
+ The DAP21 & ARC21 which are part of the 'Projecto de elctromecânica'
+ The arranjos exteriores project corrections

@nelsonic _Ideally_, I would like to give the engineers who are sorting out the electromechanical project until mid-morning to get the project to us because it's relatively likely they'll be able to (but I can confirm this with a phone call at 09h00). It's less likely we'll get the arranjos exteriores sorted by then, but we'll have to hand those in later. Would this be possible?

**Comment by nelsonic** [comment]
@iteles makes sense. 09:00 phone call. Visit CMB at 11:00 if the engineers send you the plans. 👍 📆

**Comment by iteles** [comment]
After 2 hours at the town council and much back and forth, scanning documents with my phone and re-burning CDs on the spot, we handed in the projects. 

All except the arranjos exteriores which is still not done (and some additional bits that will no doubt be necessary for the water works. These will need to be handed in with 
https://www.cm-braga.pt/pt/0502/municipio/camara-municipal/apoio-ao-cidadao/requerimentos/item/item-1-8954/download (requerimento de junção de elementos). A reminder that this needs to be wet signed, scanned and saved to the CD we hand in as a PDF/A as well. 

The CD needs the process number, NIF and name of the requerente written on it.

**Comment by iteles** [comment]
## On the two missing projects
+ **Arranjos exteriores**
  + I got an email from the architect working on this on Friday to say he had finished the other things he was working on (🙄) and was picking up our project again on Friday/Monday 1-Apr-2019. We'll see.
  + Still no budget provided for the work but I'm estimating in the region of €250 - €300+IVA
+ **Water and plumbing/drainage**
  + There were a number of supporting files missing from the projects we handed in so these have now been passed to yet another engineer to work on (José Dias) for €160+IVA
  + We got a call from him on Friday to say that the project plans that we already had (and handed in to the town council) from the Palhagua plumbers were missing a number of critical elements and in his experience, would not be approved by the council, so he was waiting for these to be fixed by Palhagua before he moved on with the rest of the documentation
  + Knowing that the Palhagua guy is a relative beginner at this and I was going to have to be an active middle-person between the two, I agreed with Eng. José Dias that he would instead take over the project plans and make any required alterations to the files himself next week
+ **I am hoping that  they are just omissions in the plans rather than actual problems with the system itself**
+ I have booked a meeting with Eng. José Dias at his earliest convenience (Tuesday 2-Apr-2019 at 11h00) at the site to try to get everything sorted asap (seeing as our plan was to lay the rest of the floor next week)

<hr/> 

I was just writing up the final bits of the readme for this process and noticed that the `requerimento` form changed (yesterday). Hoping this doesn't cause even more confusion at the town council 🙄

**Comment by iteles** [comment]
Had a meeting this morning at the site with the Engineer who will be taking over the water and drainage projects because he believes the project drawings are incorrect and will not be accepted by the town council.

He has since sent be a revised budget of €750 + IVA including a few things we don't need. I have explained this to him and expect a revised budget tomorrow.

**Comment by iteles** [comment]
## Update from Town Council
There are three exemption requests that were denied:
+ **Stability project:** I've requested a budget for this from one of our engineers, chased today
+ **Gas project:** Despite the fact that we don't have, have never had and don't want gas in the house, the town council is forcing us to submit a project _and do the work_ to have a 'gas ramal' installed, at least to the door of the house
  + Quote for project was €150+IVA provided today, I've told them to go ahead
+ **Electromechanical project:** I've requested a budget for this from one of our engineers, chased today

There was also a reminder that we also need to hand in the **External works project:** Chased again and got a text saying it would be done by the end of the week, but I've been told this 6 times already so I'll believe it when I see it.
_Note: We got a first draft of this 1 week after the originally agreed deadline and I sent back a list of corrections within 1 week (2 months ago)._

Deadline given by town council 29-Apr-2019.

**Comment by iteles** [comment]
Latest on the projects:
+ **Water projects**: Agreed this would be €250+IVA rather than €750; received first draft, to review today
+ **Stability project:** Should be an additional €100+IVA, _should be with us by Friday (26th)
+ **Gas project:** Quote is €150+IVA, chased for project today
+ **Electromechanical project:** Still awaiting budget
+ **External works:** Got an "I'll send it to you today" on the phone but this is the 4th one of those I've received so I'll believe it when I see it

Updated the top comment with this second round of tasks. Not apparent: the constant chasing of 5 different architects 🤦‍♀️

**Comment by iteles** [comment]
Updates:
+ **Water works**
  + We need to review the water projects at the building site to double check they're correct
  + I've put the text documents through a couple of different PDF/A validators (https://www.pdfen.com/pdf-a-validator) and they failed so I've asked the engineers to check the format
+ **Gas project**: 
  + A couple of validations failed so I've asked them to double-check
  + @nelsonic I'm happy with the positioning of the gas box that goes nowhere in the position they have suggested, are you?
![image](https://user-images.githubusercontent.com/4185328/56696595-33413980-66e4-11e9-9dcf-ac50719dd424.png)

**Comment by iteles** [comment]
Got another "Ainda hoje lhe mando isso" from arranjos exteriores guy.

**Comment by iteles** [comment]
Got a curt email back from the **gas project** saying they didn't think either change was necessary and had to contain myself. Requested the changes again.

Of course, no word from the **arranjos exteriores** guy.

**Comment by iteles** [comment]
Unbelievably, the **arranjos exteriores** guy replied to my email chaser today with the project alterations 🎉 I reviewed all 5 documents (this is a small project) and requested one tiny change  in the `memória descritiva` document from 'moradia unifamiliar' to 'moradia' (the same thing I requested from the gas project) but honestly, I'll hand them in as-is if it means we're not more delayed.

**Comment by iteles** [comment]
Will try to hand in whatever we have on Monday when we go to Braga :+1:
Anything left over, I will get the engineers to hand this in themselves, no sense in delaying further.

**Comment by iteles** [comment]
Handed in as many as we could on Monday 5th May, 2 to go which were _supposed_ to be handed in on Friday 10th May by our engineer but he missed the deadline and still hasn't handed them in 🤦‍♀

**Comment by iteles** [comment]
One of our engineers tried to hand in the projects on Friday 24-May-2019 but both projects required adjustments. 

I already have one of the two corrected and am waiting for the second. Rather than waiting for the engineer to go and hand the projects in, I'm just going to go and do it myself on Monday.

Updated top comment with hopefully final tasks:
![image](https://user-images.githubusercontent.com/4185328/58373962-bba63a80-7f2d-11e9-9e5b-61d093dbb41f.png)

**Comment by iteles** [comment]
We went to try to hand these last 2 projects in at the town council yesterday but both failed the format checks 🤦‍♀ 

I've written up a new form to leave for the engineer (the one we used yesterday had the date) and sent the contact details for our architects as they are failing the formats for the drawings specifically and our architects might be able to help.

**Comment by iteles** [comment]
Chased. Again. After I was told this would be done by Friday 31st May.

**Comment by iteles** [comment]
😂 This is the issue that just won't end 😂 

I was sent the documents that were missing yesterday and decided to just burn the CD and go to the town council myself with them to make sure this was handed in today rather than face any more delays.

So that one doesn't have to read the full context above:
+ I handed in all the original projects (apart from 'arranjos exteriores') and exemption requests on 20-Feb-2019
+ In early April we got a letter denying the exemption requests for 4 of the projects and asking for the arranjos exteriores project that was missing (5 projects total)
+ I handed in 3 of the 5 projects on 5-May-2019 because I didn't want to delay any further
+ Then engineer tried to hand in the final 2 projects on 24-May-2019 but they failed the format checks
+ I tried to hand in supposedly corrected documents on 27-May-2019 but they failed the format checks _again_ 
+ I tried to hand the final 2 projects in a third a final time today, 4-Jun-2019 and was told that **the process was complete and just awaiting a letter to be sent out to me** but that this was very strange because the 2 missing projects were important ones (estabilidade e electromecânica) and that I had to speak to the architect in charge at the town council 😱 

So now I have to go and speak to this architect on 6-Jun-2019 at 11h00  🤦‍♀

**Comment by iteles** [comment]
Architect said everything was fine and we should wait for a letter in the post.
