### ISSUE TITLE
Electrical epic - all the final tasks

### ISSUE THREAD

**Issue by iteles** [dwyl/home#45]
The next step for us is to get the electricians to come in and finalise _all_ of their work, so that we can go ahead and close up all of the final walls and get things finished!

All of the electrical outlets, lighting and switches have been installed in all of the areas of the house. 

![image](https://user-images.githubusercontent.com/4185328/52900972-19234080-31f5-11e9-89ee-a6abe16ba59f.png)

But there are lots of little details to be completed aside from the final and ideally we will collect them in one place (here) and open issues on them each when they need to be discussed.

## Final electricals list
+ [x] Finish hooking up shutters to motors
+ [ ] Install emergency bell for reduced mobility bathroom (this has to be done before the porcelain goes in)
+ [x] Update data cable location to be next to the new front door
+ [x] Kitchen electrical plan - review and correct the things that have been done incorrectly
+ [x] Attic electrical plan #34 **[wiring complete, must confirm exact locations _as_ walls go in]**
+ [ ] Purchase transformers for doors so that there is a sample for the electricians #46 
+ [x] Review ITED (telecommunications plan) & adjust
  + [x] Add coaxial cabling throughout 
+ [x] Review SCIE (fire safety plan) & adjust
+ [ ] Purchase signage for fire safety & install
+ [ ] Lighting throughout the house - picking & purchasing fixtures and fittings
  + [ ] Work areas
  + [ ] Sleeping areas
  + [ ] Communal/passage areas
  + [ ] Bathrooms
+ [x] Provide samples of the switches and plugs (in accordance with the samples we have already provided to electricians)
+ [ ] Install all switches and plugs
+ [ ] Exterior lighting
+ [ ] Install door transformers and close this area off with in a box
+ [ ] Bathroom electricals
+ [ ] Create light in entrance way.

**Comment by iteles** [comment]
## Open questions
+ The budget included "instalação de vídeo-porteiro Videx ou equivalente" - do we want to add this to the list to at least discuss with them? Having a pre-installation that we can then re-use in some way with our app and security system may not be a bad idea, it would just have to be the right kind
+ Lighting for the entryway - the entry balcony which we have now closed off has no light. I would suggest that we request that they put light in here
+ The budget includes the "instalação de uma sirene por piso, no interior e no exterior" - we should discuss this with Bernardo to see what he means

**Comment by nelsonic** [comment]
@iteles agreed. we should discuss the above with Bernardo (_as soon as he is available_) 👍

**Comment by iteles** [comment]
List sent to electrician, to be discussed at the building site tomorrow.

**Comment by iteles** [comment]
Out of date. New list to be created with our _new_ electricians when they start in early July.
