### ISSUE TITLE
Name? 💭💡 

### ISSUE THREAD

**Issue by nelsonic** [dwyl/home#51]
# "_What's in a name? That which we call a rose_ 🌹 <br /> _By any other word would smell as sweet;_" 🍬  <br /> ~ [_Bill S._](https://en.wikipedia.org/wiki/A_rose_by_any_other_name_would_smell_as_sweet)

Naming things is often the _most_ difficult part of the project. 
This is a _widely_ known fact in the tech community see: [martinfowler.com/bliki/TwoHardThings.html](https://martinfowler.com/bliki/TwoHardThings.html)

> _**Note**: We're not suggesting that naming **variables**, functions or "**Classes**" in a given project is difficult, that's **easy**; just give things descriptive names based on what they **do** so the **humans** can understand the code! And let the compiler/interpreter worry about shortening the names ...
Naming software **projects** where you want a **descriptive name** that **isn't** "**taken**"... that's **hard**!_)

You can have a super awesome project that has incredible innovation and creativity 
and if its' name is _off_ in any way (_e.g: bland, uninspiring or unmemorable_) or _worse_ "taken" by some other project that has more "_traction_", _most_ of the effort you made can be _wasted_. 😞
 
> Note: I'm not suggesting for a _moment_ that we are in the situation where the _name_ of the project, or the _lack_ of a good one for that matter, is affecting its' "success", just opening this issue to log that it's something we have thought about _extensively_ and not yet found a satisfactory _answer_ ... 💭  

The name "**home**" has been our ["working title"](https://en.wikipedia.org/wiki/Working_title) during development, a way of referring to the project _internally_. Most people have _not_ given a thought to the name, and that's a _good_ thing because we _don't_ want _naming_ to _distract_ anyone right now. However some members of the @dwyl community have voiced a _concern_ that "**home**" might not be a good "production" title. I see the point they are making; "**home**" is not exactly something we can _trademark_ and get "brand recognition" for ... 🙄 
At the same time, I get _frustrated_ when people are _dissatisfied_ with the name "home" but offer no suggestion of their own as an _alternative_. It's _easy_ to say something is "bad" (_or "not good" enough_) whereas it's _far_ more _constructive/helpful_ to offer a suggestion for _improvement_. Mostly, I feel that people don't know they _can_ make suggestions and that _all_ ideas are very much _welcome_! 

With that in mind, we are thinking of creating way of letting people _anonymously_ suggest names and _vote_ on the ones they like the most. Anonymous because we don't want it to be a personality contest where the _person_ gets the votes, rather we want each name to be evaluated on it's _own_ merits. 💡

# Todo

Create a form that allows people to:
+ [ ] 1. ***Suggest*** a Name Idea: 📝 
  + [ ] **Name***? Make a suggestion for a name. [max 20 characters?]
  + [ ] **Why***? Give the "***pitch***" for the name. i.e. "_**`home`**, because everyone already knows what it is_".
  + [ ] **Why _Not_**? If you can think of any counter-argument for the name suggestion.
    > This might not be immediately obvious to people, but as we learn from Adam Grant's book ["Originals"](https://www.youtube.com/watch?v=utIMVnutzAk), carefully considering and _dismantling_ people's "objections" _during_ your "_pitch_" is the best way of showing people that you have already thought through their "_it **won't work** because of xyz_" argument and you aren't oblivious to the "downside" of your idea(s).
    see: [https://github.com/dwyl/home/#why-it-will-never-work-risks-and-mitigation](https://github.com/dwyl/home/tree/e2cf80da78de6120a3e2e19129568c399c598b39#why-it-will-never-work-risks-and-mitigation)
    > I think it's _fair_ to _not_ **`require`** people to consider the "cons" or "common objections" of their name suggestion, so we will make this field ***optional***, but it's something _we_ have to think about. We need to apply a ["devil's advocate"](https://en.wikipedia.org/wiki/Devil%27s_advocate) to each name suggestion. 
For example: We need to _translate_ names into various languages to avoid rude words. 😕 
  + [ ] **_Any_ Other Details**. Are any of the TLDs available? e.g: all variants of home.com home.etc are "taken" and it would be _impossible_ to _trademark_ the word "home" in any capacity. 
+ [ ] 2. ***Vote*** on the suggestions ✅ 
  + [ ] We need to decide if it's **single candidate voting** ("_one person one vote for one name_", _i.e. the simplest approach to voting_) ***OR*** if we are going to allow people to state **_multiple_ preferences** in the order they prefer (_more complex but also more representative_)
  see: https://en.wikipedia.org/wiki/Instant-runoff_voting
  I have _many_ [thoughts](https://github.com/nelsonic/nelsonic.github.io/issues/504) on [voting systems](https://en.wikipedia.org/wiki/Electoral_system) and can discuss them at length, but I want to hear everyone _`else`'s_ thoughts on this, is it worth the _effort_ to record **_multiple_ preferences**?
  + [ ] When displaying the list of name suggestions for voting, the list order should be _randomised_ on each refresh to ensure that we are unbiased in the presentation. 
  + [ ] Should there be a _limit_ to the number of suggestions? (_or a deadline for submission_?)

Asking people to describe a _fault_ with their name suggestion is like the _infamous_ (_and somewhat redundant_) interview question: "_what is your **biggest weakness**_?"
People invariably attempt to give a quality ("_I'm too much of a perfectionist_") or if they are honest and say "_procrastination_" they try to "_spin_" it to sound like a quality, e.g: "_I spend too much time analysing a problem which means I only get started on the solution quite late. This has played in my favour when selecting technology because it means I benefit from all the latest advancements and don't have to refactor any of my code before it goes into production_" ... ⏳
In other words: they only do their work "_last minute_" before the deadline and it has "_worked_" for them.  
I may be going off topic a bit here and @tomfrankly has a [_several_](https://collegeinfogeek.com/pomorodo-technique/) [great](https://youtu.be/7DvftaHlZR0) [tips](https://collegeinfogeek.com/procrastination-eliminate-choices) and [videos](https://youtu.be/ilwork_mktE) on this [subject](https://youtu.be/YokGiK29k74). 
But the point is this: _thinking_ about things from a ["_Why NOT_?"](https://github.com/dwyl/learn-elm/issues/2) perspective is a great way to _question_ your _own_ reasoning for an idea and helping others to _overcome_ the ["FUD"](https://en.wikipedia.org/wiki/Fear,_uncertainty_and_doubt) they might have. 

Obviously we run the _risk_ of people making a suggestion and voting for "***HouseyMcHouseFace***" ... 😜 
So we may need to "reserve the right" to _not_ select the "winner" of the popular vote. 

# General Applicability of Voting System

One of the features we are going to need when fostering a _community_ is the ability to present a topic and collect the votes of the members in an effortless and reliable way. 
This might seem like a _simple_ problem to solve, up-voting has been done in online forums since the beginning of the internet. But it's not that simple, _especially_ if/when the stakes are high. 
How do we _prevent_ people from using email aliases to register multiple times and skew the vote?

Voting can be as simple as "_what food should we eat at our community meal_?" 🥗  
to "_should our country [exit](https://youtu.be/J1Yv24cM2os) a common market_?" 🙄 

Estonia is a _great_ leader in this area: https://www.zdnet.com/article/online-voting-now-estonia-teaches-the-world-a-lesson-in-electronic-elections 
Interested comments on security in HN thread: https://news.ycombinator.com/item?id=19352740

_Obvs_ we don't need to build anything _ultra_-secure for capturing votes for the potential name-change of @home ... but we should still be _curious_ about voting systems if we are going to use one in the _future_ for making democratic decisions. 

We don't need to consider _generalising_ our voting system yet ... but if we _do_ build something for this, we should at _least_ consider the potential _exploits_ an online voting system can subjected to.

Is there a viable Open Source tool we can use for this _without_ having to write _any_ code? 🤔

**Comment by nelsonic** [comment]
One of the suggested "statuses" for GitHub is: "Working from home" ...

![github-status-working-from-home](https://user-images.githubusercontent.com/194400/54885153-1dd0b980-4e71-11e9-9d5d-6d96743de124.png)

**Comment by nelsonic** [comment]
'member this documentary?
[![image](https://user-images.githubusercontent.com/194400/55974955-c019db00-5c80-11e9-9e92-2c9ca2836593.png)](https://youtu.be/jqxENMKaeCU?t=85)
https://youtu.be/jqxENMKaeCU?t=85

The documentary is a bit "slow" ... if you haven't watched it, consider speeding it up.
![image](https://user-images.githubusercontent.com/194400/55975771-9792e080-5c82-11e9-9e86-056837d6262b.png)

It's _nuts_ how not much has changed (_if anything the situation is worse_) since it was published in 2009!

![image](https://user-images.githubusercontent.com/194400/55975490-015eba80-5c82-11e9-86e7-3a7ba4a2ad38.png)
![image](https://user-images.githubusercontent.com/194400/55975551-25220080-5c82-11e9-8952-2030ab49e5c6.png)
![image](https://user-images.githubusercontent.com/194400/55975594-3cf98480-5c82-11e9-857f-d8a0df10e9f8.png)
![image](https://user-images.githubusercontent.com/194400/55975617-4aaf0a00-5c82-11e9-81ac-f5735d58f139.png)
![image](https://user-images.githubusercontent.com/194400/55975661-5f8b9d80-5c82-11e9-894f-159ef8330e7e.png)
![image](https://user-images.githubusercontent.com/194400/55975834-b6917280-5c82-11e9-9ede-b1661812ffb6.png)
![image](https://user-images.githubusercontent.com/194400/55975866-c741e880-5c82-11e9-8160-e7acdb18a14c.png)
![image](https://user-images.githubusercontent.com/194400/55975893-daed4f00-5c82-11e9-87e4-db62b9766c0f.png)
![image](https://user-images.githubusercontent.com/194400/55975924-ee001f00-5c82-11e9-9499-2ed8d0ec2082.png)
![image](https://user-images.githubusercontent.com/194400/55975947-fe17fe80-5c82-11e9-91ad-97273553737b.png)
![image](https://user-images.githubusercontent.com/194400/55976001-1720af80-5c83-11e9-84d7-f102f490bdd8.png)

> This number is _conservative_!
+ https://bigthink.com/surprising-science/certainty-human-driven-climate-change
+ https://bigthink.com/politics-current-affairs/climate-change-is-a-threat-multiplier
+ https://youtu.be/17aE91SBMoY

Note: (I'm) still 100% open to alternative/better names. 💭

**Comment by nelsonic** [comment]
Let's get this one out of the way: We're _definitely not_ calling it "***Housey McHouseFace***". 😉 

Some comedy _genius_ already did that: https://twitter.com/hashtag/houseymchouseface  🤦‍♂ 

![housey-mchouseface-high-res](https://user-images.githubusercontent.com/194400/76353077-03088680-6308-11ea-9764-8320f4f5c227.jpg)

If ever there were a lesson to be learned from letting random strangers on the internet [decide](https://en.wikipedia.org/wiki/RRS_Sir_David_Attenborough#Naming_poll) the name of your thing ... 🙄 What You Get When You Let the Internet Decide: https://www.nytimes.com/2016/03/22/world/europe/boaty-mcboatface-what-you-get-when-you-let-the-internet-decide.html 

> _For the record: I still laugh each time I think of them having to name the research vessel "**Boaty McBoatface**" ... I just think the joke has run it's course and the imitations are nowhere near as funny_

As this Reddit comment puts it: 👍 
![image](https://user-images.githubusercontent.com/194400/76352356-d0aa5980-6306-11ea-8d5d-e25d749a9fd8.png)
https://www.reddit.com/r/CasualUK/comments/9lcsx9/this_house_is_named_housey_mchouseface/
