### ISSUE TITLE
Kitchen No. 3: Wheelchair Accessible "Mini"

### ISSUE THREAD

**Issue by nelsonic** [dwyl/home#54]
Initial 3D Sketch for #52 the "mini" kitchen is designed to be wheelchair accessible.
![image](https://user-images.githubusercontent.com/194400/54496824-86f18380-48eb-11e9-83bd-c15c3917c6fc.png)

# Two Zone Induction Hob `MÖJLIG` 29 cm x 52 cm

https://www.ikea.com/pt/pt/catalog/products/30237138/
![image](https://user-images.githubusercontent.com/194400/54498395-a6de7280-48fe-11e9-8593-a9d428b26561.png)
![image](https://user-images.githubusercontent.com/194400/54498412-d68d7a80-48fe-11e9-92f1-86ebfa9e97d3.png)

# Inset sink `LÅNGUDDEN`

https://www.ikea.com/pt/pt/catalog/products/S59157391/
![image](https://user-images.githubusercontent.com/194400/54498866-068b4c80-4904-11e9-86c5-24cb22642600.png)

![image](https://user-images.githubusercontent.com/194400/54498812-81a03300-4903-11e9-9044-d862388c8123.png)

# Kitchen Mixer Tap with Pull-out Spout `ÄLMAREN`

https://www.ikea.com/pt/en/catalog/products/80341646/
![image](https://user-images.githubusercontent.com/194400/54498744-ab0c8f00-4902-11e9-81b6-6d6b4466fc88.png)

![image](https://user-images.githubusercontent.com/194400/54498790-44d43c00-4903-11e9-898b-b1ed024e1818.png)

This chopping board that fits neatly between the sink and hob:
https://www.ikea.com/gb/en/products/cookware/knives-chopping-boards/aptitlig-chopping-board-bamboo-art-60233426/
![image](https://user-images.githubusercontent.com/194400/54496768-003ca680-48eb-11e9-9ec8-1932c72b3b92.png)

I think we will standardise on these **_Bamboo_ chopping boards** as they are better for the environment 
than plastic and biodegrade-able when beyond their useful life. 
(_though I will probably periodically run them through a [thickness](https://youtu.be/xajPodZzDD4) [planer](https://youtu.be/aONpB1yOlpE) to extend their life_)

[![image](https://user-images.githubusercontent.com/194400/54497848-94ad0600-48f7-11e9-8244-444f3ee766d9.png)](https://youtu.be/-av6cz9upO0?t=250)
https://youtu.be/-av6cz9upO0?t=250 "_buy the best you can afford and take good care of it_" 👍 

# Todo

+ [ ] Add Extractor Fan #53 
+ [ ] Add Accessible Switch for Extractor Fan
+ [ ] Add Accessible Wall Socket

**Comment by nelsonic** [comment]
A slightly more expensive tap is the Hansgrohe Focus kitchen tap
https://www.amazon.co.uk/dp/B00FK3XNW4?aaxitk=ACkTSnIjagXmOY6Ea5j64w
![image](https://user-images.githubusercontent.com/194400/54520860-97dcdc00-4961-11e9-8936-70bf7297e1f0.png)
the IKEA `ÄLMAREN` above is €99 but has _mixed_ reviews if you go to the more _critical_ country websites (_IKEA does not translate reviews from their various country localisations_) e.g:
The US site which has the _most_ reviews: https://www.ikea.com/us/en/catalog/products/80341651
![image](https://user-images.githubusercontent.com/194400/54521451-dde66f80-4962-11e9-8187-81cf627fc8c1.png)
In _particular_ the "Drip, drip, drip" review:
![image](https://user-images.githubusercontent.com/194400/54521531-02424c00-4963-11e9-8d14-56c6b07b19c7.png)
I'm willing to take a "_risk_" on the IKEA tap on the basis that the store is 5 mins drive from @home and if for any reason it's not _perfect_ we have 365 days to return it. 
![image](https://user-images.githubusercontent.com/194400/54521697-5ea56b80-4963-11e9-80d4-06171915f3cc.png)

But if we find a Grohe, Hansgrohe or _similar_ quality (_reputable brand_) tap at a _reasonable_ price 
I would also consider "upgrading".

**Comment by iteles** [comment]
This is awesome! 🙌 
I definitely think we should open a separate issue on the taps but other than that, looks fantastic.

**Comment by nelsonic** [comment]
@iteles agree that the taps deserve their own issue. opened: https://github.com/dwyl/home/issues/57

**Comment by nelsonic** [comment]
@iteles the MR kitchen is ready for review please see the following screenshots:
![image](https://user-images.githubusercontent.com/194400/54560297-f0d85e80-49b9-11e9-8a57-a7346c643b0f.png)
![image](https://user-images.githubusercontent.com/194400/54560326-09487900-49ba-11e9-8726-1f3172cab5a9.png)
![image](https://user-images.githubusercontent.com/194400/54560364-1bc2b280-49ba-11e9-87db-790c39aa3ee0.png)

If you have time to visit my desk to review in Sketchup, please come over.

**Comment by nelsonic** [comment]
@iteles in the design above, the _purple_ switch is an _accessible_ mains cut off.
We weren't able to find any at our electrical supplier, so I was considering ordering this one:
https://www.ebay.co.uk/itm/292994559915
![image](https://user-images.githubusercontent.com/194400/57178397-3e743200-6e67-11e9-84ea-52ebd00ef602.png)

Should we order more than one (_e.g: for the other kitchen areas ...?_)

**Comment by iteles** [comment]
This latest design also means that we will want to change the placement of the current extractor fan piping from just above the refrigerators to above the window.

I have booked a meeting with our ventilation folks at the building site today to discuss 👍

**Comment by nelsonic** [comment]
@iteles you haven't answered my question regarding the Cooker switches ... 
So I've placed the order for one (to be delivered directly to the building site):
![image](https://user-images.githubusercontent.com/194400/58020866-51426400-7b01-11e9-92fa-99e5ce7cb165.png)
![image](https://user-images.githubusercontent.com/194400/58020883-5b646280-7b01-11e9-9068-d0e82fc570a7.png)

Will be good to get the ventilation locations sorted. 👍

**Comment by iteles** [comment]
Oops, my apologies. No, I don’t see a reason to order more than one, the only place that needs an ugly wall switch is this station. The other extractor fans will be switched on/off on the fan itself!

**Comment by nelsonic** [comment]
The IKEA 2-zone induction hob is _really_ overpriced at €249 ... and online reviews aren't great. 
By contrast this electriQ (_it doesn't matter what the brand is, it's not visible on the product_) is quite good:
https://www.appliancesdirect.co.uk/p/eiq30indp/electriq-eiq30indp-2-zone-induction-hob-hob
![image](https://user-images.githubusercontent.com/194400/72688157-7eb23800-3afc-11ea-92ca-e0c5de99c906.png)

FYI: I'm doing research for the accessible ("mini") kitchen because it's the _first_ one I intend to build. 👍

**Comment by nelsonic** [comment]
_Could_ we use the IKEA TILLREDA Portable induction hob for the accessible kitchen? 
https://www.ikea.com/gb/en/p/tillreda-portable-induction-hob-white-40331630
![image](https://user-images.githubusercontent.com/194400/72688194-b7521180-3afc-11ea-8c5c-15d92a316fe3.png)
It's pretty cheap and has good reviews. 💭 

https://www.ikea.com/pt/pt/p/tillreda-placa-inducao-portatil-branco-00331627/
![image](https://user-images.githubusercontent.com/194400/72688242-1dd72f80-3afd-11ea-9706-2337616908f7.png)

I think I can do a good job of _integrating_ it into the work surface and having a movable cover. 💡

**Comment by nelsonic** [comment]
_Could_ we use the IKEA TILLREDA Portable induction hob for the accessible kitchen? 
https://www.ikea.com/gb/en/p/tillreda-portable-induction-hob-white-40331630
![image](https://user-images.githubusercontent.com/194400/72688194-b7521180-3afc-11ea-8c5c-15d92a316fe3.png)
It's pretty cheap and has good reviews. 💭 

https://www.ikea.com/pt/pt/p/tillreda-placa-inducao-portatil-branco-00331627/
![image](https://user-images.githubusercontent.com/194400/72688242-1dd72f80-3afd-11ea-9706-2337616908f7.png)

I think I can do a good job of _integrating_ it into the work surface and having a movable cover. 💡

**Comment by iteles** [comment]
My initial instinct would be that it would be _preferable_ to have 2 hob spots rather than just one in case there are lots of people cooking at once (irrespective of mobility) but what we _can_ do it test it with one _before_ integrating it into the worktop. If we find one is plenty after 6 months, we'll integrate it, if not, then we can get a 2 spot  hob and integrate that instead :+1:

It is only 1cm wider than the 2 spot hob you had [originally accounted for](https://github.com/dwyl/home/issues/54#issue-421981749) in the designs, so it shouldn't throw things off too much. I'll get one whilst I'm in Ikea tomorrow night.

**Comment by nelsonic** [comment]
Indeed the width being similar was my reasoning for considering it. 👍 
The _much_ lower price and good reviews are attractive to me.
We could build the _whole_ accessible kitchen for less than €200 
(_including sink, tap, counter top and hob!_)

**Comment by nelsonic** [comment]
As researched/shared above, these are the kitchen products I am buying:
+ €45 TILLREDA induction hob
+ €62 LÅNGUDDEN 46 x 46 cm sink
+ €49 ÄLMAREN kitchen tap

**Comment by nelsonic** [comment]
https://consumer.healthday.com/encyclopedia/caregiving-9/home-healthcare-384/remodeling-for-wheelchair-access-part-4-kitchens-651018.html
![image](https://user-images.githubusercontent.com/194400/75497826-5fd97800-59bd-11ea-888b-700690eac958.png)

**Comment by nelsonic** [comment]
Newer Model of IKEA 2-zone induction hob (_slightly cheaper_):
https://www.ikea.com/pt/en/p/vaelbildad-induction-hob-black-ikea-300-black-20467592/
![image](https://user-images.githubusercontent.com/194400/95504519-c2a7de80-09a4-11eb-9f65-15ab1af17192.png)

**Comment by nelsonic** [comment]
Online layout planner with cutting list: https://kitchenplanner.ikea.com/pt/UI/Pages/VPUI.htm?Lang=en-PT

**Comment by nelsonic** [comment]
https://www.ikea.com/pt/en/p/tillreda-portable-induction-hob-2-zones-white-30497094/
![TILLREDA-ikea-2-zone-induction-hob](https://user-images.githubusercontent.com/194400/122689034-ddab3d80-d217-11eb-9e3b-dd1dfed85c2f.png)

**Comment by XelaAl** [comment]
My sister is currently looking for the same way out for our grandmother. I live far from her, so I can't help much, only financially. So, we decided to hire professionals. I looked through many companies, and Bath Fitter seems to be a good choice. But I'm glad that I've found this discussion. Thanks a lot for sharing your experience and great ideas, I appreciate it.
