### ISSUE TITLE
Install BTE and increase electrical power 

### ISSUE THREAD

**Issue by iteles** [dwyl/home#70]
We have had a huge saga to get a higher power supply so far with electrical projects taking months to be handed in, taking months to get a reply, requests upon requests and changes from 74 kVA to 54 kVA. It's been a whole thing.
https://github.com/ideaq/home/issues/25#issuecomment-447811886

However, things are moving on this front and on Monday we're meeting with both the electricians and our electrical engineer to determine a full list of tasks.

**Current estimates are that this will still take 2 months to complete.**

## Tasks
+ [x] Create official electrical plan
+ [x] Make request for feasibility of increased power supply
+ [x] Receive confirmation from EDP that this can be done
+ [x] Install BTE box at the entrance to the house
+ [x] Put in request for the connection to the EDP box
+ [x] Book appointment with EDP for engineers to come to verify the BTE box is in place (they will need to call us to arrange this)
+ [x] Visit from EDP engineers
+ [x] Request permission to occupy the 'public walkway' (ocupação da via pública) to do the work required to connect to the power box #84 
+ [x] Receive permission
+ [x] Implement connection from the BTE to the EDP power box
+ [x] Go through house and make list of final lights required #47
+ [x] Buy final lights/sensors 
+ [x] Confirm with the pool people that the electrical board is electrified and the lights are sorted for the pool
+ [x] Confirm with the engineer that he can finalise the plans - if he wants to review everything at the house with the electricians, this can be done from next Wednesday 4-Dec-2019 onwards
+ [x] Book time with electricians to get everything completed
+ [x] Engineer to complete electrical plans https://github.com/dwyl/home/issues/73
+ [x] Get paperwork together for an 'auto de entrega' to be handed in to EDP
+ [x] Survey and certification of electrical installation complete
+ [x] Receive proposed contract from EDP
+ [x] Accept contract from EDP
+ [x] Get connection hooked up
  + [x] Call EDP to understand whether ceasing our current contract will come with any charges (in which case we'll have to delay this whole process) - but there is a clause in our contract which allows the contract to terminate with 20 days notice if _both_ parties agree so I'm expecting this not to be a _problem_, just a delay.
  + [x] Book switching off of current supply 'desligação do contracto neste momento' for a day when our electricians can be present and far enough into the future that our new contract can be hooked up on the same day
  + [x] Call EDP Distribuição on 253005063 and speak to João Romão about getting the new connection hooked up on the same day (note: he is on holiday from 30-Aug to 4-Sep, next week) _and_ they can only book up to two weeks in advance
  + [x] Make sure electricians can be  present "para fazer a passagem do quadro electrico"
+ [ ] Confirm power increase
+ [ ] Look into possibility of switching electricity suppliers (e.g. [Gold Energy with 100% renewable energy](https://goldenergy.pt/energia-verde/))

**Comment by iteles** [comment]
EDP engineer came to the house today and confirmed everything was as it should be :+1:
Now we wait for the letter from EDP in order to ask for the license to occupy the public walkway in order to carry out the work.

**Comment by iteles** [comment]
Things have moved on a little and we finally got the permissions needed (see https://github.com/dwyl/home/issues/84). The connections have now been done.

Next steps updated in OP:
+ [ ] Go through house and make list of final lights required #47
+ [ ] Buy final lights/sensors 
+ [ ] Confirm with the pool people that the electrical board is electrified and the lights are sorted for the pool #90 
+ [ ] Confirm with the engineer that he can finalise the plans - if he wants to review everything at the house with the electricians, this can be done from next Wednesday 4-Dec-2019 onwards
+ [ ] Book time with electricians to get everything completed

**Comment by iteles** [comment]
The engineer has said that he wants the electricians to correct the plans and send them to him.

Booked with the electricians to go to the obra tomorrow morning to review everything and finalise the fittings of the final lights from #47.

**Comment by iteles** [comment]
The reviewed plan was sent to the engineer before Christmas but he now needs to review everything with the electricians on site again. 🙄 
Still trying to book another appointment for them both to get together (they're supposedly organising with each other but in reality, are not).

This is required before we can book our electrical certification visit.

**Comment by iteles** [comment]
The final review from the electricians has been handed into the engineer who says he will finish the plans by 15-Feb-2020.

Now the electricians need to come in and finish their electrical tasks. Ahead of this we need to do a quick test of all the electrical sockets in the house to ensure that they are aware of any issues before the final electrical check.

**Comment by iteles** [comment]
I chased the engineer for the project today and he said it was delayed. Now due 20-Feb-2020.

Meanwhile I called EDP to find out if we could get a temporary increase in power and they told us that we were maxed out until we put in the full request (which is exactly what this issue is for) so I'll keep chasing.

**Comment by iteles** [comment]
Two points from my phone calls today:
+ EDP has taken a lot of their systems offline following the [IT attack they suffered this week](https://www.publico.pt/2020/04/14/economia/noticia/edp-alvo-ataque-informatico-empresa-garante-nao-ha-falhas-fornecimento-energia-1912186) (no idea what kind) so the certification paperwork has yet to be filed although all paperwork has been with the certification engineer for 3 weeks 🙄 
  + In theory, the engineer was going to call our electricians to notify them of anything additional that needed to be done by Wednesday of this week, but no call was made. Fingers crossed this means that it's just a case of filing the paperwork now
+ I asked our electricians to get us keys to the BTE box so we could keep an eye on the electricity meter and consumption , he said he'd watch out for one for us - I'll add it to #108

**Comment by iteles** [comment]
EDP has now sent us a proposed contract for 43.3kVA.
https://drive.google.com/drive/u/0/folders/1DsqhruhgVNE_e_QpAJqtMtn-5GpD5mk-

I'll read it through and add any salient points here.

![image](https://user-images.githubusercontent.com/4185328/87807310-067cc300-c850-11ea-85eb-be6684510335.png)

**Comment by iteles** [comment]
I've reviewed the contract and there is a lot of boiler plate BS that we just can't avoid such as EDP won't be responsible for damages or losses incurred if they fail to supply electricity to us for one reason or another, if they fail to provide electricity we're still liable for the _fixed_ monthly costs we/they incur, any changes to the contract (on their part) which are not replied to within 20 days will automatically count as accepted.

There is a portion that is personal to us and that is the bit we can realistically question. 

## Things to be aware of
+ Proposed dates of power provision are from 28-Jul-2020 to 27-Jul-2021
+ This is a 12 month contract so we wouldn't be able to change suppliers up until that time (see last point in OP above)
+ If we want to stop the contract after 12 months, we have to provide notice in writing _60 days_ before the end of our contract
+ If we try to break out of the contract early, it's a 💣 to pay 💸 
+ 58.86% of EDP's energy last year came from renewable sources
  + Our personal bills show that 100% of our energy to date is from renewable sources

## Minor things to change/ask
+ [ ] Phone number and email address on page 1 are incorrect (they are our electricians') and need to be changed
+ [ ] Minor typo in address on page 1 and page 4
+ [ ] Na página 4 das Condições Particulares, prevê-se um consumo anual de 75,106kW - este número foi estimado com base no quê? (this makes a difference only if we want out of the contract early as we pay the difference between how much we've already consumed and this number - to date we're consuming less than 200kWh a month)
+ [ ] Não é explícito neste contracto o valor da Parcela Regulada, mencionada na página 5. Já tentamos procurar extensivamente no site www.erse.pt e não encontramos esta informação para a potência que pretendemos contratar. Podia-nos esclarecer este valor se faz favor?
+ [ ] Sendo que a página 5 refere-se a horas de ponta, cheia, vazio normal e super vazio, presupõe-se um regime no minimo (tri-horário](https://www.edp.pt/particulares/apoio-cliente/perguntas-frequentes/pt/contratos/novo-contrato/o-que-e-a-opcao-horaria-e-qual-a-melhor-para-mim/faq-4823)?
  + Quais são os horários tanto de verão como de inverno para estas horas?
  + Podemos optar por outras opções horárias?

A couple of things that _might_ be worth mentioning:
+ De acordo com o ponto 1.2 das Condições Gerais, o nível de tensão de fornecimento da energia eléctrica  devia ser especificado nas Condições Particulares, mas este não se encontra especificado nas mesmas. Existe apenas uma referência genérica às várias tensões nos Anexos 1 e 2. Deveria ser especificada?
+ No ponto 2.1 das Condições Gerais pedem que o Cliente notifique a EDP da não-renovação do contracto com **30 dias** de antecedência da data de renovação. Porque razão nos pedem para notificar a EDP com **60 dias** de antecedência nas Condições Particulares?

**Comment by iteles** [comment]
Apparently, the sales section of EDP is the only section that moves quickly and have replied to all questions I've posed in less than half a day ⚡ Our electricians have, however, confirmed that "the rest of EDP is like a house on fire" :+1: 😆 

Got to the bottom of the issues here:
+ The annual consumption figure is based on the fact that we have a BTE - this is fixed. This really only matters if we try to get out of the contract before the 12 month period (as they'll charge us for the consumption we haven't yet used up to that figure), so I say we leave it.
+ There are no options for BTEs with regards to schedules, we have to be on a tri-horário schedule, with the following hours:
![EDP-tri-horario-bte](https://user-images.githubusercontent.com/4185328/88165929-5bcd2180-cc0e-11ea-9b86-9ecffbfab4a1.png)
+ We have ascertained with 80% certainty that the daily fixed contractual value is:
0,0428 X o nº dias X a potência de 43,00 kVA = about €57 fixed monthly for a 31 day month

![Tarifas_BTE](https://user-images.githubusercontent.com/4185328/88166403-1f4df580-cc0f-11ea-99fd-50cc3066b840.PNG)

## Timelines
I would propose that we ask to sign the contract with a starting date of either **end of August or end of September** as our energy needs will likely be met by solar + not much additional power. Our current grid seems to support the laser cutter plus other essential systems just about.
![image](https://user-images.githubusercontent.com/4185328/88166740-a8fdc300-cc0f-11ea-935b-fa4293497f08.png)


@nelsonic What are your thoughts on delaying the contract start date to end of August or even September 2020?

**Comment by nelsonic** [comment]
@iteles given that we are getting by with our Solar quite well right now, I would advise that we de-prioritise this request.
I would delay it to Jan 2021 as we aren't going to have a "full house" until then as there's a _lot_ of other work to do.

**Comment by iteles** [comment]
I hadn't considered delaying it further than October 2020 but I also don't think I provided a clear reason as to why. As this is across multiple issues, let me pull them together here:

Delaying it past September/October will imply:
+ Potentially new electricity inspections (#14) because they are required to be relatively recent
+ We cannot finalise the configuration of the solar panel system until the higher potency has been established (see final tasks in https://github.com/dwyl/home/issues/20#issue-372416585)
+ We know that if we have 2 heaters on (roughly 2.5-3kW/h) and put on the kettle, it knocks out our power grid at our current low potência. In September/October, we will be running the laser cutter + a potent extraction system for quite a lot of the day so I would be concerned that we would be running up against tripped fuses all the time during this period until the end of the year
+ It has taken us over a year to get to this point, there is some concern that it'll take them another 3 months or more to pick the process up again if we drop it now
+ Also note: we currently pay a fixed €17.20 every month for our 10kVAs, this is expected to be a rise of less than €40 in monthly costs.

**Comment by nelsonic** [comment]
@iteles in which case **August**. I was only suggesting delaying because of the extra €40/month. 
But if there is a knock-on effect of delaying other things, then fair enough; August. 👍

**Comment by iteles** [comment]
:+1: Thanks, I've emailed!

**Comment by iteles** [comment]
They have come back to us with the amendments of typos and info we requested and a new start date of 25-Aug-2020.

However, in speaking about the 'fixed portion' to my uncle Tó on Friday (he who works with EDP on a semi-regular basis), he was pretty sure that this portion (or 'Parcela Regulada') did not work as had been described to us.

I will be calling EDP Comercial on Monday to confirm everything and seeing as our new proposal is valid until the 6-Aug-2020, we have enough time to get this in writing too, which I'll pursue before signing.
![image](https://user-images.githubusercontent.com/4185328/88476728-aa422f00-cf32-11ea-999c-fa5c3fb59a42.png)

**Comment by iteles** [comment]
I have managed to get them on the phone and they have confirmed our understanding (if we were to use _no_ electricity, we would pay at most the €57 for a 31 day month plus the consumption over and above this).

I am collecting the documentation needed and signing the contract.

**Comment by nelsonic** [comment]
@iteles paying €57/month for the _privilege_ of having the **`<option>`** to use their electricity seems like daylight robbery. 💸 
What is our baseline "connection" fee right now?

**Comment by iteles** [comment]
@nelsonic I think this comment has the answers you need: https://github.com/dwyl/home/issues/70#issuecomment-662409497

**Comment by nelsonic** [comment]
@iteles ah yes, the _last_ bullet point. I would have preferred that it was a little more prominent:

# Currently: €17.20/month 💵 

# Proposed: €57/month 💰 

# _Increase_: €40/month 💸

**Comment by iteles** [comment]
Fair. 
I have gathered all the documents required (identification, certidão permanente, etc). 

Given all the _remainder_ of the bullets in that comment on why we might not want to delay this further, what are your latest thoughts on signing (reminder: our _current_ proposal expires today).

**Comment by iteles** [comment]
All sent by 17h30 today. Awaiting connection in early September 2020.

**Comment by nelsonic** [comment]
@iteles when discussing the costs of the upgrade, maybe _lead_ with the **_massive_ reduction** in **_marginal_ cost**
 from €0.1544/kWh to €0.06057/kWh (_I don't see **any** mention of it in this thread ..._):

![edp-electricity-cost](https://user-images.githubusercontent.com/194400/89578884-c6937500-d82a-11ea-931d-e13b9ee54986.png)

# Break-even: `424 kWh` or `€82.68` / Month

A quick [break-even analysis](https://en.wikipedia.org/wiki/Break-even) visualising how the cost per kWh (unit) of electricity will be _substantially_ cheaper on the newer tariff is a compelling way to illustrate that the upgrade is a no-brainer **_above_ `424` kWh**:
![image](https://user-images.githubusercontent.com/194400/89585225-61914c80-d835-11ea-9dbc-4fc9ae5e0c24.png)

I made this table + graph in under 10 mins in Google Spreadsheets. It clearly shows the **Break-even** point at **`€82.68`** / month.
Edit: https://docs.google.com/spreadsheets/d/1tneDqPykTdnXkC3B1F3ZebmBLN9rqUVzvQtrWy5OmLo

# Recent _Monthly_ Consumption: `141 kWh`

Our most recent monthly electricity bill (July 2020) was **`141 kWh`**: 
![image](https://user-images.githubusercontent.com/194400/89584740-7de0b980-d834-11ea-9098-63b99ef16f38.png)
**Note**: we were away from the house for almost half of the month. (_Tadim and Lx_)
The highest consumption item was the water filtration system which was poorly configured. 🙄 

Given this analysis, and assuming average consumption of **15 kWh** units **per day** it makes sense to upgrade.
As soon as there is even *one* other person in the house using the AirCon during the day/night we will increase the consumption by 5 kWh/day or 150/month. It will be instructive to see how much the consumption increased with my parents staying in the house for a week. 

Once there are _multiple_ people living in the house, the upgrade to the higher fixed cost but _lower_ marginal cost tarrif
will be a no-brainer. 👍

**Comment by iteles** [comment]
As I discussed with you verbally, we have been told by multiple people that this cost estimate sounds dubious so I had not included it here  because I didn't feel we could 100% _rely_ on it to make our decision. I _did_ however mention this to you offline because I thought it _may_ be a factor. Thank you for writing it up.

**Comment by nelsonic** [comment]
@iteles the **`€0.06057/kWh`** is not far off the **`€0.0731/kWh`** I noted in my Telsa PowerWall Calculations in 2018: https://github.com/dwyl/home/issues/25#issuecomment-447811886

The fact is EDP _Commercial_ does not make all of their rates **`public`** because they don't compete on price.
EDP, like other ex-state monopolies, competes on "branding" and "lifestyle" (_whatever that means for a utility..._) 

If the _consumers_ paying **`€0.21/kWh`** knew what they charge for higher volume use there would be [_riots_](https://github.com/nelsonic/nelsonic.github.io/issues/733) in the streets!!

https://www.statista.com/statistics/418111/electricity-prices-for-households-in-portugal
![image](https://user-images.githubusercontent.com/194400/89613364-f3bb4400-d879-11ea-8599-1aa80234840b.png)
Again, the **_marginal_ cost** to EDP (_considering the majority of our power comes from Hydroelectric/Wind_) is near-zero.

But this is the same for _every_ **_near-zero_ marginal cost utility**. 
Think of how much we pay for the **_marginal_ gigabyte** of data on our [_unlimited_](https://github.com/dwyl/home/issues/107) Fibre Home Broadband ... 
It doesn't _cost_ the ISP anything extra for us to be "consuming" the data. So they don't _charge_ us anything.
But we pay more up-front. 

To be clear, I'm not suggesting that the MC _is **zero**_, rather it's **_near_ zero**. 
[![image](https://user-images.githubusercontent.com/194400/89614027-798bbf00-d87b-11ea-9d2b-387b2d416e2b.png)](https://youtu.be/5-iDUcETjvo)
We have to pay _some_ contribution towards the maintenance of the [Hydro Dam](https://en.wikipedia.org/wiki/Cani%C3%A7ada_Dam) and Transmission Lines / Distribution Network. The only question is: **How much is _fair_**?

**Comment by iteles** [comment]
We thought this saga was over. Not quite.

2 weeks ago I got the call to schedule in the power changeover and because they could only book dates until the end of August at the time, it was delayed until this week.

Today I got a call to book it in but after speaking for a little we discovered that actually we have to book to switch off our _current_ electricity contract and _then_ have this one switched on. Even though this is all done with the same company (EDP), they are two different sections of the same company (EDP Comercial and EDP Distribuição), so I have to make the calls rather than then.
Our _current_ EDP contract was automatically renewed for a year on 2-Nov-2019.

Apparently we _also_ have to have electricians here for the changeover and ours are on holiday until the 7th September.

So. New tasks:
+ [ ] Call EDP to understand whether ceasing our current contract will come with any charges (in which case we'll have to delay this whole process) - but there is a clause in our contract which allows the contract to terminate with 20 days notice if _both_ parties agree so I'm expecting this not to be a _problem_, just a delay.
+ [ ] Book switching off of current supply 'desligação do contracto neste momento' for a day when our electricians can be present and far enough into the future that our new contract can be hooked up on the same day
+ [ ] Call EDP Distribuição on 253005063 and speak to João Romão about getting the new connection hooked up on the same day (note: he is on holiday from 30-Aug to 4-Sep, next week) _and_ they can only book up to two weeks in advance
+ [ ] Make sure electricians can be  present "para fazer a passagem do quadro electrico"

**Comment by iteles** [comment]
Spent an hour on the phone with EDP last week and confirmed that there would be no cost to switching off our current contract.

Also requested the closure of the contract via the form on their website as they requested.
On Friday we received a 'new contract' for the _existing_ electrical potência. However, upon calling them again, I confirmed that the request to close the contract has been received but that the new contract was sent out automatically because it hasn't been booked yet.

They only book 2 weeks in advance so I have to call everyone (both EDP teams and our electricians) to confirm that it will happen on the 28th as planned.

**Comment by iteles** [comment]
Call received from EDP asking to change this to 13-Oct-2020 as they were carrying out systems upgrades and all teams would be busy until then 😳 

I have now confirmed that:
+ Original electricity contract will be switched off on 13-Oct-2020, within the 08h00-10h30 window
+ New electricity contract will be switched _on_ on 13-Oct-2020, booked for a 10h30 - 13h00 window
+ Electricians will be present during the 10h30-13h00 window on 13-Oct-2020

**Comment by iteles** [comment]
This was _done_ on the 13-Oct-2020 🎉 
Only took about a year and a half? 👍 

I'll check the next bill reflects this and we can tax the system and then we should be good to close this issue.

**Comment by nelsonic** [comment]
@iteles any follow-up required on this? 💭

**Comment by iteles** [comment]
All done and reflected in bills 👍

**Comment by nelsonic** [comment]
Sweet! 🍭 Thanks for confirming + closing. ✅
