### ISSUE TITLE
Installing the heat pumps

### ISSUE THREAD

**Issue by iteles** [dwyl/home#71]
We have two heat pumps to service all of the house's hot water needs.

We need to get them installed before the water supply throughout the house can be hooked up.

## Tasks

+ [x] Make a decision on if any additional finishings are required for the room
+ [x] Check light order to see if we have light fittings for this room already
+ [x] Install lockable door on heat pump room
+ [x] Book installation of heat pumps
+ [x] Determine whether we are actually having solar panels _just_ for the heat pumps or not https://github.com/ideaq/home/issues/20#issuecomment-475782390
+ [x] Install heat pumps

**Comment by iteles** [comment]
Booked installation of heat pumps for 5-June-2019 onwards (they'll start in the kitchen and work their way down).

**Comment by iteles** [comment]
After a bit of a non-starter (in early June they updated the extractor locations in the kitchen and fixed the downstairs shower but the heat pumps hadn't arrived yet, it seems that the 300L one has arrived but the 500L one hadn't yet. 
According to an update from today, the 500L heat pump should arrive this week.

**Comment by iteles** [comment]
These were successfully installed in mid-July and finalised at the end of July 2019.
They have been installed so that one heat pump can be used at a time (either the small or large one) or both together.

Photo mid-installation:
![image](https://user-images.githubusercontent.com/4185328/69956513-1a112e80-14f8-11ea-9564-66f03d0fd9a7.png)


They will need to be fully tested along with all the other plumbing and we will need to be taught how to properly use them but this is a separate issue.
