### ISSUE TITLE
Lighting plan for the house

### ISSUE THREAD

**Issue by iteles** [dwyl/home#73]
Following on from #47, our electricians have asked us to create a lighting plan for the house with the types of lights for each room marked on it.

## Tasks
+ [x] Print out latest electrical plan for main house
+ [x] Print out electrical plan for attic
+ [x] Check for LM lights order and digitise
+ [x] Rough on-paper drafts
+ [x] Check all lighting points in the house are the same as on the plans so as not to confuse electricians
+ [x] Get everything into a digital plans
+ [x] Print 
+ [x] Hand to electricians
+ [x] Confirm our lighting order from Leroy Merlin matches the plan!
+ [x] Add/return any items missing/over-ordered
+ [x] Electricians to update lighting plan and send to engineer
+ [x] Engineer to update the lighting plan

Adding `priority-3` because all of the lighting will sit atop the walls so these need to be painted _before_ the lighting can be installed and the lighting 'vistoria' and certificates (#70) can be done without the lights themselves being in place so it's not a bottleneck for that either.

**Comment by iteles** [comment]
Completed 28-Mar-2020 and uploaded to our google drive.
