### ISSUE TITLE
Back garden wall

### ISSUE THREAD

**Issue by iteles** [dwyl/home#74]
The back wall in the garden has a wall of ivy along half of it (seen below in the left hand side of the picture):

![image](https://user-images.githubusercontent.com/4185328/58905503-d2a11580-8701-11e9-83dd-53a6310a6901.png)

It's beautiful and has been around for years and years but we've received a letter from the town council to say that it's leaning too far into the public walkway and either we pare it back or they will pare it back for us (and charge us government contract prices for the privilege).
**Deadline: 7-Jun-2019**.

But when we came to look at it more closely, the _whole thing_ is leaning outside of the walls and is a mass of strong trunks that are impossible to push back into the property and prop up. Even the metal fence originally holding it up has been completely overcome and bent over:
![IMG_1018](https://user-images.githubusercontent.com/4185328/58909836-008b5780-870c-11e9-99a3-656eb0e467a5.JPG)

So we will have to cut down the majority of it so that we still give it a chance to survive without the council making a mess of it. We'll leave everything we can on the inside of the property so that we can coax them into growing within the bounds of the garden - they grow super quickly! We had a similar situation at the front of the house and in one year there are leaves standing 1 metre tall!

## Tasks
+ [x] Pare back as much as we have to (scheduled w.b. 3-Jun-2019)
+ [x] Build up that half of the wall to provide some privacy and a leaning spot for the barbeque area 🌶 ☀️ (scheduled w.b. 10-Jun-2019)
+ [x] Determine colour/finish of wall
+ [ ] Put wiring in place to guide the ivy

**Comment by iteles** [comment]
This was completed and the wall was fully built up for a little privacy. We realised once the ivy had been paired back that it was sorely needed!

The ivy will grow back easily 👍
