### ISSUE TITLE
Plants! (How to "grow" fresh air indoors)

### ISSUE THREAD

**Issue by nelsonic** [dwyl/home#8]
In _addition_ to having a "herb garden" in the kitchen and a _jungle_ outside,
we are going to have as _many_ of the following plants as we can _reasonably_ fit in the house:

+ [ ] **Areca Plam** (_Chrysalidocarpus lutescens AKA Dypsis lutescens_) https://en.wikipedia.org/wiki/Dypsis_lutescens
+ [ ] **Mother-in-law's Tongue**/**Snake Plant** (_Sansevieria trifasciata_) https://en.wikipedia.org/wiki/Sansevieria_trifasciata
+ [ ] **Money Plant** (_Epipremnum aureum_) https://en.wikipedia.org/wiki/Epipremnum_aureum
+ [ ] **Boston Fern** (_Nephrolepis Exaltata_) https://en.wikipedia.org/wiki/Nephrolepis_exaltata
+ [ ] **Peace Lilly** (_Spathiphyllum_) https://en.wikipedia.org/wiki/Spathiphyllum
+ [ ] **Gerbera Daisy** (_Gerbera jamesonii_) https://en.wikipedia.org/wiki/Gerbera_jamesonii
+ [ ] **Spider plant** (_Chlorophytum comosum_) https://en.wikipedia.org/wiki/Chlorophytum_comosum
+ [ ] **English Ivy** (_Hedera helix_) https://en.wikipedia.org/wiki/Hedera_helix

[![image](https://user-images.githubusercontent.com/194400/45092214-a756af00-b10c-11e8-9073-7bb29067ed50.png)](https://youtu.be/gmn7tjSNyAA)
https://youtu.be/gmn7tjSNyAA

[![image](https://user-images.githubusercontent.com/194400/45092688-24ceef00-b10e-11e8-96f1-a0f8d08d69a9.png)](https://youtu.be/lPNYdSZRSdg)
https://youtu.be/lPNYdSZRSdg

## Todo

+ [ ] Take the list of plants to our local plant nursery to see how many of them they have "in stock".
+ [ ] Check prices for different maturity/age of plants (_we would like more "established" plants but they will be correspondingly more expensive!_)
+ [ ] Buy plants!! (_budget: TBD!_)
  + [ ] Add _water resistant_ stickers https://www.averyproducts.com.au/water-resistant/outdoor-labels with following data: 
     + [ ] Common Name (_English_)
     + [ ] Latin/scientific Name
     + [ ] What it's "good for" e.g: oxygenates air at _night_! (_in the case of **Snake Plant**_)
     + [ ] Date of purchase (_or planting if available_)
     + [ ] QR Code linking the plant to our "plant health manager" web app.

With the QR code on the plant we can easily keep track of it's location and when it was last cleaned or taken outside for Sun.

> Please add plants to this list and ideas for how we can _implement_ this quest!

**Comment by iteles** [comment]
Love this so much.
I have a lot of articles on this saved already 🎉 

Have been looking to make the time to get into indoor plants for years ❤️

**Comment by nelsonic** [comment]
Further options of plants to consider in: 
https://news.ycombinator.com/item?id=18192328

**Comment by Cleop** [comment]
I recommend Lucky Bamboo for dark spaces:

**Comment by nelsonic** [comment]
@Cleop good shout on having _indoor_ Bamboo! 💡🌱 

"Pet" Bamboo plants are available at our local ("big box") garden/DIY store:
http://www.leroymerlin.pt/Site/Produtos/Jardim/Sementes-e-plantas/Plantas-e-arvores/Bonsais/15694560.aspx
![image](https://user-images.githubusercontent.com/194400/47251786-afef1480-d430-11e8-8df4-2c6c0bd8112b.png)

> Sadly our family-owned/run plant nursery does not have a website so we can't share a link/screenshot of the product from them. But I will _ask_ them next time we visit. 💬 
 
We have a plan for bamboo _outside_ (_as a "privacy screen"_):

![image](https://user-images.githubusercontent.com/194400/34457724-f1605872-edb1-11e7-954a-788b39eea52c.png)

and want to explore using Bamboo for ***vertical farming***: https://github.com/dwyl/learn-aquaponics/issues/22

**Comment by nelsonic** [comment]
Alpha testing 7 indoor plants on my desk 
(in our “while we’re waiting for the house to be ready” apartment...)
![cccadf29-3cc0-4948-b806-e1651dbff042](https://user-images.githubusercontent.com/194400/48924779-d54dc300-eeb3-11e8-83d1-28feb4be98fd.jpeg)
Dedicated grow light. ☀️
I’m pretty excited about having an abundance of plants in the house. 🙌

**Comment by Cleop** [comment]
@nelsonic - are you using a regular bulb for the light or have you bought one that is designed specifically for plant growing? (It's something I'm interested in but have not explored yet!)

**Comment by nelsonic** [comment]
@Cleop good question! (_worthy of a separate issue: https://github.com/dwyl/learn-aquaponics/issues ..._) 😉 

I did a heap of research into Grow Lights https://en.wikipedia.org/wiki/Grow_light a while back. 
(_long before I was as systematic about capturing/sharing my knowledge in public ..._ 🙄) 
and the main thing about using "artificial" lights to grow plants is having the wavelength of light necessary for the plants. 

I purchased a "basic" (IKEA RYET  LED bulb E27 600 lumen 5000K)  LED bulb with the appropriate "full spectrum" https://en.wikipedia.org/wiki/Full-spectrum_light of light which simulates day/sun light. ☀️ 
£6 for a 2-pack (£3 each) is "_reasonable_" for a retail store ... 💰 👍 
https://www.ikea.com/gb/en/products/lighting/light-bulbs-accessories/ryet-led-bulb-e27-600-lumen-globe-opal-white-art-10363279/
![image](https://user-images.githubusercontent.com/194400/49440810-9590b080-f7bc-11e8-9753-36f40f3bbd84.png)

IKEA also sell this (_overpriced_) LED Grow light _specifically_ for indoor plants:
https://www.ikea.com/gb/en/products/indoor-gardening/indoor-growing-cultivators/v%C3%A4xer-led-bulb-for-cultivation-par30-e27-art-60317483/
![image](https://user-images.githubusercontent.com/194400/49440879-ca9d0300-f7bc-11e8-8a00-d81154d8213a.png)

> obviously if you were doing this at any sort of scale you would buy the appropriate lights in bulk ...
In _commercial_ (_indoor / year-round_) growing they limit the wavelengths to only the two required for photosynthesis see: https://en.wikipedia.org/wiki/Photomorphogenesis
i.e. they don't "waste" energy producing the "full spectrum" of visible light.

![image](https://user-images.githubusercontent.com/194400/49440330-3ed6a700-f7bb-11e8-841f-376eb4b75232.png)

I have a few "commercial" grow lights which I used to grow **wheatgrass** "back in the day" ...
(_for anyone reading this, I grew **legal** plants with documented health benefits, not "weed"!_)

And I will be resuming _indoor_ growing under "lab conditions" in Braga with _full_ "open source data" for anyone around the world to analyse and learn from! 📈 📊 
I'm _excited_ that I will be using my _own_ data to create a "Machine Learning" tutorial... `#WatchThisSpace!`

**Comment by GrosSacASac** [comment]
Also keep in mind that sun-light is a natural signal for human body, it can impact falling asleep
https://en.wikipedia.org/wiki/Effects_of_blue_light_technology#Effects_of_blue_light_on_sleep_and_circadian_rhythm

For computer screens https://justgetflux.com/ can help lower blue lights, in latest microsoft and apple OSes it is now built-in see https://support.microsoft.com/en-us/help/4027563/windows-10-set-your-display-for-night-time, https://support.apple.com/en-us/HT207570

**Comment by Cleop** [comment]
Thanks @nelsonic for sharing all that. I looked a little into grow bulbs in the past but didn't know that ikea did them. Through experimentation I managed to revive one of my own houseplants in winter by putting it next to a lamp when it started dying. I had placed it by a south facing window but it was the regular lamp that seemed to bring back to good health. When I have a bit more room one day I would like to experiment more with these things! ✨ 🌱

**Comment by nelsonic** [comment]
https://youtu.be/ooMiIm8RItw

**Comment by nelsonic** [comment]
Low light house plants: https://youtu.be/VxdQp3s-7_o

**Comment by nelsonic** [comment]
For the exterior of the house, we need some sort of vine. 
Vines That Will Not Damage Brick Mortar: 
https://homeguides.sfgate.com/vines-not-damage-brick-mortar-33670.html
