### ISSUE TITLE
Door frames and skirting boards

### ISSUE THREAD

**Issue by iteles** [dwyl/home#81]
Following on from https://github.com/dwyl/home/issues/42, a few tasks required to get the door frames in place:

## Tasks
+ [ ] Attic | Put in all door frames
+ [ ] Attic | All skirting boards
+ [ ] Top floor | Initial skirting boards - put in as much of the skirting boards as possible inside the rooms without the last portion that touches the door frames
+ [ ] Top floor | Corridor skirting boards - _Dependency: full flooring laid & outer door frames have to be in so that these can butt up against them_
+ [ ] Top floor | Finish skirting boards in rooms - _Dependency: inner door frames have to be in so that these can butt up against them_
+ [ ] Top floor | Put in all bathroom door frames and doors
+ [ ] Top floor | Paint all existing door frames
+ [ ] Middle floor | Put in all bathroom door frames and doors
+ [ ] Middle floor | Put in all door frames (other than bathrooms)
+ [ ] Middle floor | Put in as much of the skirting boards as possible inside the rooms without the last portion that touches the door frames - _Dependency: flooring has to be completed (in turn dependent on electricals being completed #45_
+ [ ] Middle floor | Corridor skirting boards - _Dependency: full flooring laid & outer door frames have to be in so that these can butt up against them_
+ [ ] Middle floor | Finish skirting boards in rooms - _Dependency: inner door frames have to be in so that these can butt up against them_
+ [ ] Middle floor | Paint all existing door frames
+ [ ] Basement | Put in as much of the skirting boards as possible inside the rooms without the last portion that touches the door frames 
+ [ ] Basement | Put in as much of the skirting boards as possible in the corridor without the last portion that touches the door frames
+ [ ] Basement | Finish skirting boards in rooms - _Dependency: inner door frames have to be in so that these can butt up against them_
+ [ ] Basement | Finish skirting boards in corridor - _Dependency: outer door frames have to be in so that these can butt up against them_
+ [ ] Basement | Put in fire door
+ [ ] Basement | Put in reduced mobility door frame and sliding door
+ [ ] Basement | Put in bathroom door frames and doors
+ [ ] Basement | Paint existing door frames that are staying

**Comment by iteles** [comment]
Current open questions:
+ Timelines for the attic doorframes, skirting boards and doors?
+ Confirm there is white skirting board for the kitchen
+ When is the final coat of paint going on the door frames that are already in place?

All doors that are missing are scheduled to be completed on Friday 29th June. 
This means that next week, the carpenter can:
+ Put in the doors in the basement that are missing and _do not_ require electronic locking systems to be fitted on them  - These are the leisure room and the reduced mobility bathroom
  + Note: Middle floor doors cannot be fitted until there is a floor
+ Put in all of the _outer_ door frames (those facing the corridors)
  + Note: The inner door frames will wait until we have electronic strike locks to test wiring with.

**Comment by iteles** [comment]
Doors are ready but have yet to be picked up by our carpenter who is also confirming whether Sr. Fernando can come in to do the second-to-last coat of paint on all the painted door frames this week.

On the questions above:
+ The attic doorframes and skirting boards are supposedly ready but can't be put in until the floor is added to the attic
+ There is definitely white skirting board accounted for for the kitchen
+ There are two more coats of paint to go on the painted door frames - one in the next week or so and one once literally everything else is finished and in place.

**Comment by iteles** [comment]
🙄  Can't believe it's been so long since I opened this issue and it's still not quite done.

We've had the carpenter's assistant in the house for the last few days finishing this up and repainting ALL the door frames and the attic doors. Here is my current list of the final things to be done:
+ [ ] Basement: the door frame from the mini aircon leak needs a final coat of paint
+ [ ] Basement: I haven't checked the reduced mobility room yet
+ [ ] Basement: the actual door of the leisure room had a few dings which would ideally be fixed
+ [ ] Middle floor: Kitchen window shutter frame needs to be sanded and then painted
+ [ ] Middle floor: Dining room doorways need to be painted
+ [ ] Middle floor: Co-working room door frame connecting to the dining room needs to be painted
+ [ ] Upstairs: our current room + housemasters room doorframes need to be painted
+ [ ] Upstairs: bathroom ding in doorway to be touched up with paint (I dissuaded him from painting the whole door 🙄 )
+ [ ] Attic: missing a piece of the doorway in one of the rooms that needs to be put in by Chico (inside top of smallest room)
+ [ ] Attic: 2 doors and 2 doorways still to be painted
+ [ ] ALL the floors need to be reviewed with a fine tooth comb and cleaned for paint stains (not just the obvious ones but the light ones that are a barely perceptible smudge too)

### @nelsonic Two questions:
1. The skirting boards also all have the same system of having been nailed in place which is usually fine, but on the way up the stairs to the attic, you're faced with a skirting board **at eye level** (🤷‍♀️ ) . I think this skirting board _has_ to have the nail holes sorted and has to be painted. Would you agree? And if so, paint the _whole_ skirting board or just until the railing we will have to put there? I reckon the whole thing.
2. The doorway board of the room we are currently using is loose again. We:
  a) Need a better solution for this panel - I don't understand why no wood glue was used; and 
  b) Need to determine whether we need to be concerned about the _other_ door panels coming off with use 😕

**Comment by nelsonic** [comment]
@iteles agreed that we want the eye-level skirting board to be tidied up. (whole thing) 👍 
Glue should have been used for all the panels. 🙄 (if it's coming off, we should use glue when it's re-attached)
As for the _type_ of glue we have a number of options. I would think that the adhesion of Tile mounting glue would be "OK":
https://www.leroymerlin.pt/Produtos/Tintas-e-drogaria/Colas-e-fitas-adesivas/Montagem/WPR_REF_82010796
![image](https://user-images.githubusercontent.com/194400/100878947-b9b62380-34a2-11eb-8508-9f00883c86d0.png)

But might be best to check with Carlos (Pinheiro) or similar experienced person. 💭
