### ISSUE TITLE
Kitchen: Plumbed Filtered Water and ICE Dispensing Fridge

### ISSUE THREAD

**Issue by nelsonic** [dwyl/home#82]
Measurements for the area where the "drinks" fridge will stand:

+ Width 830mm
+ Depth 793mm

# Requirements

+ [x] Use the available space as effectively as possible.
+ [x] Additional low maintenance high value-add (_nice-to-have_) features:
  + [x] Plumbed Ice maker/dispenser (_so that nobody has to think about re-filling ice trays_)

# Todo

+ [x] Research fridges which can fit in the space available.
+ [x] Order fridge
+ [ ] Call Worten for Credit/Refund ***or*** 
  + [ ] order alternative model: https://www.worten.pt/grandes-eletrodomesticos/frigorificos/frigorificos-americanos?sort_by=price&order_by=asc&dispensador=Gelo [see below]

**Comment by nelsonic** [comment]
If this was a "money no object" decision, I would suggest getting a Fisher & Paykel RF521TLPX6
https://www.johnlewis.com/fisher-paykel-rf521tlpx6-freestanding-fridge-freezer-a-energy-rating-80cm-wide-stainless-steel/p3063730
![image](https://user-images.githubusercontent.com/194400/60381694-e285ee00-9a50-11e9-9faf-5a76056e7206.png)

***or*** Fisher Paykel RF522BRPUX6 which has the _integrated_ (_plumbed_) Ice Maker 😮 
https://www.johnlewis.com/fisher-paykel-rf522brpux6-fridge-freezer-a-energy-rating-80cm-wide-stainless-steel/p3097403
![image](https://user-images.githubusercontent.com/194400/60381748-9c7d5a00-9a51-11e9-8ede-1363a0ad63a9.png)


Slightly cheaper from Appliance City £1429 - £100 (rebate) = **£1329** 
https://www.appliancecity.co.uk/refrigeration/fridge-freezers/freestanding-fridge-freezers/fisher-paykel-rf522brpux6-79cm-designer-fridge-freezer-ice-water
![image](https://user-images.githubusercontent.com/194400/60381701-eca7ec80-9a50-11e9-8d47-a9c005d40aea.png)

This _feels_ like a _lot_ to spend on a Fridge when there are cheaper options ...
Further research required ... 

@iteles should we take a measuring tape and visit the electrical stores?
(_or are we going to factor in the **time** for researching...? and just buy the best one immediately_)

**Comment by iteles** [comment]
@nelsonic You've called this a 'drinks fridge'. 

What are the actual requirements for this fridge? Is it just a plumbed/cold water system on the door? Or does it go deeper than that?

I feel that with a full house, we'll need this as food fridge space (we could make it a fresh fruit and vegetable only fridge for example).

**Comment by nelsonic** [comment]
@iteles the idea since the beginning was to have a fridge in the alcove, and given that the alcove fridge is the most "accessible" to the main co-working room, we figured that it would be the best place to store healthy drinks (_e.g: matcha lattes, iced tea, green smoothies, raw soup, juices, etc..._).
The _whole_ idea is that it's a _separate_ fridge for liquids so that when the fridge is opened it does not bombard people with meals/snacks and other "heavy" distractions.

I've updated the requirements above. I don't think that the fridge should dispense water because the "button" to activate it will get broken from excessive use (_unless it's a super sturdy fridge/mech..._). 
I'm _much_ more of a fan of the idea of having filtered water out of the main Kitchen Tap https://github.com/dwyl/home/issues/57#issuecomment-502472712 because it will be more robust and easier to change filters.

Having a **_plumbed_ ice-maker** would be a "nice to have" bonus feature that would mean we would always have ice and never have to _manually_ re-fill an ice tray. 

As for mixing uses for _this_ fridge, I _agree_ that we could use the "crisper" (drawers) for fruit.
But we _really_ need to avoid having "food" in the "quick access" fridge otherwise it will _always_ be over-stuffed with half-empty unlabelled Tupperware and [**_chaos_ is _garanteed_**](https://en.wikipedia.org/wiki/Second_law_of_thermodynamics).  

It's quite simple, if we don't have a _dedicated_ liquids fridge that I can use to avoid _seeing_ food in the morning (_or when I'm doing a liquid-only day_) in the kitchen I will buy a _personal_ one for the garage. 👍

**Comment by iteles** [comment]
I have previously raised the following concerns:
+ The _noise_ - that ice dispenser makes a _racket_ every time it's in use and we're going to have a hard time blocking the noise from the working room.
+ The levers are not super strong and as mentioned above, there are concerns they will break.


Things have moved on slightly since this issue was last updated, with the main changes being:
+ We have decided to trial a plumbed fridge because we think that the endless ice is a wonderful luxury that fits with what we're hoping to achieve with @home and because we trust people to be gentle with it!
+ The alcove where we _intended_ to place the 'drinks fridge' was made considerably thinner through the construction work that had to be done in the kitchen and there are now no _plumbed_ fridges that fit within the 80cm space left.

The implication here is that the _plumbed fridge_ will now move to the corner of the kitchen where the previous fridges were kept and one of the existing fridges #80 will move to the alcove instead.
Whilst the UX is slightly less intuitive, this is actually _positive_ in that the fridge will be further from the coworking space which will help to dampen the noise level as well.

# Fridge options
As mentioned, there are no _plumbed_ fridges that fit within the 80cm space of the alcove so with the location alteration, the plan is to **maximise usable fridge and freezer space**.

@nelsonic Has done a _lot_ of research into this and suggested the **SAMSUNG RS67N8210S9**.
I have done a few extra pomodoros of research and completely agree this is the one to go for (see below).

## SAMSUNG RS67N8210S9

+ **Fridge capacity**: 407l
+ **Freezer capacity**: 210L
+ **Energy consumption**: 389kWh/year
+ **Width:** 91.2cm

@nelsonic The one you linked to originally seems to have gone up in price by €200 since you linked to it:
https://www.worten.pt/grandes-eletrodomesticos/frigorificos/frigorificos-americanos/frigorifico-americano-samsung-rs67n8210s9-ef-no-frost-178-cm-609-l-inox-6570745

![image](https://user-images.githubusercontent.com/4185328/90528873-03d0fe80-e16b-11ea-8e0a-f97a4e02abd9.png)


But that's ok because it's available much cheaper on Prinfor anyway:
[![image](https://user-images.githubusercontent.com/4185328/90529309-7c37bf80-e16b-11ea-9f4e-c91070db2ac2.png)[(https://www.prinfor.pt/frigorificos/200372-frigorifico-side-by-side-samsung-rs67n8210s9-ef.html?)

## LG GSL360ICEV
+ **Fridge capacity**: 405l
+ **Freezer capacity**: 196L
+ **Energy consumption**: 429kWh/year
+ **Width:** 91.2cm

Doesn't particularly seem to add any value to the Samsung one
https://www.prinfor.pt/frigorificos/135576-frigorifico-side-by-side-lg-silver-gsl-360-icev.html
[![image](https://user-images.githubusercontent.com/4185328/90537136-dbe69880-e174-11ea-866b-0e599ae307c6.png)](https://www.prinfor.pt/frigorificos/135576-frigorifico-side-by-side-lg-silver-gsl-360-icev.html)

<hr/>


I also looked at a number of others that seemed promising, but they either had no ice dispenser like this [Whirlpool one](https://www.elcorteingles.pt/electrodomesticos/A35268323-frigorifico-combinado-whirlpool-btnf-5012-ox-aqua-no-frost-inox/), a lower capacity for a much higher price like this [AEG](https://www.elcorteingles.pt/electrodomesticos/A22145988-frigorifico-americano-rmb86111nx-com-dispensador-de-agua-e-gelo-e-home-bar/) or [this Bosch](https://www.elcorteingles.pt/electrodomesticos/A22019386-frigorifico-americano-kag90aw204-com-dispensador-de-agua-e-gelo-e-homebar/), looked promising but then had a deposit rather than being plumbed like [this LG one](https://www.elcorteingles.pt/electrodomesticos/A22220619-frigorifico-americano-gsj361didv-com-porta-door-in-door-e-dispensador-de-agua-e-gelo/), or pretty much the same capacity as the Samsung for €1000 more like [this LG](https://www.elcorteingles.pt/electrodomesticos/A35057978-frigorifico-americano-lg-gsj761pzzz-no-frost-inox/).

<hr/>

@nelsonic 
I would say let's just order the Samsung from Prinfor tonight so that we can eliminate the dependency we have on this and move forward with building the kitchen?

**Comment by nelsonic** [comment]
@iteles the Samsung I had in mind is actually the **RS68N8221S9/EF** model which has a **`A++`** Energy Rating
https://www.prinfor.pt/frigorificos/260945-frigorifico-side-by-side-samsung-rs68n8221s9-ef.html
![image](https://user-images.githubusercontent.com/194400/90565388-c1291980-e19e-11ea-98eb-409fac6f0337.png)

The Worten link/screenshot you have above is the correct product, as are the specs. ✅ 

+ **Fridge capacity**: 407l
+ **Freezer capacity**: 210L
+ **Energy consumption**: 389kWh/year
+ **Width:** 91.2cm

Ultimately, my _reasoning_ for getting a _plumbed_ fridge with Water/Ice dispenser is that it has a water _filter_.
https://www.samsung.com/us/home-appliances/refrigerators/water-filters
![image](https://user-images.githubusercontent.com/194400/89722286-af49b880-d9df-11ea-9e61-43aabd11d0cd.png)

So in addition to cooling the water (_some like it cold_) it filters it _automatically_ without having to _refill_ Brita jugs. 

If our objective is to _reduce_ the amount of human effort required, this is a great way to get _cold_ filtered water.
My only "concern" is the same as yours: someone _breaking_ the dispenser button. 🤷‍♂️

**Comment by iteles** [comment]
I think we've debated this enough. Let's get the Samsung you found as it's undoubtedly the best price-quality ratio and then we can move on to building the kitchen 👍

**Comment by nelsonic** [comment]
There are 3 grades of "refurbished" (_or as you put it "upcycled"_) items: **`A`**, **`B`** and **`C`**:
https://www.worten.pt/outlet/o-que-e-a-worten-outlet-online
![image](https://user-images.githubusercontent.com/194400/90979507-5c2e4480-e54d-11ea-8d8e-a6609e7f3451.png)

Google Translate:
![image](https://user-images.githubusercontent.com/194400/90979526-8253e480-e54d-11ea-9f69-6249bbfb0a05.png)

If the available fridge was **`C`** Grade I'd expect _significant_ damage, and thus I wouldn't consider buying it. 👎 
Whereas the **`B`** Grade _probably_ just has a couple of scratches so they can't sell it as **`A`** ("As New") but is otherwise good. 👍

**Comment by iteles** [comment]
In case I wasn't particularly clear above: let's buy this fridge.

I spoke to Worten and they confirmed that:
+ They will deliver into the home
+ The returns policy is the same as with other products

**Comment by nelsonic** [comment]
Order placed:
![image](https://user-images.githubusercontent.com/194400/90987432-fa88cd00-e582-11ea-863b-c7d0dd309802.png)

Nº de pedido: **`33391134`**
Entidade: **`23239`**
Referência: **`873762006`**
Montante: **`947.36€`**

<img width="320" alt="payment-request-accepted" src="https://user-images.githubusercontent.com/194400/90987609-1771d000-e584-11ea-8386-b96268940d35.png">

<img width="504" alt="image" src="https://user-images.githubusercontent.com/194400/90987600-0a54e100-e584-11ea-9dba-b81498f7cc30.png">

# 💸 🙄 --> 🚰 🧊 --> ❤️ ✅ 

This is _definitely_ "_extravagant_". 💰 
But I'm fairly certain having **_filtered_ cold water** and **ice** "on tap" will bring [***joy***](https://youtu.be/_ea6i0J8W2U) to the people living in the house. 💭
I will certainly use these two features _every_ day without fail. I _love_ cold water and iced tea. 🍹 
Drink more _cold_ water: https://pubmed.ncbi.nlm.nih.gov/14671205 + https://pubmed.ncbi.nlm.nih.gov/30722649💧

**Comment by iteles** [comment]
The wrong fridge was delivered.

They delivered a model  RS68N8**3**21S9/EF instead of a  RS68N8221S9/EF which just so happened to make a pretty big difference because the one we _bought_ is plumbed and the one they _delivered_ is not 🤦‍♀️ 

I've booked a collection for the one in our house on Friday (28-Aug-2020) during which they will _try_ to substitute it for the model we ordered _if_ they find it in their warehouse. This is HIGHLY unlikely.

99% likely that they will take the wrong fridge away, refund the money within a week or so and then we have to buy a new one. But we won't know until Friday.

**Comment by nelsonic** [comment]
@iteles sadly, while the "wrong" fridge model was delivered (_and we should definitely return it_), ↩️ 
We do _not_ want them to attempt to substitute it for the RS68N**8221**S9/EF model. (_see detail below_) 🙄 

When the fridge arrived, it looked "OK"; only a handful of minor scratches, very good condition. ✅ 
_However_ when we _opened_ it, we noticed that it had a **Water Deposit/Tank** on the shelf:

![photo-of-delivered-fridge](https://user-images.githubusercontent.com/194400/91356181-2d32ff80-e7e7-11ea-94bd-9005de81b608.jpeg)

That water tank is an obvious red flag. 🚩

The left ***side*** (external) of the fridge the has the following label: 
![external-fridge-label](https://user-images.githubusercontent.com/194400/91355542-34a5d900-e7e6-11ea-8d5a-18d8561c37e9.jpeg)

_However_ the ***inside*** of the fridge has the following label:
![internal-fridge-label](https://user-images.githubusercontent.com/194400/91355632-569f5b80-e7e6-11ea-81ad-c3a21c9ce6eb.jpeg)

This is how we confirmed the model mismatch before calling Worten technical/customer support. 

# But ...

As it turns out, ***both*** these models are ***non-plumbed***!! 🤦 
Though, in my defence, the RS68N**8221**S9/EF does not _say_ it's "non-plumbed" anywhere!! 🔍 

The Worten product page for the  RS68N**8221**S9/EF
https://www.worten.pt/produtos/frigorifico-americano-samsung-rs68n8221s9-ef-no-frost-178-cm-617-l-inox-6559321
Has the following _internal_ picture: (_no sign of the water deposit!_)
![image](https://user-images.githubusercontent.com/194400/91355815-a0884180-e7e6-11ea-92fe-f81dbefea811.png)

There is _definitely_ no water tank on the shelf:
![worten-fridge-page-no-tank-on-shelf](https://user-images.githubusercontent.com/194400/91365764-d256d380-e7f9-11ea-8132-26ec27ed5839.png)

And there is no detail on whether this is plumbed or non-plumbed. So I re-checked the Samsung Website:

# 8221

The RS68N8**2**21S9EF model has the water tank in the product photos on the Samsung website: 🤦 
https://www.samsung.com/pt/refrigerators/side-by-side-rs68n8221s9/RS68N8221S9EF

![samsung-RS68N8221S9-tank](https://user-images.githubusercontent.com/194400/91366393-8016b200-e7fb-11ea-8e36-c9afc2b224d2.png)

But the **8221** model product page does not mention the word "***ligação***" anywhere on the page:

![no-mention-of-ligação](https://user-images.githubusercontent.com/194400/91366334-62494d00-e7fb-11ea-80f9-26b6f6600bb3.png)


# 8321

The RS68N8**3**21S9EF model _also_ has the water tank in the picture:
https://www.samsung.com/pt/refrigerators/side-by-side-rs68n8321s9ef
![samsung-RS68N8321S9](https://user-images.githubusercontent.com/194400/91366476-bb18e580-e7fb-11ea-83f7-5527b42c8a26.png)


The **8321** model clearly states "Sem ligação à rede de água":

![samsung-sem-ligacao](https://user-images.githubusercontent.com/194400/91366262-2a420a00-e7fb-11ea-9e47-85f8a3fe3497.png)





I'm really sorry this is such an unnecessary saga. 😞 
It's a reminder to pay _very_ close attention to detail before moving forward with anything.
If for any reason they do not allow us to return it, there is a Connection kit:
https://www.filtrosfrigorificosamericanos.pt/kit-de-conexo-externa-universal-para-refrigeradores-americanos-p-189.html

![image](https://user-images.githubusercontent.com/194400/91365550-5492c800-e7f9-11ea-9070-d46849516da9.png)

We could simply open the service panel at the back of the fridge and connect this filter directly to the water mains. 

# Next Action: Return this Fridge

Get Worten to collect the incorrect fridge and go back to the drawing board on which _plumbed_ fridge to buy.

**Comment by iteles** [comment]
@nelsonic Whilst we were checking to see if the fridge model was correct, I actually reviewed both **8321** (the incorrect model we were sent) that as per your screenshot is very clearly marked as _not_ plumbed, but I also checked the **8221** _just in case_. 

In the detailed specifications section of the link you shared above for the **8221**, it does actually say that it’s plumbed _despite_ the photo of the water deposit you pointed out. It’s tucked away under a collapsible tab/section so it wouldn’t have shown up in your search:
![E989442B-3D5C-4383-B395-56AC0E39685F](https://user-images.githubusercontent.com/4185328/91373004-2919d880-e80d-11ea-835c-6763f415081e.jpeg)

I reckon your research was right the first time ☺️ Hopefully we don’t have to spend any more time researching a plumbed fridge after all 🙌🏻

**Comment by nelsonic** [comment]
@iteles wow. That's an **_epic_ fail** on Samsung's web team then; confusing customers! 🤦 
Thanks for sharing this screenshot confirming that I wasn't crazy to select the **8221** fridge. 👍 
So if they have a _real_ **8221** in the warehouse, we could _accept_ it? 💭

**Comment by iteles** [comment]
Exactly! But sadly, I highly doubt they will have or most importantly bother to find it. It was likely just a listing error on the outlet site 😒
At least we won’t have to choose a different fridge and can still buy this one new if they can’t find the one in the warehouse 👍🏻

**Comment by nelsonic** [comment]
@iteles now that I've done a bit more digging, I'm a little dubious that the **8221** is in fact plumbed. 😕 
But it's definitely there in the spec: (_as you confirmed above_)
![Samsung-RS68N8221S9-ligacao-rede](https://user-images.githubusercontent.com/194400/91422158-b3366100-e84e-11ea-82cb-cdae9ff0370f.png)

I've spent _way_ too much time on this issue researching alternatives to the "Filtered Cold Water + Ice" problem ... ⏳ ==💸 

I briefly considered getting a dedicated water dispenser and putting it _under_ the counter:
https://www.klarstein.co.uk/Home-appliances/Ice-cube-machines/Ice-Volcano-2GB-Ice-Cube-Machine-LED-12kg-every-24h-2l-6-10min-Black-Black.html
![image](https://user-images.githubusercontent.com/194400/91424730-170e5900-e852-11ea-8b60-aea7b3c08035.png)
But the ice falls into a "storage container" it's not _dispensed_, so people have to open the lid and reach in to access it; so bacteria 🦠  ... It does not _filter_ the water so it will still have the same content and it's **not _plumbed_** so we would need to "rig" it up to create our own system. 🙄 
The Amazon reviews are mixed: 
https://www.amazon.co.uk/Klarstein-Volcano-Performance-Operation-Soft-Touch/dp/B072J2Y6HF
The _noise_ and extra power consumption put me off. 

Let's see what Worten comes back with ... ⏳

**Comment by nelsonic** [comment]
Resume on Monday after coding work is complete: https://www.worten.pt/outlet?categoria=Grandes%20Eletrodom%C3%A9sticos&tipologia=Frigor%C3%ADficos%20Americanos&page=1&sort_by=price&order_by=asc

Considering the SAMSUNG RS68N8671S9 because it is _definitely_ plumbed:
https://www.samsung.com/pt/refrigerators/side-by-side-rs68n8671s9
![image](https://user-images.githubusercontent.com/194400/92333627-ee226b00-f07e-11ea-99a4-5c0f62a00452.png)

Obviously it's a bit more than I wanted to spend, but at this point I just want this issue to be _resolved_ ... ⏳  == 💸 

https://www.worten.pt/outlet/frigorifico-americano-samsung-rs68n8671s9-ef-recondicionado-grade-b-no-frost-178-cm-604-l-inox-7175024

![image](https://user-images.githubusercontent.com/194400/92333596-bb787280-f07e-11ea-98be-b4702fe6b2a4.png)

Will ask Worten customer support if they can credit my account and then we can decide if we still want to use Worten for the fridge or consider an alternative supplier that has the original one we researched/picked ⬆️

**Comment by nelsonic** [comment]
Next: https://www.worten.pt/cliente/conta#/myOrders/pending 
Call: **`210 155 222`** (das 8h às 24h, de 2ª feira a domingo)

I used the online Customer Support https://www.worten.pt/contactos form and sent them the following:

```
Encomendamos um Frigorífico Americano do vosso outlet e quando entregaram 
vimos que era o produto errado; o modelo não correspondia ao que tínhamos encomendado. 
Entretanto devolvemos o frigorífico (errado) na Sexta-feira 28 Agosto. 
A nossa conta diz que a compra está "Pendente" ... 
o que falta para finalizar a devolução?
Muito obrigado, 
Nelson
```

![worten-contact-request-sent](https://user-images.githubusercontent.com/194400/92333938-3c386e00-f081-11ea-9941-a919556ec00b.png)

**Comment by nelsonic** [comment]
Got email response to my online contact:
![worten-email-refund](https://user-images.githubusercontent.com/194400/92386107-063fcc00-f10b-11ea-8d46-3ab5e4ff8f31.png)


_Confirmed_ transaction refunded:
![image](https://user-images.githubusercontent.com/194400/92385930-b3661480-f10a-11ea-8704-d8354c87466f.png)

**Comment by nelsonic** [comment]
Thinking of making a quick trip to Radio Popular after work today to take a look at this model:
https://www.radiopopular.pt/produto/frigorifico-americano-samsung-rs67n8210s9
![image](https://user-images.githubusercontent.com/194400/92391032-e1038b80-f113-11ea-843b-4937af3a89d9.png)

From what I can tell, the key difference between the RS68N8221S9 vs RS67N8210S9 is the handles ...
https://www.samsung.com/pt/refrigerators/side-by-side-rs67n8210s9
![image](https://user-images.githubusercontent.com/194400/92392731-a2bb9b80-f116-11ea-8b97-8b9c2438bfdb.png)

It's plumbed:
![image](https://user-images.githubusercontent.com/194400/92392388-1d37eb80-f116-11ea-8d4b-a623234e024a.png)

**Comment by nelsonic** [comment]
We discussed that the we (_still_) _prefer_ the model _without_ the protruding handles **`Samsung RS68N8221S9/EF`**
https://www.samsung.com/pt/refrigerators/side-by-side-rs68n8221s9/RS68N8221S9EF/
![image](https://user-images.githubusercontent.com/194400/92409423-79ac0280-f138-11ea-93db-98b49ddc7305.png)


For which the best price at the time of writing is €1,058 + €119 (extended warantee) + **€69.90** (delivery)
https://www.kuantokusta.pt/electrodomesticos/Grandes-Electrodomesticos-de-Cozinha/Frigorificos-Americanos/Samsung-RS68N8221S9-EF-p-4-373951
![image](https://user-images.githubusercontent.com/194400/92408657-18832f80-f136-11ea-94f1-73e78d46092f.png)

![image](https://user-images.githubusercontent.com/194400/92407673-21263680-f133-11ea-996d-4bb5f2f6946f.png)

Not really clear from the KuantoKusta (price comparison site) page is that the delivery of a big fridge is a _lot_ more expensive. For Prinfor to carry the fridge up our flight of stairs and into the kitchen it will be an extra **€69.90**:
https://www.prinfor.pt/content/1-entregas
![image](https://user-images.githubusercontent.com/194400/90966759-55acb800-e4ce-11ea-85d9-bc36fc8882d6.png)


If we can wait Black Friday, 27th November ... **81 Days** ... there might be a cheaper option. ⏳ 💭 
![image](https://user-images.githubusercontent.com/194400/92408578-d22dd080-f135-11ea-965b-ed7473fd22d3.png)
![image](https://user-images.githubusercontent.com/194400/92408599-e671cd80-f135-11ea-82c1-0f0696c69176.png)

@iteles I think if we can get the Drinking Water Filtration system #143 ordered and installed in the next month 
_and_ design and build the MR kitchen around the space of this fridge, I don't mind waiting for it, do you? 💭

**Comment by iteles** [comment]
I don't mind either. If it's a blocked for the design and build of the MR kitchen at any stage, we'll get it earlier 👍 

We just have to _agree_ that we're not going to spend another 3 hours researching this apiece on Black Friday 😆

**Comment by nelsonic** [comment]
@iteles I'm not going to spend another _second_ on this until the end of Nov (_unless it's needed to complete the MR kitchen_)
But I think it's worth researching/ordering/installing the Water Filtration System #143 before the fridge. 💭

**Comment by iteles** [comment]
Saw that El Corte Ingles had a big sale on so went to check on 'our fridge':

![image](https://user-images.githubusercontent.com/4185328/94422474-10d80900-017f-11eb-9a20-d958b7bdd3a5.png)

https://www.elcorteingles.pt/electrodomesticos/A26567303-frigorifico-americano-samsung-rs68n8221s9ef-617-l-a/
![image](https://user-images.githubusercontent.com/4185328/94422388-e7b77880-017e-11eb-8b5d-0454bdf47ee8.png)

They started from a much higher price base so the discount is small and they don't appear to offer an extended warranty on this fridge, which I think we really want/need. So no point in doing anything today 👍 

I also feel like the Samsung american fridges are always in the sales so there's an even better chance it'll be in the Black Friday sale.

**Comment by nelsonic** [comment]
https://www.samsung.com/pt/refrigerators/side-by-side-rs68n8221s9/RS68N8221S9EF/
![image](https://user-images.githubusercontent.com/194400/124398906-241c9400-dd10-11eb-9aa6-0c483787cb12.png)

**Comment by nelsonic** [comment]
This was purchased last year and has been working well for us. Closing. ✅
