### ISSUE TITLE
Installation of all fire safety equipment

### ISSUE THREAD

**Issue by iteles** [dwyl/home#83]
We have a fire safety project which our electricians were in charge of installing.
However, now that we have new electricians, this portion falls outside the remit of the new electricians apparently 🙄 

The key issue in getting the attic done asap because that is a blocker for closing off the walls in the attic. Also, this all needs to be done by mid July so that the final finishing touches can be done in order to start painting!

## Tasks
+ [ ] Print out fire safety plans
+ [ ] Book walk-around with Márcio (fire safety expert/fireman)
+ [ ] Walk-around with Márcio to see what still needs to be done
+ [ ] Get quotes for what still needs to be done
+ [ ] Book timelines for work
+ [ ] Discuss quote with previous electrician to figure out remaining budget issues
+ [ ] Get final work done

**Comment by iteles** [comment]
Walk-around booked for Monday 1st July, TBC whether it'll be morning or afternoon.

**Comment by iteles** [comment]
Booked for 09h30 tomorrow (1-Jul-2019).

**Comment by iteles** [comment]
Had the walk-around with Márcio yesterday, confirmed that the following needs to be completed by the electricians so things are ready to be put in place:
+ [ ] Fire detector needs to be added to the washing machine area (this wasn't in the fire safety plans that were approved but will need to be done ideally)
+ [ ] There is a cable missing from the fire safety 'push here in case of emergency' alarm by the door to the library
+ [ ] Upstairs middle room (room 3), the two cables for the fire detector are a little too far apart and need to be brought together

I also found out that the emergency exit lights above the doors that lead to the outside of the house have to be on _permanently_.

There are also a number of things that will have to be updated in the project (locations of one or two things + the addition of the fire detector mentioned above) so I'll co-ordinate with the architects to get this updated so that we can get the fire safety certifications.

Top comment updated.

Now that we have reviewed everything that needs to be done from an electrical point of view, as long as these 3 things are done, Márcio's job is only to add all the equipment once the final coat of paint has been put on and then take care of the certifications.

**Comment by iteles** [comment]
On Friday I walked around with Márcio _and_ the electricians and we ascertained that when tested, the circuits were not working as they should. For example, the emergency switches were all on the same circuit so if one goes off, no one will know where in the house this has gone off.

This needs to be fixed and will add 2 days of electricians time (€480+IVA) and a day of Carlos' time to the budget.
The biggest issue is that timelines are getting very tight so fitting this in, both for the electricians and Carlos will be tricky. We need to stay ontop of the electricians all week.

Tasks updated in OP.

**Comment by iteles** [comment]
Called last week to confirm and all the fire safety equipment has arrived at the warehouse.  Will call Márcio tomorrow to get it delivered to the house.

**Comment by iteles** [comment]
@nelsonic Márcio and his people will be installing fire safety equipment @home tomorrow, 22-Oct-2019, from 09h30 onwards.

I suggest we head in around late morning (11h00 or so) so that they have an opportunity to go around and make a start and in this way when we get there they will already have a plan we can discuss/questions we can answer.

**Comment by nelsonic** [comment]
@iteles any reason we don't aim to arrive at 09:00?

**Comment by iteles** [comment]
> so that they have an opportunity to go around and make a start and in this way when we get there they will already have a plan we can discuss/questions we can answer.

But if you prefer to be there for 09h00 and spend that time formulating the plan _with_ them and inspecting the equipment they bring, we can do that too 👍

**Comment by nelsonic** [comment]
Inês buying fire safety equipment out the back of a random van:
![image](https://user-images.githubusercontent.com/194400/67316392-3df85200-f500-11e9-96e3-f4f692f990c6.png)

Joking obvs ... this is Márcio (_the fire safety expert_) showing Inês samples in his work van. 😉

**Comment by iteles** [comment]
@nelsonic Thanks for that 😂

**Comment by iteles** [comment]
I've emailed Márcio to get quotes for the signage and light blocks, noting that these shouldn't all be permanent lighting.

**Comment by iteles** [comment]
These are the standard signs to be hung pretty much everywhere:

![IMG_4223](https://user-images.githubusercontent.com/4185328/67711915-dee08480-f9ba-11e9-8ea6-3a5f5796072e.JPG)

These are the 'prettier' ones, which I would consider using in extremely prominent places like the entrance hallway and the cost **€22.50+IVA each** 😱 
![IMG_4224 (1)](https://user-images.githubusercontent.com/4185328/67711921-e142de80-f9ba-11e9-8e38-facd4ae179b3.JPG)

Tomorrow we need to go around and count the number of light blocks (and measure them, so I can contact Pedro) and see if there is anywhere we would want to have the prettier, more photo-worthy signs 😬

**Comment by iteles** [comment]
Sent an email asking the specialists for final confirmation on the number of each sign and placement questions so that we can finalise and order the signage.

From my count on the plans there are:
- 3 electrical shut-off signs + 1 for the solar panel shut-off
- 4 fire extinguisher signs
- 14 emergency exit signs
- Attic: 4 more emergency exit + 1 fire extinguisher + 1 emergency cut-off sign (I can't tell the placement of these from the plans)

**Comment by iteles** [comment]
Still chasing this.
