### ISSUE TITLE
'Ocupação de via' license to hook up to electricity

### ISSUE THREAD

**Issue by iteles** [dwyl/home#84]
Sub-task of https://github.com/dwyl/home/issues/70

As part of https://github.com/dwyl/home/issues/70 we need to get a license from the town council to dig up the 3 metre section of pavement that we need to get the house's electricity connected to the EDP electrical box on the corner.

## Tasks
+ [x] Go to CMB to get the right forms
+ [x] Fill in form & sign
+ [x] Confirm whether any additional documents are required and attach those
+ [x] Scan form
+ [x] Burn CD with form
+ [x] Hand in at town council
+ [x] Pick up license and pay

Priority 2 because this will take a while to get approved.

**Comment by iteles** [comment]
Preferred dates from electricians:
22/07/2019, followed by 27th or 29th

**Comment by iteles** [comment]
This was handed in mid-July and we are still waiting. Will go to CMB tomorrow to check status.

**Comment by iteles** [comment]
Called today again (3 calls have happened since the last update) and it's finally ready.

Now all we need to do is pick it up and pay €130 for the privilege 🙄

**Comment by nelsonic** [comment]
@iteles can _I_ collect it from the Council?  (_or does it have to be you because it's in your name...?_)

**Comment by iteles** [comment]
@nelsonic If you pay, they'll hand it to anyone 😆

**Comment by iteles** [comment]
Had to pay for this _twice_ because the licenses are only issued for the following working day and it unexpectedly POURED with rain all day so the work couldn't be done.

![computer-says-no](https://user-images.githubusercontent.com/4185328/67681167-ade55d00-f984-11e9-8ef8-d2293b51c33b.jpg)

Thanks for picking this up (twice) @nelsonic 👍
