### ISSUE TITLE
External water supply points

### ISSUE THREAD

**Issue by iteles** [dwyl/home#86]
Linked to #61 

We have discussed the various 'water points' with our plumbers on a number of occasions, but there are two things to note here:
1. There is currently a provision (I _hope_ and have a vague memory of discussing) for water points coming out from behind the leisure room but this is TBC
2. Having water points all around the back and side garden will imply digging space and burying pipes that will run the length of the garden
3. Having water in the front garden (on the pool side) might be the hardest point and will need to be discussed.

## Tasks
+ [ ] Confirm that there is a provision for external water points
+ [ ] Confirm the location of water supplies required in the garden (e.g. https://github.com/dwyl/home/issues/77#issuecomment-506247820)
  + [ ] This is strongly linked to where the electricity will run #61 
+ [ ] Discuss these in detail with the plumbers AND the electricians

**Comment by iteles** [comment]
Note this is also a very good reason to dig up the area around the machine room to confirm my suspicion that it has not been properly insulated (which has already been confirmed by an anonymous workman to me verbally). Then we can get it all sorted at once.

**Comment by iteles** [comment]
This and #61 need to be decided this week so that we can do the necessary digging.

**Comment by iteles** [comment]
Dropping the priority down here a bit because the outside work has been temporarily put on the back burner whilst we finish the internals.
