### ISSUE TITLE
Getting connected to the water system

### ISSUE THREAD

**Issue by iteles** [dwyl/home#88]
In order to officially switch on the running water for the house (taps, flushes, showers etc), there are a few steps that need to be taken.

Note: I have been asking our plumbers about this for 2 months (both over email and over the phone) specifically noting my concern over the fact that this involved the national water and waste company, traditionally a lumbering giant that takes a while to do anything, particularly in the 'summer holiday' season.

After finally catching someone yesterday @home, the following context is required:
+ AGERE rules dictate that now water meters _must_ be placed outside the house for easy access to meter readings, but ours is placed _inside_ - it will need to be moved outside
+ There has been new piping placed already leading from the house to our front gate, allowing a new water meter to be placed by the front gate (inside or outside will still require some digging) - finally some good news!
+ AGERE will however need to come and do a site visit to determine what needs to be done (and ideally we can convince them to change the pipes 'ramal' leading into the house too)

## Tasks
+ [x] Review work that has already been done on-site by plumbers
+ [x] Email AGERE to request a visit for 'verificação de ligação de ramal de abastecimento de agua da moradia à rua'
+ [x] Book AGERE visit **[they have to call us so it's out of our hands]**
+ [x] Visit conducted
+ [x] New water meter acquired
+ [x] New water meter installation booked
+ [x] New water meter installed
+ [x] New pipes installed by AGERE to the _new_ water meter
+ [x] Running water switched on for @home 🚀

**Comment by iteles** [comment]
Email sent to AGERE requesting visit 12-Jul-2019

**Comment by iteles** [comment]
Spoke to Cristiana about this again today.
She confirmed that we should head to AGERE and speak to them directly to request the new water meter (contador).

A ideia é termos aproveitado uma obra que fizemos no muro para instalar qq coisa pequena para podermos já pôr o contador cá fora e precisavamos de saber quais os proximos passos para ligar ao ramal e ter o contador novo.

**Comment by iteles** [comment]
Finalised at the end of February.
