### ISSUE TITLE
Roof snagging issue

### ISSUE THREAD

**Issue by iteles** [dwyl/home#92]
From Nelson's comment here: https://github.com/dwyl/home/issues/35#issuecomment-528791530

![image](https://user-images.githubusercontent.com/4185328/64420972-61725500-d098-11e9-8891-b586cbf9eeea.png)

Essentially there are 3 major snags:
1. The roofers put screws in the "valleys" of the roof tiles instead of only on the peaks. That means that they will be exposed to more rain water and thus will oxidise and the panels will get damaged. (the Solar Panel installer alerted us to this ... 🙄) So we need to apply 
"Tela líquida" (AKA "Membrana líquida") to all the screws to ensure that no water can enter.
This is the liquid rubber used by the Velux Windows installers to seal around the windows:
![braga-window-guy-applying-liquid-rubber](https://user-images.githubusercontent.com/194400/64414385-2584c300-d08b-11e9-8bd2-f538a7afb6be.jpg)

2. Almost all the Topos (ends) are rushed and thus poorly installed:
![braga-roof-topo-fail](https://user-images.githubusercontent.com/194400/64413845-3254e700-d08a-11e9-9efb-44a69bfd7554.jpg)
![braga-roof-topo-fail](https://user-images.githubusercontent.com/194400/64414453-464d1880-d08b-11e9-8e03-49a4d001cad4.jpg)
This means that we need a _competent_ person (_who isn't going to rush the work and run_) 
to carefully review each panel ending and where necessary remedy the join and paint with Membrana líquida to prevent water entering. 
https://www.leroymerlin.pt/Produtos/Construcao/Impermeabilizacao/Telhados-e-cobertura/WPR_REF_12281612
![image](https://user-images.githubusercontent.com/194400/64417206-8fec3200-d090-11e9-8d86-18a337de9d19.png)

3. **ANTS**!! 🐜 (_and other boring insects_) will _infest_ the ends of the Panels if not sealed properly.
(_we only learned about the pest problem **`after`** we had commissioned the roof in SIPs Panels ..._)
This is _related_ to `#2` above, but it is distinct in that the rain will not "climb" up from _underneath_. 
We need to apply an anti-bug treatment to the ends of _all_ the panels. For this I propose we use a Borate-based solution which will protect against a wide variety of boring bugs. 

_Much_ more detail on borates: http://www.americanborate.com/all-about-borates/borate-applications/borate-wood-preservation/
Bora-Care: https://youtu.be/Rmr_aEodyhg + https://youtu.be/lD-f9a8-OLw

It may seem counter-intuitive to use a ***wood*** treatment for SIPs Panels (_metal and foam_) 
but the foam in the SIPs panels is porous and will thus absorb the liquid so it's functionally similar.

Leroy has a product that will be appropriate: Tratamento universal AXTON incolor:
https://www.leroymerlin.pt/Produtos/Pintura-e-drogaria/Produtos-para-madeira-interior/Tratamento-contra-bichos-e-fungos/WPR_REF_16459800
![image](https://user-images.githubusercontent.com/194400/64416963-15bbad80-d090-11e9-9e89-e5dbd5f804f2.png)

I estimate that there is (_at least_) a **week** of work to be done on finishing the roof. 
The person doing the work will need to be competent/reliable and follow clear instructions.
They will (_obviously_) need to be comfortable with heights (_while wearing provided protection_).

## Tasks
+ [ ] Discuss using Joaquim with Carlos
+ [ ] Discuss work with Joaquim
+ [ ] Check our harnesses are still at the construction site
+ [ ] Buy tela liquida & application materials
+ [ ] Maybe try to find a sub-30 degree week so whoever does this doesn't come down with heat stroke!
![image](https://user-images.githubusercontent.com/4185328/64421126-c332bf00-d098-11e9-8cc0-5fa36bd175d6.png)
