### ISSUE TITLE
Bathroom equipment final check

### ISSUE THREAD

**Issue by iteles** [dwyl/home#95]
I believe there are one or two things missing from the sanitary equipment we agreed (tap in the reduced mobility room?) so we need to do a final check at the site to make sure we can provide a list of exactly what hasn't been delivered yet.

The bathroom folks have said that they may have made a mistake and not invoiced us for the final tap so I'll also need to check this.

## Tasks
+ [x] Create list from 2 invoices already paid for of all material
+ [x] Make sure this document is available offline
+ [x] Check off all the items on-site
+ [x] Communicate missing items to bathroom equipment suppliers
+ [x] Receive order for missing items
+ [x] Palhagua plumbers to install these

**Comment by iteles** [comment]
The spreadsheet has now been created and I've confirmed what's available on-site. https://docs.google.com/spreadsheets/d/1QMjjSDHRhlL-bTvJ7PEsvKcjABOMm3S8wt74mC_OCPU/edit?usp=sharing

The only thing missing is a tap for the reduced mobility bathroom. 

I think that even though they are eye-wateringly expensive, this possibly  the place where it makes the _most_ sense to have a sensor-operated tap as this is more accessible than requiring a big handle to be moved about in order to get water flow. They are also better for conserving water.

HOWEVER, where I think this tap _should_ differ from the others we have in the house is that the other taps we have in the house have a small (arguably finicky) lever on the side for temperature regulation, like in the image below (though these aren't quite the right taps:
![image](https://user-images.githubusercontent.com/4185328/67598178-cd9e3a80-f764-11e9-9e27-e20878560cf9.png)

This lever is not very accessible so I would suggest a pre-mixed, fixed temperature tap for the reduced mobility WC.

**Comment by iteles** [comment]
@nelsonic We should order the final missing tap this week so that it arrives before the electricians start doing the final snagging in a week's time.

**Comment by nelsonic** [comment]
@iteles yes.

**Comment by iteles** [comment]
☺️ The point to agree on was in the comment above this one. But I'll call them Monday and get them to send over the options and prices for the _fixed temperature_ sensor taps 👍

**Comment by nelsonic** [comment]
@iteles I disagree that the temperature control on the tap is "inaccessible".
It would be "bad UX" to have a fixed temperature for the hand tap water. 
at least with the regulator on the tap the temperature _can_ be regulated at the point of use
someone with reduced dexterity could simply _ask_ the house keeper for help.

**Comment by iteles** [comment]
I feel like we need to ask someone with reduced mobility the question. My family experience for this kind of thing is that forcing situations where help has to be requested when it could be avoided is worse than the alternative, but we should ask.

**Comment by nelsonic** [comment]
Inês, how do you intend to _sample_ the target population?
And what question do you intend to ask to avoid bias?
The fact is: most **`public`** accessible bathrooms are designed to _minimise_ cost `while` still meeting the **_minimum_ requirements** of building regulations. That is why you will almost _never_ see a _high quality_ (sensor) tap in a **`public`** accessible bathroom; they cost 2-4 times more money and offer _zero_ benefit to the _designer_/_developer_. The UX benefit of a _great_ tap accrues exclusively to the "_user_". 
I feel that the _next_ course of action would be to ***test*** the **Delabie _sensor_ taps** in the _rest_ of the house  and confirm the operating conditions, specifically how close does a hand need to be to the sensor to activate it? 

https://www.delabie.pt/produtos/490001 (_still a huge fan of the water efficiency of these taps_ 👍) 
![image](https://user-images.githubusercontent.com/194400/68546975-4e4f6e80-03d4-11ea-935b-86552eb65c00.png)


That way we can determine if someone with reduced mobility can _reach_ close enough to the sensor to activate it. The temperature would be set to a "warm but not hot": **35°C**

Water temperature as a factor in handwashing efficacy Michaels et al 2002
https://onlinelibrary.wiley.com/doi/full/10.1046/j.1471-5740.2002.00043.x
Conclusion:  Independent of soil or bacterial type (resident or transient) there was no significant difference in efficacy attributed to water temperature. i.e. water temp is purely a comfort/UX thing and has no baring on cleanliness of hands. If anything, having cooler water encourages people to wash their hands more vigorously and not spend ages running the warm water over their hands.

> I could not find any guidance online for water temperature ...
https://www.cdc.gov/handwashing/show-me-the-science-handwashing.html 
> The best I could find was this forum thread on https://www.ifsqn.com (International Food Safety & Quality Network) people conclude that given that the human body hovers around **37°C**, 
a temperature of around 35°C to 45°C is recommended. 

We _could_ always buy the wheelchair #48 and test it ourselves ... 
make a video and then post it online and ask a few people with experience to help clarify.

E.g: in this video Brian Kinney (Paralyzed Living) shows that his bathroom has "standard" taps:

[![image](https://user-images.githubusercontent.com/194400/68547238-0a119d80-03d7-11ea-98d6-90cb799397d5.png)](https://youtu.be/YhYQ57s8Myk)
https://youtu.be/YhYQ57s8Myk

**Comment by iteles** [comment]
The wheelchair fits fine with our current setup and the sensors are great on these taps (which is why we spent the big bucks on them 💸) so they are great for a wheelchair or otherwise impaired folks for the most part. This was never a question because it was planned this way from the start.

What I was saying is that having a temperature knob on the side where it may be difficult to reach and/or use (because it is small and finnicky) may show a lack of forethought and be frustrating for the users. We could get the exact same tap but _without_ the temperature control (which is what I suggested above) for a less frustrating experience for a number of those people.

However, you seem keen to have the temperature knob, so let's move ahead with this.

**Comment by iteles** [comment]
We have now been told this has to come from the warehouse and will take 1.5 weeks. I expect it to arrive with us on 12-Dec-2019.

**Comment by iteles** [comment]
Final tap installed and electricity hooked up today! 🙌

**Comment by nelsonic** [comment]
@iteles I will check it when I'm there after standup today. 🔍
